Issue 9980 integration tests outside container
dotCMS/core pull request #10006
Opened 2016-10-21 15:05 UTC by maurizo

2016-10-21 15:14 UTC, dsilvam commented on dotCMS/src/integration-test/java/com/dotmarketing/util/IntegrationTestInitService.java
> +    		CacheLocator.init();
Nice!

2016-10-21 18:28 UTC, dsilvam requested changes

2016-10-26 15:44 UTC, jgambarios approved these changes

2016-10-31 16:00 UTC, dsilvam approved these changes

2016-10-31 16:00 UTC, merged