Issue 10035 fix failing unit tests
dotCMS/core pull request #10047
Opened 2016-11-02 14:12 UTC by maurizo

2016-11-02 18:47 UTC, dsilvam approved these changes

2016-11-02 21:38 UTC, jdotcms approved these changes

2016-11-03 14:28 UTC, dsilvam requested changes

2016-11-03 14:28 UTC, dsilvam commented on dotCMS/src/integration-test/java/com/dotcms/util/marshal/MarshalUtilsIntegrationTestTest.java
> +public class MarshalUtilsIntegrationTestTest {
TestTest as suffix

2016-11-04 16:32 UTC, dsilvam requested changes

2016-11-04 16:32 UTC, dsilvam commented on dotCMS/src/integration-test/java/com/dotcms/util/marshal/MarshalUtilsIntegrationTestTest.java
> +public class MarshalUtilsIntegrationTestTest {
Let's remove the double "Test" as suffix

2016-11-04 17:01 UTC, dsilvam approved these changes

2016-11-04 17:01 UTC, merged