#10193 Document new APIs ContentTypeApi and FieldApi
dotCMS/core pull request #10221
Opened 2016-11-29 20:19 UTC by erickgonzalez

2016-11-29 20:27 UTC, jdotcms approved these changes

2016-11-30 22:52 UTC, dsilvam requested changes

2016-11-30 22:52 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/contenttype/business/FieldApi.java
> +	 * Deletes a field in the DB. Also deletes the field variable.
change to : "Deletes a field from a content type (as specified in the passed in Field object)"

2016-11-30 22:52 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/contenttype/business/FieldApi.java
> +	 * Deletes all the fields in the DB related to a Content Type
change to: "Deletes all the fields related to the given Content Type"

2016-11-30 22:52 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/contenttype/business/FieldApi.java
> +	 * Retrieves a List of Fields based on the Content Type Id (structure_inode column).
let's remove "(structure_inode column)."

2016-11-30 22:52 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/contenttype/business/FieldApi.java
> +	 * Deletes the field variable in the DB.
"Deletes a field variable from a field (as specified in the passed in FieldVariable object)."

2016-12-01 15:29 UTC, dsilvam approved these changes

2016-12-01 15:29 UTC, merged