Issue 10398 delete textarea fields mssql
dotCMS/core pull request #10399
Opened 2017-01-06 19:01 UTC by joseorsini

Tested on backported fix to 3.6.1, running on SQL Server DB. 
Works OK

2017-01-09 13:33 UTC, nollymar approved these changes

2017-01-09 13:41 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentFactoryImpl.java
> +            }
I think this if else if else logic can be simplified a bit:
if(DbConnectionFactory.isMsSql() && field.getFieldContentlet().contains("text_area")) {
    whereField.append(" DATALENGTH (").append(field.getFieldContentlet()).append(")");
} else {
  whereField.append(field.getFieldContentlet()).append(" != ");
}

2017-01-10 13:18 UTC, joseorsini commented
@dsilvam please review. Suggestions on code were applied. Thanks for the tip!

2017-01-10 13:40 UTC, dsilvam requested changes

2017-01-10 13:40 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentFactoryImpl.java
>          }
Looks good @joseorsini

2017-01-10 13:40 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentFactoryImpl.java
> +            }
@joseorsini what about here? I think the same thing can be done

2017-01-10 14:49 UTC, dsilvam approved these changes

2017-01-10 14:50 UTC, joseorsini commented on dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentFactoryImpl.java
> +            }
@dsilvam please review. PR has been updated.

2017-01-10 14:53 UTC, merged