#10400 tables styles changes and unnecessary clases removed
dotCMS/core pull request #10494
Opened 2017-01-20 18:15 UTC by woontsoudev

2017-01-20 18:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dotCMS/core?pullRequest=10494) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dotCMS/core?pullRequest=10494) before we can accept your contribution.<br/><hr/>**woon tsou** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2017-01-20 19:30 UTC, jgambarios approved these changes

2017-01-23 14:41 UTC, fmontes requested changes
Code review is in the source, dojo-theme repo.

2017-01-23 18:03 UTC, fmontes approved these changes

2017-01-30 15:03 UTC, jdotcms approved these changes

2017-01-30 15:56 UTC, fmontes requested changes

2017-01-30 15:56 UTC, fmontes commented on dotCMS/src/main/webapp/html/portlet/ext/common/edit_versions_inc.jsp
> +<div style="overflow: hidden">
Not sute why do we need this but If we need it, it's better to create a class for this edit_versions portlet and do whatever it needs to be done.

2017-01-30 15:56 UTC, fmontes commented on dotCMS/src/main/webapp/html/portlet/ext/contentlet/edit_contentlet.jsp
> +			<div class="content-edit__history-status">
If you are "inside" the ```history``` block, this classname should be ```history__status``` I think ```history``` belongs to anothers places beside ```content-edit```

2017-01-30 15:56 UTC, fmontes commented on dotCMS/src/main/webapp/html/portlet/ext/templates/design/design_templates.jsp
> +			<div class="buttonRow-left lineRight portlet-sidebar-wrapper" id="editContentletButtonRow" style="height: 100%; min-height: 617px;position:absolute;top:0px;left:0px;">
I think this two classes ```buttonRow-left lineRight ``` can be removed.

2017-01-30 15:56 UTC, fmontes commented on dotCMS/src/main/webapp/html/portlet/ext/templates/design/design_templates.jsp
> +			<div class="buttonRow-left lineRight portlet-sidebar-wrapper" id="editContentletButtonRow" style="height: 100%; min-height: 617px;position:absolute;top:0px;left:0px;">
Also please create a portlet scss file for this file so you can do something like: ```.design-template__sidebar-wrapper``` and you can put there all the inline styles in this line (and maybe some others)

2017-01-30 15:56 UTC, fmontes commented on dotCMS/src/main/webapp/html/portlet/ext/templates/design/design_templates.jsp
> +						<div class="content-edit-actions">
This reminds me that we need to update this class name because actions buttons are all over dotcms and I attached incorrectly to just content-edit.

2017-01-30 21:52 UTC, fmontes commented on dotCMS/src/main/webapp/html/portlet/ext/contentlet/edit_contentlet.jsp
> +			<hr class="history__divider">
We need a global "divider"

2017-01-30 21:52 UTC, fmontes approved these changes

2017-01-31 14:52 UTC, jgambarios approved these changes

2017-01-31 14:52 UTC, merged