dotCMS/core#10466 create startup task and update SQL scripts
dotCMS/core pull request #11792
Opened 2017-06-01 17:32 UTC by joseorsini

2017-06-01 18:22 UTC, jdotcms approved these changes

2017-06-13 19:00 UTC, jgambarios requested changes
@joseorsini question, if the host names have a max length of 255 why not to increase the sizes to 255 in order to avoid future errors?

2017-06-14 21:21 UTC, joseorsini commented
Suggestions were applied and committed, @jdotcms please review.

2017-06-15 12:00 UTC, joseorsini commented
Suggestions were applied and committed, @jdotcms @jgambarios please review.

2017-06-28 21:57 UTC, dsilvam approved these changes

2017-06-28 21:57 UTC, merged