#11753 Fix sites end point issues
dotCMS/core pull request #11888
Opened 2017-06-14 14:52 UTC by freddyucv

2017-06-14 16:02 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/site/SiteHelper.java
> +			Host host = null;
you can reduce it to

(null != hostId)?hostAPI.find(hostId, user, false):null;

2017-06-14 16:02 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/util/CollectionsUtils.java
> +    public static <K,V> Map<K,V> map(final K key1, final V value1, final K key2, final V value2
A new one hehehe

2017-06-14 16:02 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/business/HostAPIImpl.java
> +            if(showArchived){
you can reduce it to condition = (showArchived)?" +deleted:true":" +deleted:false";

2017-06-14 16:02 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/business/HostAPIImpl.java
> +            if(showArchived){
Condition could be a StringBuilder

2017-06-14 16:37 UTC, dsilvam requested changes

2017-06-14 16:37 UTC, dsilvam commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/business/HostAPI.java
> +	 * @throws DotSecurityException
{DotDataException, DotSecurityException } are not really thrown

2017-06-14 16:37 UTC, dsilvam commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/business/HostAPIImpl.java
> +     * @throws DotSecurityException
{DotDataException, DotSecurityException } are not really thrown

2017-06-14 19:34 UTC, dsilvam approved these changes

2017-06-14 19:37 UTC, jdotcms approved these changes

2017-06-15 17:04 UTC, jgambarios approved these changes

2017-06-15 17:05 UTC, merged