fix-Pagination stop working everywhere
dotCMS/core pull request #12338
Opened 2017-08-15 12:38 UTC by freddyucv

2017-08-15 15:52 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/util/PaginationUtil.java
> +		}else{
you could use params.put (PAGE, (-1 != page)?String.valueOf(page):"pageValue");
In addition pageValue could be a constant

2017-08-16 16:17 UTC, jgambarios requested changes

2017-08-16 16:17 UTC, jgambarios commented on dotCMS/src/main/java/com/dotcms/util/PaginationUtil.java
> +			params.put(PAGE, "pageValue");
**"pageValue"** is the default value if **page** is not set?, is not a weird default for a param?, if nothing was set we should not send the param in the first place or at least send something like **-1**
**Note:** I'm assuming the **page** param is the page number

2017-08-17 12:57 UTC, jgambarios approved these changes

2017-08-21 15:18 UTC, merged