#12852 fixes in SQL statements
dotCMS/core pull request #12853
Opened 2017-10-12 21:16 UTC by joseorsini

#12852

2017-10-19 17:31 UTC, jgambarios approved these changes

2017-10-25 16:56 UTC, jgambarios requested changes

2017-10-25 16:56 UTC, jgambarios commented on dotCMS/src/main/java/com/dotmarketing/util/MaintenanceUtil.java
> +		        "WHERE field.inode = inode.inode) and inode.type like '%s' ",Inode.Type.FIELD.getTableName());
@joseorsini instead of a `like` I think a `=` could be better on that case?

2017-10-27 13:26 UTC, joseorsini commented
Changes were introduced. Please review, @jgambarios

2017-10-27 20:26 UTC, dsilvam approved these changes

2017-10-27 20:27 UTC, merged