Issue 12878 fix validations systemfolder folderapi save
dotCMS/core pull request #12879
Opened 2017-10-17 16:08 UTC by joseorsini

#12878

2017-10-19 16:59 UTC, jgambarios approved these changes

2017-10-25 16:44 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/folders/business/FolderAPIImpl.java
> +            if(FolderAPI.SYSTEM_FOLDER.equals(folder.getInode())) {
Probably you can chain this into one if and &&

2017-10-25 16:44 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/folders/business/FolderAPIImpl.java
> +        if(user==null) user = APILocator.getUserAPI().getSystemUser();
use two lines to do this, such as
```
if(user==null) { 
user = APILocator.getUserAPI().getSystemUser();
}
```

Eventually someone can introduce an error with the current code

2017-10-25 16:44 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/folders/business/FolderAPIImpl.java
> +        Folder f = folderFactory.findFolderByPath(id.getParentPath(), host);
rename to folder

2017-10-25 16:44 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/folders/business/FolderAPIImpl.java
> +        for(Folder folder : allFolders)
you can use a stream here, such as:
```
return allFolder.stream().filter (folder -> permissionAPI.doesUserHavePermission(folder, PermissionAPI.PERMISSION_READ, user, respectFrontEndPermissions)).collect(CollectionsUtils.toImmutableList());
```

2017-10-25 16:44 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/folders/business/FolderAPIImpl.java
> +        List<Folder> full = folderFactory.findThemesByHost(host);
Same comment for the stream here

2017-10-25 16:44 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/folders/business/FolderAPIImpl.java
> +        List<Folder> subFolders = findSubFolders(folder, user, respectFrontEndPermissions);
same of stream

2017-10-25 16:44 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/folders/business/FolderAPIImpl.java
> +        List<Folder> toIterateOver = new ArrayList<Folder>(subFolders);
same of stream

2017-10-25 16:44 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/folders/business/FolderAPIImpl.java
> +                String userId = user.getUserId() != null?user.getUserId():"";
+1

2017-10-25 16:44 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/folders/business/FolderAPIImpl.java
> +            for (final Contentlet c : conList) {
rename to contentlet

2017-10-25 16:44 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/folders/business/FolderAPIImpl.java
> +                for (Contentlet cv : otherLanguageCons) {
+1 and rename to LanguageContentlet

2017-10-25 16:44 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/folders/business/FolderAPIImpl.java
> +            List<Link> links = getLinks(folder, user, respectFrontEndPermissions);
+1

2017-10-25 16:44 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/folders/business/FolderAPIImpl.java
> +            Folder f = findFolderByPath(sb.toString(), host, user, respectFrontEndPermissions);
rename to folder

2017-11-27 19:46 UTC, jgambarios requested changes
@joseorsini sorry but we can not merge this pull with all the format changes on the **FolderAPIImpl** class. 
Probably sending a new pull request with just the fix changes would be easiest than trying to fix this pull?.

2017-11-28 00:45 UTC, joseorsini commented
sure @jgambarios I'll work on that tomorrow morning.

2017-11-28 19:35 UTC, jgambarios commented
Closed as there is a new pull request https://github.com/dotCMS/core/pull/13124

2017-11-28 19:35 UTC, closed without merging