Create jersey endpoint to get containers
dotCMS/core pull request #13024
Opened 2017-11-09 16:22 UTC by freddyucv

2017-11-09 16:34 UTC, jdotcms approved these changes

2017-11-09 17:18 UTC, oarrietadotcms approved these changes

2017-11-09 17:49 UTC, dsilvam requested changes

2017-11-09 17:49 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/container/ContainerResource.java
> +@Path("/v1/container")
Let's rename to containers, in plural

2017-11-09 17:49 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/container/ContainerResource.java
> +     * Url example: v1/contenttype?query=New%20L&limit=4&offset=5&orderby=name-asc
update example

2017-11-17 17:07 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/util/pagination/ContainerPaginator.java
> +        this.containerFactory = containerFactory;
why do we use the containerFactory and not the containerAPI?

2017-11-20 15:57 UTC, dsilvam approved these changes

2017-11-20 15:58 UTC, merged