Fixing permission error in PageResource
dotCMS/core pull request #13801
Opened 2018-03-06 20:10 UTC by freddyucv

2018-03-06 20:11 UTC, dsilvam approved these changes

2018-03-07 15:45 UTC, jgambarios requested changes

2018-03-07 15:45 UTC, jgambarios commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResource.java
> +            final Template template = this.templateAPI.findWorkingTemplate(page.getTemplateId(), APILocator.getUserAPI().getSystemUser(), false);
Why should we use the system user here?, why not to use the logged in user, templates are permissionable, not sure the logic behind this but only a user with the right permissions should be able to render a template right?

2018-03-07 16:48 UTC, jgambarios commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResource.java
> +            final Template template = this.templateAPI.findWorkingTemplate(page.getTemplateId(), APILocator.getUserAPI().getSystemUser(), false);
Looks like that is how it used to work.

2018-03-07 16:48 UTC, jgambarios approved these changes

2018-03-07 16:49 UTC, merged