Issue update render html endpoint for languages and personas
dotCMS/core pull request #13861
Opened 2018-03-14 14:08 UTC by freddyucv

2018-03-14 14:28 UTC, nollymar approved these changes

2018-03-14 20:56 UTC, jgambarios requested changes

2018-03-14 20:56 UTC, jgambarios commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResource.java
> +                                   @QueryParam("language_id") @DefaultValue("LIVE_ADMIN") final String languageId,
That `@DefaultValue("LIVE_ADMIN")` looks wrong for a `language_id`, I think it is a typo

2018-03-15 13:32 UTC, jgambarios approved these changes

2018-03-15 13:32 UTC, merged