#14024 fixes
dotCMS/core pull request #14069
Opened 2018-04-09 18:16 UTC by joseorsini

Tested against master:

- Contents with multiple versions see only their live and/or working version copied over, whenever we decide to copy a content, or its parent site.
- Contents with different language versions will their live and/or working versions copied, and old versions will be excluded as expected.

2018-04-10 14:25 UTC, oarrietadotcms approved these changes

2018-04-12 17:37 UTC, jgambarios requested changes

2018-04-12 17:37 UTC, jgambarios commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/business/ContentletAPI.java
> +	 * Note this method should not be used currently because it could pull too many versions.
I think we should change the javadoc explaining what the `bringOldVersions` does

2018-04-12 22:37 UTC, jgambarios approved these changes

2018-04-12 22:37 UTC, merged