Issue 12677 role selector workflow step editor
dotCMS/core pull request #14127
Opened 2018-04-14 00:33 UTC by fabrizzio-dotCMS

2018-04-14 17:51 UTC, jdotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/workflows/business/WorkflowAPITest.java
> +        assertTrue(null != actions && actions.size() == 1);
this kind of things is better to separated on two assert
assertNotNull
assertEquals (2, actions.size);

Give you more info about what is the error

2018-04-14 17:51 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/workflows/ajax/WfRoleStoreAjax.java
> +    private String rolesToJson ( List<Role> roles, boolean includeFake, boolean includeLabelAll ) throws IOException, DotDataException, LanguageException {
it is a legacy tradition to include flag parameters as a boolean in the functions, we are trying to leave it and start doing things such as

allRolesToJson or something like that.

In that case I think it is not an issue b/c it is a private method but just to keep in mind

2018-04-14 17:51 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/workflows/ajax/WfRoleStoreAjax.java
>  	        map.put( "name", "" );
replace "" by StringPool.EMPTY

2018-04-14 17:51 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/workflows/business/WorkflowAPI.java
> +	 *
Add documentation here

2018-04-14 17:51 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/workflows/business/WorkflowAPIImpl.java
> +	public List<WorkflowAction> findActions(WorkflowStep step, Role role) throws DotDataException,
set always params to final

2018-04-14 17:51 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/workflows/business/WorkflowAPIImpl.java
> +			return Collections.emptyList();
I am wondering if we should start using Optional for this scenarios

2018-04-14 17:51 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/workflows/business/WorkflowAPIImpl.java
> +			return Collections.emptyList();
or even throw an Illegal Arg Exception

2018-04-14 17:51 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/workflows/business/WorkflowAPIImpl.java
> +	public List<WorkflowAction> findActions(WorkflowStep step, Role role) throws DotDataException,
Remember to add the @closeDbIfOpened annotation

2018-04-14 17:51 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/workflows/business/WorkflowAPIImpl.java
> +	public List<WorkflowAction> findActions(WorkflowStep step, Role role) throws DotDataException,
and the override too

2018-04-14 17:51 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/workflows/business/WorkflowAPIImpl.java
> +			final WorkflowAction wa = iterator.next();
we are trying to use meaningful names, you can rename to workflowAction

2018-04-16 14:16 UTC, jgambarios requested changes
Great work Fabrizzio!, now that you are there I think we can remove these extra queries that I think no one is using: https://github.com/dotCMS/core/blob/issue-12677-role-selector-workflow-step-editor/dotCMS/src/main/webapp/html/portlet/ext/workflows/schemes/view_steps.jsp#L21-L26

2018-04-16 16:11 UTC, jdotcms approved these changes

2018-04-17 13:47 UTC, fabrizzio-dotCMS commented
Again the requested changes were made. The unused queries are no longer there.

2018-04-17 14:14 UTC, jgambarios approved these changes

2018-04-17 14:14 UTC, merged