Issue 13566 add incremental number to container UUID
dotCMS/core pull request #14154
Opened 2018-04-18 15:05 UTC by freddyucv

2018-04-18 16:12 UTC, jdotcms requested changes

2018-04-18 16:47 UTC, jdotcms approved these changes

2018-04-19 16:40 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResourceHelper.java
> +
Maybe an integration for this change also?

2018-04-23 14:40 UTC, dsilvam approved these changes

2018-04-23 14:58 UTC, merged