#14108 Changing the way metadata fields were handled
dotCMS/core pull request #14240
Opened 2018-04-27 15:56 UTC by nollymar

1. Now, metadata fields saved in DB and indexed are defined through this property: INDEX_METADATA_FIELDS
2. Lucene queries that include metadata fields have to be referenced as metadata.{field} instead of fileAsset.metadata.{field}

2018-04-27 18:10 UTC, jgambarios approved these changes

2018-04-30 15:12 UTC, dsilvam requested changes

2018-04-30 15:12 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/tika/TikaUtils.java
> +        return Collections.EMPTY_SET;
This shows yellow in IDEA because of unchecked type returned. Replace with `Collections.emptySet()`

2018-04-30 15:15 UTC, dsilvam commented on dotCMS/src/integration-test/java/com/dotcms/tika/TikaUtilsTest.java
> +    public void test_FilterMetadataFields_WhenMapEmpty_ReturnsEmptyMap() throws DotDataException {
I think dataProviders could have been used for these cases? Just to take into consideration

2018-04-30 17:34 UTC, dsilvam requested changes

2018-04-30 17:34 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESMappingAPIImpl.java
>  					String lvar=con.getStructure().getVelocityVarName().toLowerCase();
remove unused variable

2018-04-30 19:44 UTC, dsilvam approved these changes

2018-04-30 19:44 UTC, merged