Issue 14431 unable to see the fe if you are logged in the backend and vice verse
dotCMS/core pull request #14510
Opened 2018-05-29 22:29 UTC by freddyucv

2018-05-29 23:00 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/rendering/velocity/servlet/VelocityServlet.java
> +        boolean comeFromAdmin = req.getAttribute(WebKeys.COME_FROM_ADMIN) != null ?
yeah set to final

2018-05-29 23:02 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/rendering/velocity/servlet/VelocityServlet.java
> +        String url = String.format("/dotAdmin/#/edit-page/content?url=%s", requestURI);
set to final

2018-05-30 14:09 UTC, jgambarios requested changes

2018-05-30 14:09 UTC, jgambarios commented on dotCMS/src/main/java/com/dotcms/rendering/velocity/servlet/VelocityServlet.java
> +        response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
Do we need to always disable the browser cache?, maybe we should do it only when editing the page and if it is a regular browsing allow the front end to interact with the browser normally.

2018-05-30 15:27 UTC, jgambarios approved these changes

2018-05-31 18:22 UTC, dsilvam approved these changes

2018-05-31 18:22 UTC, merged