finding content by current language
dotCMS/core pull request #14792
Opened 2018-07-05 20:08 UTC by freddyucv

2018-07-05 21:46 UTC, nollymar reviewed
Is it possible to include an IT?

2018-07-06 13:20 UTC, freddyucv commented
Test for MultiTreeAPIImpl are included in this issue

https://github.com/dotCMS/core/issues/14386

I can try do some test  for PageContextBuilder.java too in that issue

2018-07-06 15:27 UTC, jgambarios requested changes

2018-07-09 12:47 UTC, jgambarios approved these changes

2018-07-09 12:48 UTC, merged