aligment issues
dotCMS/core pull request #14997
Opened 2018-07-30 20:59 UTC by hmoreras

2018-07-30 21:07 UTC, alfredo-dotcms commented on dotCMS/src/main/webapp/html/portlet/ext/workflows/schemes/edit_scheme.jsp
> +	<div class="buttonRow" style="position:absolute; bottom:20px; margin-left:146px">
if you have a CSS file, then why not move all inline styles to that file?

2018-07-31 12:30 UTC, freddyucv approved these changes

2018-07-31 15:24 UTC, jgambarios approved these changes

2018-07-31 15:26 UTC, fmontes requested changes
Missing dropdown changes.

2018-07-31 18:40 UTC, fmontes approved these changes

2018-07-31 18:41 UTC, merged