Issue 15056 content types styles
dotCMS/core pull request #15101
Opened 2018-08-13 23:13 UTC by hmoreras

2018-08-14 22:23 UTC, nollymar approved these changes

2018-08-15 17:52 UTC, dsilvam approved these changes

2018-08-15 18:01 UTC, erickgonzalez approved these changes

2018-08-16 16:18 UTC, fmontes requested changes

2018-08-16 16:18 UTC, fmontes commented on dotCMS/src/main/webapp/WEB-INF/messages/Language.properties
> +contenttypes.sidebar.components.title=FIELDS
@hmoreras Never do uppercase message if we have to use css.

2018-08-17 15:34 UTC, merged