Issue 14938 reorder menu doesnt work when you save and publish the changes of the page
dotCMS/core pull request #15210
Opened 2018-08-27 21:17 UTC by alfredo-dotcms

2018-08-27 22:43 UTC, fmontes requested changes

2018-08-27 22:43 UTC, fmontes commented on dotCMS/src/main/webapp/html/portlet/ext/folders/order_menu.jsp
> +function emitErrorEvent() {
Too much duplicated code... why don't just create a function where you can pass the event string?

2018-09-04 17:38 UTC, jgambarios approved these changes

2018-09-04 17:41 UTC, fmontes approved these changes

2018-09-04 17:48 UTC, merged