Issue 14966 unable to add new content in second language
dotCMS/core pull request #15303
Opened 2018-09-18 12:41 UTC by freddyucv

2018-09-18 15:29 UTC, dsilvam approved these changes

2018-09-18 20:42 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/action/EditContentletAction.java
> +					Logger.debug(UtilHTML.class, "getLanguagesIcons :: Sibbling Contentlet = "
remember use the supplier
```
Logger.debug(UtilHTML.class, ()->"getLanguagesIcons :: Sibbling Contentlet = "

2018-09-18 20:42 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/action/EditContentletAction.java
> +					for (Field ff : FieldsCache.getFieldsByStructureInode(sibblingContentlet.getStructureInode())) {
rename ff to field and set to final

2018-09-19 17:49 UTC, nollymar approved these changes

2018-09-20 21:09 UTC, jgambarios requested changes

2018-09-20 21:09 UTC, jgambarios commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/action/EditContentletAction.java
> +					Logger.debug(UtilHTML.class, ()->"getLanguagesIcons :: Sibbling Contentlet = " + sibblingContentlet.getInode());
Wrong logger, is using `UtilHTML.class` and a wrong message `getLanguagesIcons`

2018-09-21 14:34 UTC, jgambarios approved these changes

2018-09-21 14:34 UTC, merged