Issue 15359 pp language fails 2
dotCMS/core pull request #15467
Opened 2018-10-22 16:01 UTC by fabrizzio-dotCMS

2018-10-31 15:39 UTC, jdotcms approved these changes

2018-11-01 15:34 UTC, jgambarios requested changes

2018-11-01 15:34 UTC, jgambarios commented on dotCMS/src/main/java/com/dotcms/publishing/PublisherConfig.java
> +	 *
Javadoc

2018-11-01 15:34 UTC, jgambarios commented on dotCMS/src/main/java/com/dotcms/publishing/PublisherConfig.java
> +	 *
Javadoc

2018-11-01 15:34 UTC, jgambarios commented on dotCMS/src/main/java/com/dotmarketing/util/StringUtils.java
> +    public static boolean equalsNullSafeIgnoreCase(final String a, final String b){
Are we using this new method?

2018-11-02 14:20 UTC, jgambarios approved these changes

2018-11-02 14:20 UTC, merged