Update build.gradle
dotCMS/core pull request #15665
Opened 2018-12-06 16:14 UTC by mwoodland

Issue #15663 - don't include the slf4j-simple library

2018-12-06 16:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dotCMS/core?pullRequest=15665) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dotCMS/core?pullRequest=15665) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dotCMS/core?pullRequest=15665) it.</sub>

2018-12-17 19:24 UTC, jgambarios requested changes
After removing locally the `slf4j-simple` dependency I have dependencies errors starting dotCMS:

```
DEBUG: DYNAMIC WIRE: [com.dotcms.tika [1](R 1.0)] osgi.wiring.package; (osgi.wiring.package=*) -> [org.apache.felix.framework [0](R 0)]
ERROR: Bundle jcl.over.slf4j [2] Error starting file:/Users/jonathan/Projects/dotCMS/repository/git/tomcat8/webapps/ROOT/WEB-INF/felix/bundle/jcl-over-slf4j-1.7.25.jar (org.osgi.framework.BundleException: Unable to resolve jcl.over.slf4j [2](R 2.0): missing requirement [jcl.over.slf4j [2](R 2.0)] osgi.wiring.package; (&(osgi.wiring.package=org.slf4j.spi)(version>=1.7.25)) [caused by: Unable to resolve slf4j.api [8](R 8.0): missing requirement [slf4j.api [8](R 8.0)] osgi.wiring.package; (&(osgi.wiring.package=org.slf4j.impl)(version>=1.6.0))] Unresolved requirements: [[jcl.over.slf4j [2](R 2.0)] osgi.wiring.package; (&(osgi.wiring.package=org.slf4j.spi)(version>=1.7.25))])
org.osgi.framework.BundleException: Unable to resolve jcl.over.slf4j [2](R 2.0): missing requirement [jcl.over.slf4j [2](R 2.0)] osgi.wiring.package; (&(osgi.wiring.package=org.slf4j.spi)(version>=1.7.25)) [caused by: Unable to resolve slf4j.api [8](R 8.0): missing requirement [slf4j.api [8](R 8.0)] osgi.wiring.package; (&(osgi.wiring.package=org.slf4j.impl)(version>=1.6.0))] Unresolved requirements: [[jcl.over.slf4j [2](R 2.0)] osgi.wiring.package; (&(osgi.wiring.package=org.slf4j.spi)(version>=1.7.25))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4149)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2119)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
```

2018-12-18 19:54 UTC, jgambarios requested changes
https://github.com/dotCMS/core/issues/15663#issuecomment-448348495

2019-02-05 20:51 UTC, wezell commented
This breaks other things

2019-02-05 20:51 UTC, closed without merging