15589
dotCMS/core pull request #15666
Opened 2018-12-06 16:21 UTC by mwoodland

2018-12-17 19:37 UTC, jgambarios requested changes

2018-12-17 19:37 UTC, jgambarios commented on dotCMS/build.gradle
> -    felix group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.25'
This change will cause issues, please look at this comment: https://github.com/dotCMS/core/issues/15663#issuecomment-447967132

2018-12-18 19:55 UTC, jgambarios commented on dotCMS/build.gradle
> -    felix group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.25'
And comment https://github.com/dotCMS/core/issues/15663#issuecomment-448348495

2019-02-05 20:50 UTC, wezell commented
This pull breaks other things

2019-02-05 20:50 UTC, closed without merging