Extended Stream for Strings and lower key map
dotCMS/core pull request #15675
Opened 2018-12-07 20:32 UTC by jdotcms

2018-12-07 20:41 UTC, wezell requested changes
What is this for?

2018-12-07 20:41 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/util/LowerKeyMap.java
> +import org.jetbrains.annotations.NotNull;
Nope.

2018-12-07 20:41 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/util/MapWrapper.java
> +public class MapWrapper<K,V> implements Map<K,V> {
Needs to implement serializable

2018-12-07 20:42 UTC, nollymar approved these changes

2018-12-10 18:38 UTC, nollymar commented
@wezell I'm going to use it in a refactoring I'm doing in ImportUtil.java

2018-12-10 18:39 UTC, nollymar commented on dotCMS/src/main/java/com/dotcms/util/LowerKeyMap.java
> +import org.jetbrains.annotations.NotNull;
Fixed. Now, I'm importing **com.dotcms.repackage.javax.validation.constraints.NotNull**

2018-12-10 18:39 UTC, nollymar commented on dotCMS/src/main/java/com/dotcms/util/MapWrapper.java
> +public class MapWrapper<K,V> implements Map<K,V> {
Done

2018-12-10 19:07 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/util/LowerKeyMap.java
> +        this.putAll(baseMap);
make `putAll` final to overcome this?

2018-12-10 19:42 UTC, dsilvam approved these changes

2018-12-11 15:26 UTC, erickgonzalez approved these changes

2018-12-11 15:26 UTC, merged