#15576 integration tests for each cardinality
dotCMS/core pull request #15697
Opened 2018-12-11 21:29 UTC by erickgonzalez

2018-12-11 23:02 UTC, dsilvam requested changes

2018-12-12 15:08 UTC, erickgonzalez commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/contentlet/business/ContentletCheckInTest.java
> +                                               final String childTypeVar, String cardinality)
done

2018-12-12 15:09 UTC, erickgonzalez commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/contentlet/business/ContentletCheckInTest.java
> +import static org.junit.Assert.assertTrue;
done

2018-12-12 15:31 UTC, erickgonzalez commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/contentlet/business/ContentletCheckInTest.java
> +  public void test_checkinContentlet_RelationshipOneToOneCardinality() throws DotSecurityException, DotDataException{
done

2018-12-12 18:48 UTC, dsilvam approved these changes

2018-12-12 22:03 UTC, nollymar approved these changes

2018-12-12 22:03 UTC, merged