Issue 15695 enhancements containerfile
dotCMS/core pull request #15743
Opened 2018-12-21 20:00 UTC by jdotcms

2018-12-21 21:55 UTC, jcastro-dotcms requested changes

2018-12-21 21:55 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/containers/business/ContainerFactoryImpl.java
> +	private void getPaginatedAssets(final int offset,
It'd be great to have some Javadoc in these methods and classes.

2018-12-21 21:55 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/containers/business/ContainerFactoryImpl.java
> +	private Collection<? extends Permissionable> findFolderAssetContainers(final User user, final String hostId,
It'd be great to have some Javadoc in these methods and classes.

2018-12-26 16:13 UTC, nollymar commented on dotCMS/src/main/java/com/dotmarketing/portlets/containers/business/ContainerFactoryImpl.java
> +					case "modDate asc":
consider a case insensitive comparison (ie.: moddate, title, etc)

2018-12-26 16:49 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/containers/business/ContainerFactoryImpl.java
> +					case "modDate asc":
done

2019-01-07 15:09 UTC, jgambarios approved these changes

2019-01-07 15:14 UTC, merged