dotCMS/core#15509 Upgrade the dot-page-selector.component
dotCMS/core pull request #15790
Opened 2019-01-08 15:47 UTC by freddyucv

2019-01-08 16:07 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/rest/elasticsearch/ESContentResourcePortlet.java
> +			String esQueryStr,
shouldn't be annotated with something?

2019-01-08 16:18 UTC, wezell requested changes
We can't change the signature or the returns of this Method - ESSearch is for general use and is public.  Also, I am pretty sure that the "filters" can and should be done by modifying the elasticsearch query that is being passed in.

2019-01-08 16:37 UTC, wezell commented
I might be wrong, but these changes look very specific to the page selector code and are not of general use which is not the purpose of the ESSearch endpoint.  It is intended to take an ES query and return the content that matches it.

I would 
1. validate that a proper elasticsearch query cannot return the same results and that we need the extra params
2. If ES can do the queries, rewrite the query correctly client site and send it
3.  If ES can't do it alone, we need to put a new method on another endpoint, e.g. the PageResource ( would need to understand what is missing from our ES mapping that would prevent it from working)
4. If we use this endpoint, the live param change is needed as @freddyucv explained to me yesterday.  My question is that should it be a general change in the PageMode.getPageMode(request) call.

2019-01-16 14:46 UTC, jgambarios approved these changes

2019-01-17 13:40 UTC, dsilvam approved these changes

2019-01-17 13:40 UTC, merged