dotCMS/core#15819 1-1 relationship allows you to add more than 1 contentlet
dotCMS/core pull request #15889
Opened 2019-01-24 20:55 UTC by freddyucv

2019-01-24 21:01 UTC, alfredo-dotcms approved these changes

2019-01-24 21:09 UTC, hmoreras requested changes

2019-01-24 21:09 UTC, hmoreras commented on dotCMS/src/main/webapp/html/js/dotcms/dijit/form/ContentSelector.js
> +    selectButtonLabel:'Select',
Add internationalization.

2019-01-24 22:08 UTC, jdotcms commented on dotCMS/src/main/webapp/html/js/dotcms/dijit/form/ContentSelector.js
> +    selectButtonLabel:'Select',
+1

2019-01-24 22:09 UTC, jdotcms approved these changes

2019-01-25 14:52 UTC, jgambarios approved these changes

2019-01-25 15:03 UTC, fmontes approved these changes

2019-01-25 15:03 UTC, hmoreras approved these changes

2019-01-25 17:19 UTC, merged