Issue 15800 file assets identifier enhancements
dotCMS/core pull request #15890
Opened 2019-01-24 21:07 UTC by fabrizzio-dotCMS

2019-01-25 04:29 UTC, jdotcms reviewed
Very nice

2019-01-25 17:15 UTC, jgambarios requested changes

2019-01-25 17:15 UTC, jgambarios commented on dotCMS/src/main/java/com/dotmarketing/portlets/fileassets/business/FileAssetAPIImpl.java
> +				if (languageId == -1){
Why do we care about the language, `languageId` should not even be a parameter, we just care about what is in the identifier table right?

2019-01-25 17:15 UTC, jgambarios commented on dotCMS/src/main/java/com/dotmarketing/portlets/fileassets/business/FileAssetAPIImpl.java
> +						return (null != contAPI.findContentletByIdentifier(fileAssetIdentifier.getId(), false, languageId, APILocator.getUserAPI().getSystemUser(), false));
Why we need to look for the contentlet in order if a assent name was already taken?

2019-01-25 17:26 UTC, jcastro-dotcms approved these changes

2019-01-25 17:26 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java
> +                Logger.debug(this, "No working contentlet found for language: "+ language.toString());
Yes please, very important for Support tasks.

2019-01-25 17:26 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/fileassets/business/FileAssetAPIImpl.java
> +		if( null == fileAssetIdentifier || !InodeUtils.isSet(fileAssetIdentifier.getId()) || "folder".equals(fileAssetIdentifier.getAssetType())){
I think you can use something like `Folder.getType()` to not use the String "folder" directly?

2019-01-30 17:09 UTC, wezell reviewed
See my feedback

2019-01-30 17:09 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java
> +
I am pretty sure we have this method in a few places and don't need to add to the already enormous contentletAPI - see:
`findAllVersions`
`getAllLanguages`

2019-01-30 23:23 UTC, wezell approved these changes

2019-01-31 15:49 UTC, jgambarios requested changes

2019-01-31 15:49 UTC, jgambarios commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/asset/FileAssetsResource.java
> +@Path("/v1/content/asset")
Please change the **path** and **package** to use also `FileAsset`

2019-01-31 15:59 UTC, jgambarios requested changes

2019-01-31 15:59 UTC, jgambarios commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/asset/FileAssetsResource.java
> +@Path("/v1/content/asset")
Also, taking with Daniel should be in plural, something like `@Path("/v1/content/fileassets")`

2019-01-31 15:59 UTC, jgambarios commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/asset/FileAssetsResource.java
> +            @QueryParam("inode") final String inode) throws DotStateException {
The inode should be a path param instead a query param, something like `@Path("/{inode}/resourcelink")`

2019-01-31 17:46 UTC, jdotcms approved these changes

2019-01-31 18:05 UTC, jgambarios approved these changes

2019-01-31 18:07 UTC, merged