Issue 15640 avoid duplicated messages
dotCMS/core pull request #16100
Opened 2019-02-22 04:49 UTC by jdotcms

2019-02-22 14:07 UTC, wezell requested changes

2019-02-22 15:24 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/api/system/event/message/SystemMessageEventUtil.java
> +    private static ThreadLocal<Boolean>                  accumulateUniqueMessagesPerThread = ThreadLocal.withInitial(()-> Boolean.FALSE);
to be honest I didn't like the solution too, will work in another approach

2019-02-22 15:25 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/containers/business/ContainerUtil.java
> +    public void notifyException(final Exception e, final String containerId) {
ok sounds good

2019-02-22 15:26 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/exception/ExceptionUtil.java
> +                if (stackTraceElement.getClassName().indexOf("EditMode") > -1 ||
It is old code, I have merge it with the PageMode when there is a http request available

2019-02-22 20:30 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/exception/ExceptionUtil.java
> +            isPreviewOrEdit = (PageMode.EDIT_MODE == pageMode || PageMode.PREVIEW_MODE == pageMode);
Done

2019-02-22 20:31 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/factories/MultiTreeAPIImpl.java
> +import com.dotmarketing.portlets.containers.business.*;
Done

2019-02-22 20:41 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/containers/business/ContainerUtil.java
> +    public void notifyException(final Exception e, final String containerId) {
Done

2019-02-22 20:41 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/exception/ExceptionUtil.java
> +    public static boolean isPreviewOrEditMode(final Exception e, final HttpServletRequest request) {
Done

2019-02-22 20:42 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/rendering/velocity/services/ContainerLoader.java
> +                final DotStateException e = new DotStateException("Cannot find container for : " + key);
Done

2019-02-26 17:09 UTC, jgambarios approved these changes

2019-02-26 17:11 UTC, merged