#16108 multiples fixes and small enhacements
dotCMS/core pull request #16136
Opened 2019-02-27 07:44 UTC by jdotcms

2019-02-27 13:54 UTC, wezell requested changes
See my coments.

2019-02-27 13:54 UTC, wezell commented on dotCMS/src/main/java/com/dotmarketing/factories/SaveMultiTreeMethodDecorator.java
> +            } catch (DotDataException e) {
While the decorator / annotation pattern is cool, and annotations have their uses in providing hooks/wrappers for legacy code , I really think we need to use them sparingly in what I would consider normal code cases.   In my opinion, annotations create too much code overhead and and misdirection where I think we should be very plain spoken as to what is happening and the amount of classes needed to create them inevitably make supporting the codebase more difficult.  

I much prefer functional objects - where we can add clear methods to our classes that do this work explicitly. 
 In this case, I would vote for a method on the Multitree like
`Multitree.getContainerAsID()` that either returns the uuid (if it is an id) or does the resolution of the path to get the uuid.  Something like that would make the code path very clear - you save a multi-tree and use that method to provide the value when doing the db work.

Also, as another note, we need to be careful mutating the state of a multitree passed in to be saved, which can have unintended consequences.

2019-02-27 15:12 UTC, jgambarios requested changes

2019-02-27 15:12 UTC, jgambarios commented on dotCMS/src/main/java/com/dotmarketing/portlets/folders/business/ApplicationContainerFolderListener.java
> +            CacheLocator.getContainerCache().remove(container);
This could be inside the `ContainerLoader.invalidate`

2019-02-27 15:12 UTC, jgambarios commented on dotCMS/src/main/java/com/dotmarketing/portlets/folders/business/ApplicationContainerFolderListener.java
>              CacheLocator.getContainerCache().remove(container);
This could be inside the `ContainerLoader.invalidate`

2019-02-27 15:12 UTC, jgambarios commented on dotCMS/src/main/java/com/dotmarketing/portlets/containers/business/FileAssetContainerUtil.java
> +    // todo: test me
Do we need Integration tests for it?

2019-03-01 22:03 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/factories/MultiTreeAPIImpl.java
> +        final DotConnect db = new DotConnect().setSQL(DELETE_SQL).addParam(multiTree.getHtmlPage()).addParam(multiTree.getContainerAsID())
Done

2019-03-01 22:04 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/factories/MultiTreeAPIImpl.java
> +            String    containerId = multiTree.getContainerAsID();
done

2019-03-01 22:09 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/containers/business/FileAssetContainerUtil.java
> +        final int endsHost   = path.indexOf(StringPool.FORWARD_SLASH, startsHost+HOST_INDICATOR.length());
Done

2019-03-04 14:32 UTC, jgambarios approved these changes

2019-03-04 14:33 UTC, merged