Issue 16697 remove cleanup personalization
dotCMS/core pull request #16748
Opened 2019-06-18 17:01 UTC by jdotcms

2019-06-18 17:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dotCMS/core?pullRequest=16748) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/dotCMS/core?pullRequest=16748) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: dsilvam<br/>:x: jdotcms<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dotCMS/core?pullRequest=16748) it.</sub>

2019-06-24 18:39 UTC, jdotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/personas/business/DeleteMultiTreeUsedPersonaTagJobTest.java
> +    public static void initData() throws Exception {
Not so much todo

2019-06-24 18:39 UTC, jdotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/personas/business/DeleteMultiTreeUsedPersonaTagJobTest.java
> +    public  void testExecute() throws Exception {
it has several

2019-06-24 19:02 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/personas/business/PersonaAPIImpl.java
> +	public Persona find(final String id, final User user, final boolean respectFrontEndRoles) throws DotDataException, DotSecurityException {
Done

2019-06-25 16:12 UTC, wezell requested changes
Like this a lot- I added a few comments.  Also, there are a number of tests that need to be written to cover the api / reusable functionality.

2019-06-25 16:12 UTC, wezell commented on dotCMS/src/main/java/com/dotmarketing/portlets/personas/business/MultiTreePersonaListener.java
> +            if (versionable.isPresent()) {
Should we check if the persona is live or not?  We could have an working version with `persona:ABC` and the previous version (live) has `persona:DEF`.  Changing personalization to the value of a working version would basically remove any personalization for the live version.

2019-06-25 16:12 UTC, wezell commented on dotCMS/src/main/java/com/dotmarketing/portlets/rules/actionlet/PersonaActionlet.java
> +                        personaAPI.findLive(instance.personaId, user, false):
Should be
`personaAPI.findLive(instance.personaId, user, pageMode.respectAnonPerms):`

2019-06-25 16:12 UTC, wezell commented on dotCMS/src/main/java/com/dotmarketing/portlets/rules/actionlet/PersonaActionlet.java
> +                        personaAPI.find(instance.personaId, user, false);
Should be
personaAPI.find(instance.personaId, user, pageMode.respectAnonPerms):

2019-06-25 16:12 UTC, wezell commented on dotCMS/src/main/java/com/dotmarketing/util/ImportExportUtil.java
> -                            t.setPersonalization(MultiTree.DOT_PERSONALIZATION_DEFAULT);
Again, this will overwrite any personalization that exists in the starter, unless I am missing something?

2019-06-25 16:12 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResource.java
> +    public Response getPersonalizedPersonasOnPage (@Context final HttpServletRequest  request,
Needs Test

2019-06-25 16:12 UTC, wezell commented on dotCMS/src/main/java/com/dotmarketing/business/VersionableAPIImpl.java
> +    public Optional<Versionable> findPreviousVersion(final String identifier)  throws DotDataException, DotStateException,DotSecurityException {
needs tests

2019-06-25 16:12 UTC, wezell commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ContentletListener.java
> +public interface ContentletListener<T extends Contentlet> {
The whole listener thing is super cool, but we need tests on it.

2019-06-28 14:42 UTC, jgambarios approved these changes

2019-06-28 14:43 UTC, merged