dotCMS/core#16734 Internationalization (i18n) dot-form and fields
dotCMS/core pull request #16892
Opened 2019-07-19 16:38 UTC by freddyucv

2019-07-19 16:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dotCMS/core?pullRequest=16892) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dotCMS/core?pullRequest=16892) before we can accept your contribution.<br/><hr/>**Freddy Rodriguez** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dotCMS/core?pullRequest=16892) it.</sub>

2019-07-22 15:20 UTC, wezell requested changes

2019-07-22 15:20 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/cache/KeyValueCache.java
>      public void addByLanguageAndContentType(final long languageId, final String contentTypeId, final KeyValue keyValue);
needs test

2019-07-22 15:20 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/cache/KeyValueCache.java
>      public KeyValue getByLanguageAndContentType(final String key, final long languageId, final String contentTypeId);
needs test

2019-07-22 15:20 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/contenttype/model/field/layout/FieldLayoutColumnSerializer.java
> +        final ContentTypeInternationalization contentTypeInternationalization =
needs test

2019-07-22 15:20 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/contenttype/model/field/layout/FieldUtil.java
> +    public static void setFieldInternationalization(
needs test

2019-07-22 15:20 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/keyvalue/business/KeyValueAPIImpl.java
> +    public KeyValue get(final String key, final long languageId, final ContentType contentType, final User user, final boolean live,
needs test

2019-07-22 15:20 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/rendering/velocity/viewtools/StructuresWebAPI.java
> +			String languageId = request.getParameter("languageId");
Always use the `LanguageWebAPI` to resolve front end language

2019-07-23 16:00 UTC, jgambarios requested changes

2019-07-23 16:00 UTC, jgambarios commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/contenttype/ContentTypeResource.java
> +			@QueryParam("language_id") final Long languageId,
In order to follow the same naming pattern of the method we could change the parameter to `languageId`

2019-07-24 15:17 UTC, dsilvam approved these changes

2019-07-25 15:39 UTC, dsilvam approved these changes

2019-08-07 18:08 UTC, jgambarios approved these changes

2019-08-08 14:28 UTC, dsilvam approved these changes

2019-08-08 14:39 UTC, merged