dotCMS/core#17050 Persona listing endpoint default persona incorrectly translated
dotCMS/core pull request #17207
Opened 2019-09-10 17:45 UTC by freddyucv

2019-09-11 15:28 UTC, jdotcms approved these changes

2019-09-17 17:14 UTC, wezell requested changes
So unless I am wrong, we have 2 languages for a backend user

1. We have the "Admin Language" language they have selected when they logged into the admin, which is one of the 8 translated langs of the backend.

2. We have the "Site Language" which is the language the site is being displayed/previewed as and that content is being managed in.  

We need to make this distinction very clear in our session variables, our request variables and in our method names.

2019-09-17 17:24 UTC, wezell commented
Let's add a new method to our LanguageWebAPI called `Language getBackendLanguage(HttpServletRequest req);`  which will return the language of the admin tool for the user.

2019-09-18 16:13 UTC, jdotcms approved these changes

2019-09-18 18:32 UTC, dsilvam approved these changes

2019-09-18 18:44 UTC, wezell approved these changes
This looks good.

2019-09-18 19:05 UTC, merged