dotCMS/core#17490 Page won't allow a live view if a page has different Live and working versions
dotCMS/core pull request #17491
Opened 2019-10-18 15:20 UTC by freddyucv

2019-10-18 16:10 UTC, wezell approved these changes
Good tests.  The key change is the move from `htmlPage.isLive` to `htmlPage.hasLiveVersion`

2019-10-18 16:14 UTC, wezell requested changes
@freddyucv - Tests don't run automatically anymore.  I think you need to add the new test to `com.dotcms.MainSuite` Test Suite

2019-10-18 16:15 UTC, wezell requested changes
Also, I would merge or rebase with master so we can get green on the tests.

2019-10-21 15:54 UTC, jgambarios approved these changes

2019-10-21 17:25 UTC, merged