Issue 17510 cms anon checking
dotCMS/core pull request #17526
Opened 2019-10-24 19:51 UTC by wezell

2019-10-24 23:01 UTC, fabrizzio-dotCMS requested changes
All of these changes look great. But before I approve this. Can you please elaborate on how the fron-end role on the anonymous user was causing that mess, please?

2019-10-31 15:55 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/business/PermissionAPI.java
> +	    return false;
yeah, or we can even create a deprecation exception hehe

2019-10-31 15:56 UTC, jdotcms approved these changes

2019-10-31 16:57 UTC, fabrizzio-dotCMS approved these changes

2019-10-31 17:20 UTC, merged