Issue 17269 cache fs ops 2
dotCMS/core pull request #17549
Opened 2019-10-29 02:25 UTC by fabrizzio-dotCMS

2019-10-29 15:30 UTC, jdotcms approved these changes

2019-10-29 15:30 UTC, jgambarios approved these changes

2019-10-29 15:48 UTC, wezell requested changes

2019-10-29 15:48 UTC, wezell commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/fileassets/business/FileAssetAPITest.java
> +      assertTrue("FileAssets should be the same Object", asset3 == asset4);
This test looks perfect, but I am missing where the magic is happening, where we put the newly transformed fileAsset back into the contentlet cache?

2019-10-31 18:15 UTC, fabrizzio-dotCMS commented on dotCMS/src/main/java/com/dotcms/rendering/velocity/viewtools/content/FileAssetMap.java
> +        return (FileAssetMap)FileAsset.eagerlyInitializedCopy(fileAssetMap, fileAsset);
@wezell Please Revise the new changes I pushed. It is also looking good on Travis.

2019-10-31 18:29 UTC, wezell approved these changes
I like this pattern much better!

2019-11-01 18:31 UTC, fabrizzio-dotCMS commented on dotCMS/src/main/java/com/dotmarketing/portlets/fileassets/business/FileAssetAPIImpl.java
> +		    //
done

2019-11-01 18:31 UTC, fabrizzio-dotCMS commented on dotCMS/src/main/java/com/dotmarketing/portlets/fileassets/business/FileAssetAPI.java
> +	 *
doced

2019-11-01 18:31 UTC, fabrizzio-dotCMS commented on dotCMS/src/main/java/com/dotcms/util/Loadable.java
> +public interface Loadable {
doced

2019-11-01 18:34 UTC, jgambarios approved these changes

2019-11-04 15:15 UTC, merged