Issue 16597 container as files cache
dotCMS/core pull request #17556
Opened 2019-10-30 21:34 UTC by jdotcms

2019-10-31 12:46 UTC, wezell requested changes

2019-10-31 14:50 UTC, jdotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/containers/business/ContainerAPIImplTest.java
> +        final Folder    folder     = APILocator.getFolderAPI().findFolderByPath
ok I will work on it

2019-10-31 17:18 UTC, wezell commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/containers/business/ContainerAPIImplTest.java
> +        final Folder    folder     = APILocator.getFolderAPI().findFolderByPath
looks great

2019-10-31 17:18 UTC, wezell approved these changes
nice change

2019-11-01 17:55 UTC, jgambarios approved these changes

2019-11-01 17:57 UTC, merged