Issue 17671 cud for language resource
dotCMS/core pull request #17704
Opened 2019-12-04 19:12 UTC by dsilvam

2019-12-04 19:19 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +import com.dotcms.repackage.javax.validation.constraints.Size;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotcms.repackage.javax.validation.constraints.Size'](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 19:19 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +        private String language;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Field language has the same name as a method](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 19:19 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +        private String country;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Field country has the same name as a method](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 19:19 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +        private String languageCode;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Field languageCode has the same name as a method](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 19:19 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguagesResource.java
> +    @Produces({MediaType.APPLICATION_JSON, "application/javascript"})
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String literal "application/javascript" appears 4 times in this file; the first occurrence is on line 95](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 19:19 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +import com.dotcms.repackage.javax.validation.constraints.NotNull;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotcms.repackage.javax.validation.constraints.NotNull'](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 19:19 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +        private String countryCode;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Field countryCode has the same name as a method](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 19:19 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguagesResource.java
> +            } catch (Exception e) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid catching generic exceptions such as NullPointerException, RuntimeException, Exception in try-catch block](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 19:19 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +    public LanguageForm(final LanguageForm.Builder builder) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [It is a good practice to call super() in a constructor](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 19:21 UTC, freddyucv requested changes

2019-12-04 19:21 UTC, freddyucv commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguagesResource.java
> +        } catch (Exception e) {
The exceptions should be handle by the Mappers

2019-12-04 19:21 UTC, freddyucv commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguagesResource.java
> +        } catch (Exception e) {
same before

2019-12-04 19:21 UTC, freddyucv commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguagesResource.java
> +     * @return Response
how is the content as this Response?

2019-12-04 19:21 UTC, freddyucv commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguagesResource.java
> +     * @return Response
how is the content as this Response?

2019-12-04 19:21 UTC, freddyucv commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguagesResource.java
> +        } catch (Exception e) {
same before

2019-12-04 19:21 UTC, freddyucv commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguagesResource.java
> +     * @return Response
same before

2019-12-04 19:21 UTC, freddyucv commented on dotCMS/src/main/java/com/dotmarketing/portlets/languagesmanager/business/LanguageAPIImpl.java
> +				"Language String can't be null or empty");
test?

2019-12-04 19:21 UTC, freddyucv commented on dotCMS/src/main/java/com/dotmarketing/portlets/languagesmanager/business/LanguageFactoryImpl.java
> +			throw new DoesNotExistException("getLanguage failed for id:" + languageId, e);
test?

2019-12-04 19:47 UTC, nollymar commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguagesResource.java
> +                throw new DoesNotExistException(e.getMessage(), e);
Perhaps, the exception name is not the most accurate

2019-12-04 20:14 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguagesResource.java
> +import com.dotmarketing.exception.DotRuntimeException;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotmarketing.exception.DotRuntimeException'](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 20:14 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +import com.dotcms.repackage.javax.validation.constraints.NotNull;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotcms.repackage.javax.validation.constraints.NotNull'](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 20:14 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +        private String countryCode;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Field countryCode has the same name as a method](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 20:14 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +import com.dotcms.repackage.javax.validation.constraints.Size;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotcms.repackage.javax.validation.constraints.Size'](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 20:14 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +        private String language;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Field language has the same name as a method](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 20:14 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +        private String languageCode;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Field languageCode has the same name as a method](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 20:14 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguagesResource.java
> +    @Produces({MediaType.APPLICATION_JSON, "application/javascript"})
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String literal "application/javascript" appears 4 times in this file; the first occurrence is on line 95](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 20:15 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguagesResource.java
> +import com.dotmarketing.exception.DoesNotExistException;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotmarketing.exception.DoesNotExistException'](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 20:15 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguagesResource.java
> +import com.dotcms.rest.api.v1.authentication.ResponseUtil;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotcms.rest.api.v1.authentication.ResponseUtil'](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 20:15 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +    public LanguageForm(final LanguageForm.Builder builder) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [It is a good practice to call super() in a constructor](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 20:15 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +        private String country;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Field country has the same name as a method](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 23:37 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguagesResource.java
> +    private boolean doesLanguageExist(String languageId) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Parameter 'languageId' is not assigned and could be declared final](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 23:37 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +        private String country;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Field country has the same name as a method](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 23:37 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +import com.dotcms.repackage.javax.validation.constraints.Size;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotcms.repackage.javax.validation.constraints.Size'](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 23:37 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +        private String countryCode;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Field countryCode has the same name as a method](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 23:37 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +import com.dotcms.repackage.javax.validation.constraints.NotNull;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotcms.repackage.javax.validation.constraints.NotNull'](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 23:37 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguagesResource.java
> +    @Produces({MediaType.APPLICATION_JSON, "application/javascript"})
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String literal "application/javascript" appears 4 times in this file; the first occurrence is on line 95](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 23:37 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +        private String languageCode;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Field languageCode has the same name as a method](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 23:37 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/languagesmanager/business/LanguageFactoryIntegrationTest.java
> +import com.dotmarketing.exception.DoesNotExistException;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotmarketing.exception.DoesNotExistException'](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 23:37 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguagesResource.java
> +import com.dotmarketing.exception.DotRuntimeException;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotmarketing.exception.DotRuntimeException'](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 23:37 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +    public LanguageForm(final LanguageForm.Builder builder) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [It is a good practice to call super() in a constructor](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 23:37 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +        private String language;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Field language has the same name as a method](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 23:37 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguagesResource.java
> +import com.dotcms.rest.api.v1.authentication.ResponseUtil;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotcms.rest.api.v1.authentication.ResponseUtil'](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-04 23:52 UTC, dsilvam commented on dotCMS/src/main/java/com/dotmarketing/portlets/languagesmanager/business/LanguageAPIImpl.java
> +				"Language String can't be null or empty");
Done

2019-12-05 14:50 UTC, nollymar approved these changes

2019-12-06 16:11 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguagesResource.java
> +    @Produces({MediaType.APPLICATION_JSON, "application/javascript"})
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String literal "application/javascript" appears 4 times in this file; the first occurrence is on line 95](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-06 16:11 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +        private String language;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Field language has the same name as a method](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-06 16:11 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +        private String countryCode;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Field countryCode has the same name as a method](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-06 16:11 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +        private String country;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Field country has the same name as a method](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-06 16:11 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +    public LanguageForm(final LanguageForm.Builder builder) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [It is a good practice to call super() in a constructor](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-06 16:11 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +        private String languageCode;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Field languageCode has the same name as a method](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-06 16:20 UTC, freddyucv approved these changes

2019-12-06 17:00 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +        private String languageCode;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Field languageCode has the same name as a method](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-06 17:00 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +    public LanguageForm(final LanguageForm.Builder builder) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [It is a good practice to call super() in a constructor](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-06 17:00 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +        private String countryCode;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Field countryCode has the same name as a method](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-06 17:00 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +        private String country;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Field country has the same name as a method](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-06 17:00 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguageForm.java
> +        private String language;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Field language has the same name as a method](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-06 17:00 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v2/languages/LanguagesResource.java
> +    @Produces({MediaType.APPLICATION_JSON, "application/javascript"})
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String literal "application/javascript" appears 4 times in this file; the first occurrence is on line 95](https://app.codacy.com/app/dotCMS/core/pullRequest?prid=4616952)

2019-12-06 18:46 UTC, merged