#17994 : As of many versions ago, pushing an archived content would m…
dotCMS/core pull request #18048
Opened 2020-02-26 18:13 UTC by jcastro-dotcms

…ake dotCMS delete it altogether in the receiving instance, which is incorrect. This change allows the Push Publishing feature and the Push Now actionlet the flexibility to push an archived content to the receiver for: (1) Simply flagging it as Archived, or (2) to delete it completely.

2020-02-26 18:20 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/workflows/actionlet/PushNowActionlet.java
> +    private RoleAPI roleAPI = APILocator.getRoleAPI();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Private field 'roleAPI' could be made final; it is only initialized in the declaration or constructor.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5077051)

2020-02-26 18:20 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/workflows/actionlet/PushNowActionlet.java
> +            final boolean forcePush = "true".equals(params.get(PARAM_FORCE_PUSH).getValue()) ? Boolean.TRUE : Boolean.FALSE;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid declaring a variable if it is unreferenced before a possible exit point.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5077051)

2020-02-26 18:20 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/workflows/actionlet/PushNowActionlet.java
> +    private EnvironmentAPI environmentAPI = APILocator.getEnvironmentAPI();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Private field 'environmentAPI' could be made final; it is only initialized in the declaration or constructor.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5077051)

2020-02-26 18:20 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/workflows/actionlet/PushNowActionlet.java
> +    private BundleAPI bundleAPI = APILocator.getBundleAPI();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Private field 'bundleAPI' could be made final; it is only initialized in the declaration or constructor.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5077051)

2020-02-26 18:20 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/workflows/actionlet/PushNowActionlet.java
> +    private UserAPI userAPI = APILocator.getUserAPI();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Private field 'userAPI' could be made final; it is only initialized in the declaration or constructor.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5077051)

2020-02-26 18:20 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/workflows/actionlet/PushNowActionlet.java
> +                    } catch (final Exception e) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid catching generic exceptions such as NullPointerException, RuntimeException, Exception in try-catch block](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5077051)

2020-02-26 18:21 UTC, jdotcms approved these changes

2020-02-26 18:31 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/workflows/actionlet/PushNowActionlet.java
> +                    } catch (final Exception e) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid catching generic exceptions such as NullPointerException, RuntimeException, Exception in try-catch block](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5077051)

2020-02-26 21:00 UTC, nollymar approved these changes

2020-02-28 18:34 UTC, erickgonzalez commented
Since we are doing some changes regarding PP and all its dialogs(changing to angular dialogs), I added this issue to the EPIC. So I think this should not be merged since it will be attacked in Angular.

2020-02-28 18:47 UTC, erickgonzalez requested changes
Since we are doing some changes regarding PP and all its dialogs(changing to angular dialogs), I added this issue to the EPIC. So I think this should not be merged since it will be attacked in Angular.

2020-03-02 17:06 UTC, dsilvam approved these changes

2020-03-02 17:06 UTC, merged