#18094 remove code and config for ES replica mgmt and ES autowire
dotCMS/core pull request #18095
Opened 2020-03-04 18:17 UTC by dsilvam

2020-03-04 19:11 UTC, freddyucv commented on dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESIndexAPI.java
>      public void moveIndexBackToCluster(final String index) throws IOException {
is it possible do a test of this method?

2020-03-05 19:08 UTC, nollymar approved these changes

2020-03-05 19:08 UTC, freddyucv requested changes

2020-03-05 19:08 UTC, freddyucv commented on dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESIndexAPI.java
> +		map.put("index.auto_expand_replicas", "0-all");
test?

2020-03-05 21:49 UTC, freddyucv approved these changes

2020-03-06 15:56 UTC, merged

2020-03-06 17:02 UTC, jdotcms approved these changes