Issue 18310 fixing resource link
dotCMS/core pull request #18317
Opened 2020-04-16 19:56 UTC by jdotcms

2020-04-16 20:03 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +    private final String fieldVar;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused private fields such as 'fieldVar'.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-16 20:03 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +import com.dotmarketing.util.Config;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotmarketing.util.Config'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-16 20:03 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +    private final String fieldVar;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Perhaps 'fieldVar' could be replaced by a local variable.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-16 20:03 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +        assertEquals("http://demo.dotcms.com/application/comments/angular/"+htmlFileName+"?language_id=2",link.getResourceLinkAsString());
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String literal "?language_id=2" appears 4 times in this file; the first occurrence is on line 229](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-16 20:03 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +        try (final FileWriter fileWriter = new FileWriter(file)) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating FileInputStream, FileOutputStream, FileReader, or FileWriter](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-16 20:03 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +            resourceLink.append(request.isSecure()? HTTPS_PREFIX:HTTP_PREFIX);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [StringBuffer (or StringBuilder).append is called consecutively without reusing the target variable.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-16 20:03 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +        final String content = "This is a test temporal file";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String literal "This is a test temporal file" appears 6 times in this file; the first occurrence is on line 123](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-16 20:03 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +import com.dotcms.contenttype.model.type.BaseContentType;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotcms.contenttype.model.type.BaseContentType'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-16 20:03 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +        try (final FileWriter fileWriter = new FileWriter(file)) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unnecessary modifier 'final' on resource specification 'fileWriter': resource specifications are implicitly final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-16 20:03 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +import com.dotcms.contenttype.model.type.DotAssetContentType;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotcms.contenttype.model.type.DotAssetContentType'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-16 20:03 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +import org.mockito.Mockito;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'org.mockito.Mockito'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-16 20:03 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +import java.io.IOException;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'java.io.IOException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 14:38 UTC, nollymar commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +            if (binary==null || identifier == null && UtilMethods.isEmpty(identifier.getInode())){
are there any tests for these new validations ?

2020-04-17 15:25 UTC, freddyucv requested changes

2020-04-17 15:25 UTC, freddyucv commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +        final String htmlFileName = file.getName();
this code should go to a private method to reuse it, o maybe to a util class

2020-04-17 15:25 UTC, freddyucv commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +            if(!(contentlet.isFileAsset() || contentlet.isDotAsset())) {
I think we are mising a test here, when contentlet.isDotAsset() is true

2020-04-17 17:14 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +import org.mockito.Mockito;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'org.mockito.Mockito'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 17:14 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +        assertEquals("http://demo.dotcms.com/application/comments/angular/"+htmlFileName+"?language_id=2",link.getResourceLinkAsString());
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String literal "?language_id=2" appears 4 times in this file; the first occurrence is on line 229](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 17:14 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +        try (final FileWriter fileWriter = new FileWriter(file)) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unnecessary modifier 'final' on resource specification 'fileWriter': resource specifications are implicitly final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 17:14 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +        private Tuple2<String, String> createResourceLink (final HttpServletRequest request, final User user,
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused method parameters such as 'user'.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 17:14 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +import java.io.IOException;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'java.io.IOException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 17:15 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +        try (final FileWriter fileWriter = new FileWriter(file)) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating FileInputStream, FileOutputStream, FileReader, or FileWriter](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 17:15 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +import com.dotmarketing.util.Config;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotmarketing.util.Config'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 17:15 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +        final String content = "This is a test temporal file";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String literal "This is a test temporal file" appears 6 times in this file; the first occurrence is on line 123](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 17:15 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +import com.dotcms.contenttype.model.type.DotAssetContentType;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotcms.contenttype.model.type.DotAssetContentType'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 17:15 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +import com.dotcms.contenttype.model.type.BaseContentType;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotcms.contenttype.model.type.BaseContentType'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 17:52 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +import io.vavr.Tuple4;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'io.vavr.Tuple4'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 17:52 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +import com.dotcms.contenttype.model.type.BaseContentType;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotcms.contenttype.model.type.BaseContentType'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 17:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +        try (final FileWriter fileWriter = new FileWriter(file)) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unnecessary modifier 'final' on resource specification 'fileWriter': resource specifications are implicitly final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 17:52 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +import java.io.IOException;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'java.io.IOException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 17:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +        try (final FileWriter fileWriter = new FileWriter(file)) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating FileInputStream, FileOutputStream, FileReader, or FileWriter](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 17:52 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +        private Tuple2<String, String> createResourceLink (final HttpServletRequest request, final User user,
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused method parameters such as 'user'.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 17:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +        final String content = "This is a test temporal file";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String literal "This is a test temporal file" appears 6 times in this file; the first occurrence is on line 123](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 17:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +        assertEquals("http://demo.dotcms.com/application/comments/angular/"+htmlFileName+"?language_id=2",link.getResourceLinkAsString());
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String literal "?language_id=2" appears 4 times in this file; the first occurrence is on line 229](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 17:52 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +import com.dotcms.contenttype.model.type.DotAssetContentType;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotcms.contenttype.model.type.DotAssetContentType'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 17:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +import com.dotmarketing.util.Config;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotmarketing.util.Config'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 17:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +import org.mockito.Mockito;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'org.mockito.Mockito'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 18:10 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +import com.dotcms.contenttype.model.type.DotAssetContentType;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotcms.contenttype.model.type.DotAssetContentType'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 18:10 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +import com.dotmarketing.util.Config;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotmarketing.util.Config'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 18:10 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +        private Tuple2<String, String> createResourceLink (final HttpServletRequest request, final User user,
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused method parameters such as 'user'.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 18:10 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +        try (final FileWriter fileWriter = new FileWriter(file)) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unnecessary modifier 'final' on resource specification 'fileWriter': resource specifications are implicitly final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 18:10 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +import org.mockito.Mockito;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'org.mockito.Mockito'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 18:10 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +        final String content = "This is a test temporal file";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String literal "This is a test temporal file" appears 6 times in this file; the first occurrence is on line 123](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 18:10 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +        try (final FileWriter fileWriter = new FileWriter(file)) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating FileInputStream, FileOutputStream, FileReader, or FileWriter](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 18:10 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +import java.io.IOException;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'java.io.IOException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 18:10 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +import io.vavr.Tuple4;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'io.vavr.Tuple4'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 18:10 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +        assertEquals("http://demo.dotcms.com/application/comments/angular/"+htmlFileName+"?language_id=2",link.getResourceLinkAsString());
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String literal "?language_id=2" appears 4 times in this file; the first occurrence is on line 229](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-17 18:10 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +import com.dotcms.contenttype.model.type.BaseContentType;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotcms.contenttype.model.type.BaseContentType'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-18 22:52 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/contentlet/model/IntegrationResourceLinkTest.java
> +import com.dotmarketing.business.RelationshipAPI;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotmarketing.business.RelationshipAPI'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-18 22:52 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/contentlet/model/IntegrationResourceLinkTest.java
> +        assertTrue(link.getIdPath().contains("/dA/") && link.getIdPath().contains("/"+htmlFileName)
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String literal "/dA/" appears 4 times in this file; the first occurrence is on line 114](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-18 22:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +import java.io.FileWriter;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'java.io.FileWriter'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-18 22:52 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/util/FileUtil.java
> +		try (final FileWriter fileWriter = new FileWriter(file)) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid instantiating FileInputStream, FileOutputStream, FileReader, or FileWriter](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-18 22:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +import org.mockito.Mockito;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'org.mockito.Mockito'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-18 22:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +import com.dotmarketing.util.Config;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotmarketing.util.Config'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-18 22:52 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/contentlet/model/IntegrationResourceLinkTest.java
> +    public static void prepare() throws Exception {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-18 22:52 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/contentlet/model/IntegrationResourceLinkTest.java
> +        final File file = FileUtil.createTemporalFile("comments-list", "txt", "This is a test temporal file");
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused local variables such as 'file'.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-18 22:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +        assertEquals("http://demo.dotcms.com/application/comments/angular/"+htmlFileName+"?language_id=2",link.getResourceLinkAsString());
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String literal "?language_id=2" appears 4 times in this file; the first occurrence is on line 229](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-18 22:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/portlets/contentlet/model/ResourceLinkTest.java
> +        final File file = FileUtil.createTemporalFile("comments-list", "html", "This is a test temporal file");
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String literal "This is a test temporal file" appears 6 times in this file; the first occurrence is on line 135](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-18 22:52 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/contentlet/model/IntegrationResourceLinkTest.java
> +        com.dotcms.contenttype.model.field.Field binaryField           = fieldMap.get(DotAssetContentType.ASSET_FIELD_VAR);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unnecessary use of fully qualified name 'com.dotcms.contenttype.model.field.Field' due to existing import 'com.dotcms.contenttype.model.field.Field'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-18 22:52 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/util/FileUtil.java
> +		try (final FileWriter fileWriter = new FileWriter(file)) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unnecessary modifier 'final' on resource specification 'fileWriter': resource specifications are implicitly final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5372524)

2020-04-20 14:18 UTC, freddyucv approved these changes

2020-04-20 15:59 UTC, nollymar approved these changes

2020-04-20 16:02 UTC, erickgonzalez approved these changes

2020-04-20 16:25 UTC, merged