#18294 changing the message when file asset has invalid size
dotCMS/core pull request #18326
Opened 2020-04-20 19:10 UTC by jdotcms

Changing the message when a binary field size is invalid

2020-04-21 14:31 UTC, freddyucv approved these changes

2020-04-21 14:38 UTC, erickgonzalez approved these changes

2020-04-21 15:30 UTC, nollymar approved these changes

2020-04-21 15:31 UTC, wezell requested changes

2020-04-21 15:31 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java
> +                            final DotContentletValidationException cve = new DotContentletValidationException(Sneaky.sneak(()->LanguageUtil.get("message.contentlet.binary.file.exceeds.size")));
We need to add the offending file name and the maxsize to the message so the user can fix the situation.

File {0) exceeds the maximum file size of {1}

2020-04-22 14:29 UTC, erickgonzalez approved these changes

2020-04-22 15:47 UTC, merged