#18233 integrating app into the translate actionlet
dotCMS/core pull request #18323
Opened 2020-04-20 05:03 UTC by jdotcms

2020-04-20 14:31 UTC, freddyucv requested changes

2020-04-20 14:31 UTC, freddyucv commented on dotCMS/src/main/java/com/dotcms/translate/GoogleTranslationService.java
> +        return null == host? APILocator.systemHost(): host;
I think we are missing some test here

2020-04-20 16:00 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/translate/TranslationService.java
> +import com.dotmarketing.beans.Host;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'com.dotmarketing.beans.Host'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5384201)

2020-04-20 16:25 UTC, erickgonzalez approved these changes

2020-08-10 18:22 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/translate/TranslationService.java
> +import com.dotmarketing.beans.Host;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.beans.Host'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5384201)

2020-08-11 17:42 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/translate/TranslationService.java
> +import com.dotmarketing.beans.Host;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.beans.Host'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5384201)

2020-08-11 17:42 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/translate/GoogleTranslationService.java
> +        this(Config.getStringProperty("GOOGLE_TRANSLATE_SERVICE_API_KEY", StringPool.BLANK), new JSONTool(), new ApiProvider());
Codacy found an issue: [The String literal "GOOGLE_TRANSLATE_SERVICE_API_KEY" appears 5 times in this file; the first occurrence is on line 51](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5384201)

2020-08-12 14:57 UTC, nollymar commented on dotCMS/src/integration-test/java/com/dotcms/translate/GoogleTranslationServiceIntegrationTest.java
> +public class GoogleTranslationServiceIntegrationTest {
Tests need doc

2020-08-12 15:59 UTC, jdotcms reviewed
very good Erick

2020-08-12 16:43 UTC, erickgonzalez commented on dotCMS/src/integration-test/java/com/dotcms/translate/GoogleTranslationServiceIntegrationTest.java
> +public class GoogleTranslationServiceIntegrationTest {
done

2020-08-12 16:47 UTC, nollymar approved these changes

2020-08-13 15:34 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotcms/translate/GoogleTranslationServiceIntegrationTest.java
> +    public static void prepare() throws Exception {
Codacy found an issue: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5384201)

2020-08-14 20:57 UTC, merged

2020-08-14 21:04 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotcms/translate/GoogleTranslationServiceIntegrationTest.java
> +    public static void prepare() throws Exception {
Codacy found an issue: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5384201)