Issue 18325 allow vanity urls to have params
dotCMS/core pull request #18332
Opened 2020-04-21 02:43 UTC by wezell

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert(queryString!=null);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/mock/request/MockHttpRequest.java
> +                    String[] answer = paramMap.get((String)args[0]);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Local variable 'answer' could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert (request.getParameterMap().size() == 4);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        List<NameValuePair> queryParams = URLEncodedUtils.parse(queryString, Charset.forName("UTF-8"));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Local variable 'queryParams' could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        final Map<String, String> formParameters = ImmutableMap.of("param0", FORM, "param1", FORM, "param2", FORM);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String literal "param2" appears 5 times in this file; the first occurrence is on line 33](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/filters/VanityUrlRequestWrapper.java
> +    public String[] getParameterValues(String name) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Parameter 'name' is not assigned and could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert(!queryString.endsWith("&"));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/filters/VanityUrlRequestWrapper.java
> +    public VanityUrlRequestWrapper(HttpServletRequest request, VanityUrlResult vanityUrlResult) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Parameter 'vanityUrlResult' is not assigned and could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        final VanityUrlResult vanityUrlResult = new VanityUrlResult("/newUrl", "param2=" + VANITY + "&param3=" + VANITY, false);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String literal "param2=" appears 4 times in this file; the first occurrence is on line 42](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/filters/VanityUrlRequestWrapper.java
> +        String[] val = this.queryParamMap.get(name);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Local variable 'val' could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert(!queryString.startsWith("&"));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +    public void test_that_query_string_has_all_the_parameters() {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [JUnit tests should include assert() or fail()](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/mock/request/MockHttpRequest.java
> +                    Object mock = invocation.getMock();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused local variables such as 'mock'.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert(queryString.contains("param1=" + URL));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +    public void test_that_vanity_urls_with_query_params_override_incoming_requests() {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [JUnit tests should include assert() or fail()](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert (request.getParameterValues("param2").length == 2);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert (request.getParameterValues("param2")[0].equals(VANITY));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert (request.getParameter("param1").equals(URL));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +    final String URL = "URL";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This final field could be made static](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert (request.getParameterValues("param2")[1].equals(URL));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert(!queryString.startsWith("&"));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This call to String.startsWith can be rewritten using String.charAt(0)](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert (request.getParameter("param3").equals(VANITY));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/mock/request/MockParameterRequest.java
> +        List<NameValuePair> additional = URLEncodedUtils.parse(request.getQueryString(), Charset.forName("UTF-8"));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Local variable 'additional' could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:52 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/filters/VanityUrlRequestWrapper.java
> +        Map<String,String[]> tempMap = new HashMap<>(request.getParameterMap());
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Local variable 'tempMap' could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 02:53 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +    final String FORM = "FORM";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This final field could be made static](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-21 14:26 UTC, freddyucv requested changes

2020-04-21 14:26 UTC, freddyucv commented on dotCMS/src/main/java/com/dotmarketing/filters/VanityURLFilter.java
> -            }
really this chenge is not tested, I think this test is tested VanityURL maybe we can add a new query params test:

https://github.com/dotCMS/core/blob/master/dotCMS/src/integration-test/java/com/dotmarketing/filters/FiltersTest.java#L162

2020-04-22 04:03 UTC, jdotcms approved these changes

2020-04-22 14:28 UTC, erickgonzalez approved these changes

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/filters/VanityUrlRequestWrapper.java
> +    public String[] getParameterValues(String name) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Parameter 'name' is not assigned and could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/filters/VanityUrlRequestWrapper.java
> +            List<NameValuePair> additional = URLEncodedUtils.parse(newQueryString, Charset.forName("UTF-8"));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Local variable 'additional' could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert(queryParams.size()==4);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert(queryString.contains("param2=" + URL));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        final Map<String, String> formParameters = ImmutableMap.of("param0", FORM, "param1", FORM, "param2", FORM);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String literal "param2" appears 5 times in this file; the first occurrence is on line 33](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/mock/request/MockHttpRequest.java
> +                public String answer(InvocationOnMock invocation) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Parameter 'invocation' is not assigned and could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/mock/request/MockHttpRequest.java
> +                    String[] answer = paramMap.get((String)args[0]);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Local variable 'answer' could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +    public void test_that_query_string_has_all_the_parameters() {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [JUnit tests should include assert() or fail()](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        final VanityUrlResult vanityUrlResult = new VanityUrlResult("/newUrl", "param2=" + VANITY + "&param3=" + VANITY, false);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String literal "param2=" appears 4 times in this file; the first occurrence is on line 42](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/filters/VanityUrlRequestWrapper.java
> +    public VanityUrlRequestWrapper(HttpServletRequest request, VanityUrlResult vanityUrlResult) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Parameter 'vanityUrlResult' is not assigned and could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert(!queryString.endsWith("&"));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/mock/request/MockHttpRequest.java
> +            List<NameValuePair> additional = URLEncodedUtils.parse(queryString, Charset.forName("UTF-8"));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Local variable 'additional' could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert (request.getParameterValues("param2")[0].equals(VANITY));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/mock/request/MockParameterRequest.java
> +        for(NameValuePair nvp : additional) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Local variable 'nvp' could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert (request.getParameter("param0").equals(FORM));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +    final String VANITY = "VANITY";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This final field could be made static](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/mock/request/MockHttpRequest.java
> +                    Object mock = invocation.getMock();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused local variables such as 'mock'.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/filters/VanityUrlRequestWrapper.java
> +            for(NameValuePair nvp : additional) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Local variable 'nvp' could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        List<NameValuePair> queryParams = URLEncodedUtils.parse(queryString, Charset.forName("UTF-8"));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Local variable 'queryParams' could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert(queryString.contains("param3=" + VANITY));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert (request.getParameterValues("param2").length == 2);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert(queryString!=null);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert(!queryString.startsWith("&"));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/mock/request/MockParameterRequest.java
> +        List<NameValuePair> additional = URLEncodedUtils.parse(request.getQueryString(), Charset.forName("UTF-8"));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Local variable 'additional' could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 18:44 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +    public void test_that_vanity_urls_with_query_params_override_incoming_requests() {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [JUnit tests should include assert() or fail()](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:12 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/filters/VanityURLFilter.java
> +    public void destroy() {}
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Document empty method body](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +    public void test_that_query_string_has_all_the_parameters() {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [JUnit tests should include assert() or fail()](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert(queryString.contains("param3=" + VANITY));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +    public void test_that_vanity_urls_with_query_params_override_incoming_requests() {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [JUnit tests should include assert() or fail()](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert(!queryString.endsWith("&"));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert(queryString.contains("param2=" + URL));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/mock/request/MockHttpRequest.java
> +                public String answer(InvocationOnMock invocation) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Parameter 'invocation' is not assigned and could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        final Map<String, String> formParameters = ImmutableMap.of("param0", FORM, "param1", FORM, "param2", FORM);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The String literal "param2" appears 5 times in this file; the first occurrence is on line 33](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/filters/VanityUrlRequestWrapper.java
> +        Map<String,String[]> tempMap = new HashMap<>(request.getParameterMap());
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Local variable 'tempMap' could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/mock/request/MockHttpRequest.java
> +                    Object mock = invocation.getMock();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid declaring a variable if it is unreferenced before a possible exit point.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert(queryString.contains("param1=" + URL));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/filters/VanityUrlRequestWrapper.java
> +            List<NameValuePair> additional = URLEncodedUtils.parse(newQueryString, Charset.forName("UTF-8"));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Local variable 'additional' could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/filters/VanityUrlRequestWrapper.java
> +        String[] val = this.queryParamMap.get(name);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Local variable 'val' could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert (request.getParameter("param0").equals(FORM));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/filters/VanityUrlRequestWrapper.java
> +            for(NameValuePair nvp : additional) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Local variable 'nvp' could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert (request.getParameterValues("param2").length == 2);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert(queryParams.size()==4);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert (request.getParameter("param1").equals(URL));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/mock/request/MockParameterRequest.java
> +        List<NameValuePair> additional = URLEncodedUtils.parse(request.getQueryString(), Charset.forName("UTF-8"));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Local variable 'additional' could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +    final String FORM = "FORM";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This final field could be made static](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/mock/request/MockHttpRequest.java
> +            for(NameValuePair nvp : additional) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Local variable 'nvp' could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert(!queryString.startsWith("&"));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [This call to String.startsWith can be rewritten using String.charAt(0)](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/mock/request/MockParameterRequest.java
> +        for(NameValuePair nvp : additional) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Local variable 'nvp' could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/filters/VanityUrlRequestWrapper.java
> +    public VanityUrlRequestWrapper(HttpServletRequest request, VanityUrlResult vanityUrlResult) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Parameter 'vanityUrlResult' is not assigned and could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, dev-dotcms commented on dotCMS/src/test/java/com/dotmarketing/filters/VanityUrlRequestWrapperTest.java
> +        assert(queryString!=null);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5391667)

2020-04-23 20:13 UTC, freddyucv approved these changes

2020-04-23 21:18 UTC, merged