#18348 fixes done
dotCMS/core pull request #18349
Opened 2020-04-23 21:35 UTC by jdotcms

2020-04-23 21:39 UTC, erickgonzalez approved these changes

2020-04-23 21:45 UTC, dev-dotcms commented on dotCMS/src/main/webapp/html/js/dotcms/dijit/form/FileAjaxUploader.js
> +        const resourceLinkRow = resourceLink && "<tr><td><b>{resourceLinkLabel}</b></td><td><a target=\"_blank\" href=\"{resourceLink}\">{resourceLinkUri}</a></td></tr>";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid using global variables](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5411758)

2020-04-23 21:45 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotcms/util/MimeTypeUtilsTest.java
> +        boolean match = MimeTypeUtils.match("*/pdf", "pdf");
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Local variable 'match' could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5411758)

2020-04-24 17:07 UTC, fabrizzio-dotCMS approved these changes

2020-04-24 17:11 UTC, freddyucv requested changes

2020-04-24 17:11 UTC, freddyucv commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/ResourceLink.java
> +            resourceLink.append(escapeUri(resourceLinkUri.toString()));
I think we are missing a test here

2020-04-28 15:15 UTC, merged