#18310 adding the language to the idPath
dotCMS/core pull request #18340
Opened 2020-04-21 22:11 UTC by jdotcms

2020-04-21 22:14 UTC, erickgonzalez approved these changes

2020-04-22 14:46 UTC, nollymar requested changes

2020-04-22 14:46 UTC, nollymar commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/transform/BinaryToMapTransformer.java
> +        final int contentLanguageSize = Try.of(()->APILocator.getLanguageAPI().getLanguages()).getOrElse(Collections.emptyList()).size();
This logic needs tests

2020-04-22 20:44 UTC, fabrizzio-dotCMS approved these changes

2020-04-22 20:46 UTC, nollymar approved these changes

2020-04-22 20:58 UTC, merged