#18345 on editmode we need to set the page mode to preview
dotCMS/core pull request #18472
Opened 2020-05-11 22:24 UTC by jdotcms

On edit mode we need to set the page mode to preview in order to display images on dA servlet that haven't live version

2020-05-11 22:41 UTC, erickgonzalez approved these changes

2020-05-12 14:43 UTC, freddyucv requested changes

2020-05-12 14:43 UTC, freddyucv commented on dotCMS/src/main/webapp/html/portlet/ext/contentlet/edit_contentlet.jsp
> +	PageMode.setPageMode(request, PageMode.PREVIEW_MODE);
I think this change is dangerous

2020-05-12 15:01 UTC, fmontes commented
Needs another approach

2020-06-16 15:20 UTC, wezell commented
PR: #18561

2020-06-16 19:51 UTC, merged

2020-06-16 19:51 UTC, fmontes commented
Chat with Freddy he mention what to test.