#18616 this preserves the inode when converting a relationship
dotCMS/core pull request #18617
Opened 2020-06-06 21:07 UTC by wezell

2020-06-06 21:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/business/RelationshipAPIImpl.java
> +        final com.dotcms.contenttype.model.field.RelationshipField field = ImmutableRelationshipField.builder()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unnecessary use of fully qualified name 'com.dotcms.contenttype.model.field.RelationshipField' due to existing import 'com.dotcms.contenttype.model.field.RelationshipField'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5653044)

2020-06-06 21:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/business/RelationshipAPIImpl.java
> +        Relationship newRelationship = (Relationship) Try.of(()->  BeanUtils.cloneBean(oldRelationship)).getOrElseThrow(e-> new DotRuntimeException(e));
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Local variable 'newRelationship' could be declared final](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5653044)

2020-06-08 17:12 UTC, nollymar commented
The change seems correct. However, it requires ITs and we need to make sure it doesn't break PP related content

2020-06-09 14:00 UTC, freddyucv requested changes
any test?

2020-06-09 14:04 UTC, wezell commented
I am not sure this is the right solution.  Nolly will be taking a look at this.

2020-06-10 22:14 UTC, dsilvam approved these changes

2020-06-11 04:38 UTC, jdotcms approved these changes

2020-06-11 15:01 UTC, erickgonzalez approved these changes

2020-06-11 16:32 UTC, merged