#18593 making the descriptor  upload endpoint return bad-request when…
dotCMS/core pull request #18743
Opened 2020-06-19 21:18 UTC by fabrizzio-dotCMS

This comes to solve https://github.com/dotCMS/core/issues/18593
I am making the upload endpoint return a Bad-request code when uploading a file that already exists.

2020-06-22 15:32 UTC, erickgonzalez approved these changes

2020-06-23 14:34 UTC, freddyucv requested changes

2020-06-23 14:34 UTC, freddyucv commented on dotCMS/src/main/java/com/dotcms/security/apps/AppsAPIImpl.java
> +                    String.format("There's an App already registered under key `%s`.",
I think we need a new test where this exception is expected

2020-06-24 17:37 UTC, nollymar approved these changes

2020-06-24 17:48 UTC, freddyucv approved these changes

2020-06-24 19:28 UTC, merged