Issue 18563 create resource for bundle operations
dotCMS/core pull request #18760
Opened 2020-06-24 00:16 UTC by dsilvam

2020-06-24 14:17 UTC, freddyucv requested changes

2020-06-24 14:17 UTC, freddyucv commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +    public final Response postMultipart(@Context final HttpServletRequest request, @Context final HttpServletResponse response,
postman test?

2020-06-24 15:10 UTC, erickgonzalez approved these changes

2020-06-25 00:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            InputStream inputStream = (part.getEntity() instanceof InputStream) ? InputStream.class
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-06-25 00:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            if (fileName == null || fileName.startsWith(".") || fileName.contains("/.")) {
Codacy found an issue: [This call to String.startsWith can be rewritten using String.charAt(0)](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-06-25 00:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            InputStream inputStream = (part.getEntity() instanceof InputStream) ? InputStream.class
Codacy found an issue: [Ensure that resources like this boolean object are closed after use](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-06-26 00:17 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            InputStream inputStream = (part.getEntity() instanceof InputStream) ? InputStream.class
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-06-26 00:17 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            if (fileName == null || fileName.startsWith(".") || fileName.contains("/.")) {
Codacy found an issue: [This call to String.startsWith can be rewritten using String.charAt(0)](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-06-26 00:17 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            InputStream inputStream = (part.getEntity() instanceof InputStream) ? InputStream.class
Codacy found an issue: [Ensure that resources like this boolean object are closed after use](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-06-27 00:15 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            InputStream inputStream = (part.getEntity() instanceof InputStream) ? InputStream.class
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-06-27 00:15 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            if (fileName == null || fileName.startsWith(".") || fileName.contains("/.")) {
Codacy found an issue: [This call to String.startsWith can be rewritten using String.charAt(0)](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-06-27 00:15 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            InputStream inputStream = (part.getEntity() instanceof InputStream) ? InputStream.class
Codacy found an issue: [Ensure that resources like this boolean object are closed after use](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-06-29 23:27 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            InputStream inputStream = (part.getEntity() instanceof InputStream) ? InputStream.class
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-06-29 23:27 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            if (fileName == null || fileName.startsWith(".") || fileName.contains("/.")) {
Codacy found an issue: [This call to String.startsWith can be rewritten using String.charAt(0)](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-06-29 23:27 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            InputStream inputStream = (part.getEntity() instanceof InputStream) ? InputStream.class
Codacy found an issue: [Ensure that resources like this boolean object are closed after use](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-06-29 23:27 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResource.java
> +        final InitDataObject initData = webResource.init(request, response,true);
Codacy found an issue: [Avoid declaring a variable if it is unreferenced before a possible exit point.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-06-30 23:15 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +    public final Response postMultipart(@Context final HttpServletRequest request, @Context final HttpServletResponse response,
Done

2020-06-30 23:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            InputStream inputStream = (part.getEntity() instanceof InputStream) ? (InputStream) part
Codacy found an issue: [Ensure that resources like this boolean object are closed after use](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-06-30 23:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            if (UtilMethods.isNotSet(fileName) || fileName.startsWith(".") || fileName.contains("/.")) {
Codacy found an issue: [This call to String.startsWith can be rewritten using String.charAt(0)](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-06-30 23:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/HTMLPageAssetAPIImpl.java
> +import com.dotmarketing.portlets.htmlpageasset.business.render.HTMLPageAssetNotFoundException;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.portlets.htmlpageasset.business.render.HTMLPageAssetNotFoundException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-06-30 23:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResource.java
> +        final InitDataObject initData = webResource.init(request, response,true);
Codacy found an issue: [Avoid declaring a variable if it is unreferenced before a possible exit point.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-06-30 23:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            InputStream inputStream = (part.getEntity() instanceof InputStream) ? (InputStream) part
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-01 04:47 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            InputStream inputStream = (part.getEntity() instanceof InputStream) ? (InputStream) part
Codacy found an issue: [Ensure that resources like this boolean object are closed after use](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-01 04:47 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResource.java
> +        final InitDataObject initData = webResource.init(request, response,true);
Codacy found an issue: [Avoid declaring a variable if it is unreferenced before a possible exit point.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-01 04:47 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/HTMLPageAssetAPIImpl.java
> +import com.dotmarketing.portlets.htmlpageasset.business.render.HTMLPageAssetNotFoundException;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.portlets.htmlpageasset.business.render.HTMLPageAssetNotFoundException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-01 04:47 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            InputStream inputStream = (part.getEntity() instanceof InputStream) ? (InputStream) part
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-01 04:47 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            if (UtilMethods.isNotSet(fileName) || fileName.startsWith(".") || fileName.contains("/.")) {
Codacy found an issue: [This call to String.startsWith can be rewritten using String.charAt(0)](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-01 05:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResource.java
> +        final InitDataObject initData = webResource.init(request, response,true);
Codacy found an issue: [Avoid declaring a variable if it is unreferenced before a possible exit point.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-01 05:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/HTMLPageAssetAPIImpl.java
> +import com.dotmarketing.portlets.htmlpageasset.business.render.HTMLPageAssetNotFoundException;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.portlets.htmlpageasset.business.render.HTMLPageAssetNotFoundException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-01 05:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            InputStream inputStream = (part.getEntity() instanceof InputStream) ? (InputStream) part
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-01 05:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            if (UtilMethods.isNotSet(fileName) || fileName.startsWith(".") || fileName.contains("/.")) {
Codacy found an issue: [This call to String.startsWith can be rewritten using String.charAt(0)](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-01 05:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            InputStream inputStream = (part.getEntity() instanceof InputStream) ? (InputStream) part
Codacy found an issue: [Ensure that resources like this boolean object are closed after use](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-01 14:05 UTC, freddyucv approved these changes

2020-07-01 15:42 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResource.java
> +        final InitDataObject initData = webResource.init(request, response,true);
Codacy found an issue: [Avoid declaring a variable if it is unreferenced before a possible exit point.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-01 15:42 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +                if (UtilMethods.isNotSet(fileName) || fileName.startsWith(".") || fileName
Codacy found an issue: [This call to String.startsWith can be rewritten using String.charAt(0)](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-01 16:26 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResource.java
> +        final InitDataObject initData = webResource.init(request, response,true);
Codacy found an issue: [Avoid declaring a variable if it is unreferenced before a possible exit point.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-01 16:26 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +                if (UtilMethods.isNotSet(fileName) || fileName.startsWith(".") || fileName
Codacy found an issue: [This call to String.startsWith can be rewritten using String.charAt(0)](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-01 17:12 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResource.java
> +        final InitDataObject initData = webResource.init(request, response,true);
Codacy found an issue: [Avoid declaring a variable if it is unreferenced before a possible exit point.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-01 17:12 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +                if (UtilMethods.isNotSet(fileName) || fileName.startsWith(".") || fileName
Codacy found an issue: [This call to String.startsWith can be rewritten using String.charAt(0)](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-01 17:57 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +                if (UtilMethods.isNotSet(fileName) || fileName.startsWith(".") || fileName
Codacy found an issue: [This call to String.startsWith can be rewritten using String.charAt(0)](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-01 17:57 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResource.java
> +        final InitDataObject initData = webResource.init(request, response,true);
Codacy found an issue: [Avoid declaring a variable if it is unreferenced before a possible exit point.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-02 16:10 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResource.java
> +        final InitDataObject initData = webResource.init(request, response,true);
Codacy found an issue: [Avoid declaring a variable if it is unreferenced before a possible exit point.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-02 16:10 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +                if (UtilMethods.isNotSet(fileName) || fileName.startsWith(".") || fileName
Codacy found an issue: [This call to String.startsWith can be rewritten using String.charAt(0)](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-02 16:54 UTC, nollymar approved these changes

2020-07-02 18:08 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +                if (UtilMethods.isNotSet(fileName) || fileName.startsWith(".") || fileName
Codacy found an issue: [This call to String.startsWith can be rewritten using String.charAt(0)](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-02 18:08 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResource.java
> +        final InitDataObject initData = webResource.init(request, response,true);
Codacy found an issue: [Avoid declaring a variable if it is unreferenced before a possible exit point.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5747250)

2020-07-02 19:24 UTC, merged