Issue #18848 adding leading slash uri
dotCMS/core pull request #18850
Opened 2020-07-08 18:24 UTC by luisbacca

This pull request add a leading slash to the uri parameter so the endpoint return the right folder structure.

2020-07-08 18:29 UTC, luisbacca commented
https://github.com/dotCMS/core/issues/18848

2020-07-08 18:30 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/folder/FolderResource.java
> +            if(uriParam.charAt(0) != '/') {
Codacy found an issue: [Avoid using Literals in Conditional Statements](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5823758)

2020-07-08 18:52 UTC, erickgonzalez commented
Is this a dupe of https://github.com/dotCMS/core/pull/18823 ??

2020-07-08 19:15 UTC, luisbacca commented
> Is this a dupe of #18823 ??

Yes, resolved now.

2020-07-08 19:21 UTC, jdotcms approved these changes

2020-07-08 19:42 UTC, erickgonzalez approved these changes

2020-07-09 14:09 UTC, freddyucv requested changes
do it need a postman test?

2020-07-13 14:34 UTC, dsilvam approved these changes

2020-07-14 16:21 UTC, dsilvam commented
Postman test for this will be included on a different branch

2020-07-14 16:22 UTC, merged