Issue 18872 site-search default status fix
dotCMS/core pull request #18876
Opened 2020-07-13 23:31 UTC by fabrizzio-dotCMS

Previously the class `IndexAjaxAction` used to perform the index activation and deactivation through `ESIndexResource` But this last one recently underwent refactoring and such behavior got removed. The activation and deactivation actions are were redirected to a direct call to `ContentletIndexAPIImpl` which didn't have any logic to do so. It was only aware of regular indices. This change adds logic to intercept any call performed on top of a site-search index redirecting it to the proper API. `SiteSearchAPIImpl`

2020-07-13 23:38 UTC, nollymar commented
I think it is ok to merge it on 5.3.4, but some test cases should be added in master branch (ESSiteSearchAPITest.java) to consider these scenarios

2020-07-13 23:38 UTC, nollymar approved these changes

2020-07-14 14:10 UTC, dsilvam approved these changes

2020-07-14 14:11 UTC, freddyucv requested changes
is it possible any test here?

2020-07-14 14:31 UTC, erickgonzalez approved these changes

2020-07-14 14:39 UTC, jdotcms approved these changes

2020-07-14 16:33 UTC, freddyucv approved these changes

2020-07-14 16:45 UTC, merged