#18970 : Adding some validations steps that will indicate a situation…
dotCMS/core pull request #18971
Opened 2020-07-24 16:20 UTC by jcastro-dotcms

… in which Push Publishing wants to access and edit an existing contentlet that is archived. This change adds a useful logging and status message for the PP bundle history.

2020-07-24 16:26 UTC, jdotcms approved these changes

2020-07-24 17:08 UTC, erickgonzalez approved these changes

2020-07-27 14:11 UTC, freddyucv requested changes
any test?

2020-08-24 16:52 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImplTest.java
> +        } catch (Exception e){
Codacy found an issue: [Avoid catching generic exceptions such as NullPointerException, RuntimeException, Exception in try-catch block](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=5907835)

2020-08-24 19:24 UTC, freddyucv approved these changes

2020-08-24 19:49 UTC, merged