#19108 first draft
dotCMS/core pull request #19119
Opened 2020-08-17 23:43 UTC by dsilvam

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/PageModeDataFetcher.java
> +import java.util.Map;
Codacy found an issue: [Avoid unused imports such as 'java.util.Map'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/VisitorDataFetcher.java
> +import java.util.Objects;
Codacy found an issue: [Avoid unused imports such as 'java.util.Objects'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/VisitorDataFetcher.java
> +import com.dotmarketing.business.APILocator;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.business.APILocator'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/VisitorDataFetcher.java
> +            final Contentlet contentlet = environment.getSource();
Codacy found an issue: [Avoid unused local variables such as 'contentlet'.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/VisitorDataFetcher.java
> +import com.dotmarketing.business.PermissionLevel;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.business.PermissionLevel'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/VisitorDataFetcher.java
> +        } catch (Exception e) {
Codacy found an issue: [Avoid catching generic exceptions such as NullPointerException, RuntimeException, Exception in try-catch block](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.fasterxml.jackson.databind.ObjectWriter;
Codacy found an issue: [Avoid unused imports such as 'com.fasterxml.jackson.databind.ObjectWriter'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/VisitorDataFetcher.java
> +import java.io.CharArrayReader;
Codacy found an issue: [Avoid unused imports such as 'java.io.CharArrayReader'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.exception.DotDataException;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.exception.DotDataException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPI;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPI'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/VisitorDataFetcher.java
> +import com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPI;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPI'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/PageModeDataFetcher.java
> +        } catch (Exception e) {
Codacy found an issue: [Avoid catching generic exceptions such as NullPointerException, RuntimeException, Exception in try-catch block](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import java.io.CharArrayReader;
Codacy found an issue: [Avoid unused imports such as 'java.io.CharArrayReader'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/VisitorDataFetcher.java
> +import com.fasterxml.jackson.databind.ObjectWriter;
Codacy found an issue: [Avoid unused imports such as 'com.fasterxml.jackson.databind.ObjectWriter'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.exception.DotRuntimeException;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.exception.DotRuntimeException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import java.io.IOException;
Codacy found an issue: [Avoid unused imports such as 'java.io.IOException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/VisitorDataFetcher.java
> +            final User user = ((DotGraphQLContext) environment.getContext()).getUser();
Codacy found an issue: [Avoid unused local variables such as 'user'.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +        } catch (Exception e) {
Codacy found an issue: [Avoid catching generic exceptions such as NullPointerException, RuntimeException, Exception in try-catch block](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/VisitorDataFetcher.java
> +import java.io.IOException;
Codacy found an issue: [Avoid unused imports such as 'java.io.IOException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/VisitorDataFetcher.java
> +import com.dotmarketing.exception.DotRuntimeException;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.exception.DotRuntimeException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/business/PageAPIGraphQLTypesProvider.java
> +import java.util.function.Function;
Codacy found an issue: [Avoid unused imports such as 'java.util.function.Function'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.business.PermissionLevel;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.business.PermissionLevel'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/VisitorDataFetcher.java
> +import com.dotmarketing.exception.DotDataException;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.exception.DotDataException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/VisitorDataFetcher.java
> +import com.dotmarketing.util.PageMode;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.util.PageMode'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-17 23:51 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/VisitorDataFetcher.java
> +import com.dotmarketing.portlets.htmlpageasset.business.render.page.JsonMapper;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.portlets.htmlpageasset.business.render.page.JsonMapper'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 02:28 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.exception.DotRuntimeException;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.exception.DotRuntimeException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 02:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/PageModeDataFetcher.java
> +        } catch (Exception e) {
Codacy found an issue: [Avoid catching generic exceptions such as NullPointerException, RuntimeException, Exception in try-catch block](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 02:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.business.PermissionLevel;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.business.PermissionLevel'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 02:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +        } catch (Exception e) {
Codacy found an issue: [Avoid catching generic exceptions such as NullPointerException, RuntimeException, Exception in try-catch block](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 02:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.fasterxml.jackson.databind.ObjectWriter;
Codacy found an issue: [Avoid unused imports such as 'com.fasterxml.jackson.databind.ObjectWriter'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 02:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/PageModeDataFetcher.java
> +import com.dotmarketing.portlets.templates.model.Template;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.portlets.templates.model.Template'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 02:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPI;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPI'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 02:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.exception.DotSecurityException;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.exception.DotSecurityException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 02:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/HTMLPageAssetRenderedAPI.java
> +import java.util.Set;
Codacy found an issue: [Avoid unused imports such as 'java.util.Set'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 02:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/PageModeDataFetcher.java
> +import java.util.Map;
Codacy found an issue: [Avoid unused imports such as 'java.util.Map'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 02:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import java.util.Objects;
Codacy found an issue: [Avoid unused imports such as 'java.util.Objects'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 02:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import java.io.IOException;
Codacy found an issue: [Avoid unused imports such as 'java.io.IOException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 02:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.exception.DotDataException;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.exception.DotDataException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 02:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.portlets.htmlpageasset.business.render.page.JsonMapper;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.portlets.htmlpageasset.business.render.page.JsonMapper'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 02:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/PageModeDataFetcher.java
> +import com.dotmarketing.portlets.htmlpageasset.model.HTMLPageAsset;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.portlets.htmlpageasset.model.HTMLPageAsset'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 02:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import java.io.CharArrayReader;
Codacy found an issue: [Avoid unused imports such as 'java.io.CharArrayReader'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 23:41 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/PageModeDataFetcher.java
> +        } catch (Exception e) {
Codacy found an issue: [Avoid catching generic exceptions such as NullPointerException, RuntimeException, Exception in try-catch block](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 23:41 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.exception.DotSecurityException;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.exception.DotSecurityException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 23:41 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import java.util.Objects;
Codacy found an issue: [Avoid unused imports such as 'java.util.Objects'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 23:41 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.portlets.htmlpageasset.business.render.page.JsonMapper;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.portlets.htmlpageasset.business.render.page.JsonMapper'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 23:41 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/business/PageAPIGraphQLTypesProvider.java
> +        viewAsFields.put("persona", new TypeFetcher(GraphQLTypeReference.typeRef("PersonaBaseType"),
Codacy found an issue: [The String literal "persona" appears 5 times in this file; the first occurrence is on line 137](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 23:41 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import java.io.CharArrayReader;
Codacy found an issue: [Avoid unused imports such as 'java.io.CharArrayReader'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 23:41 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/PageModeDataFetcher.java
> +import com.dotmarketing.portlets.templates.model.Template;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.portlets.templates.model.Template'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 23:41 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/HTMLPageAssetRenderedAPI.java
> +import java.util.Set;
Codacy found an issue: [Avoid unused imports such as 'java.util.Set'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 23:41 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPI;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPI'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 23:41 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.exception.DotRuntimeException;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.exception.DotRuntimeException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 23:41 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/PageModeDataFetcher.java
> +import com.dotmarketing.portlets.htmlpageasset.model.HTMLPageAsset;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.portlets.htmlpageasset.model.HTMLPageAsset'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 23:41 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.exception.DotDataException;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.exception.DotDataException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 23:41 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.fasterxml.jackson.databind.ObjectWriter;
Codacy found an issue: [Avoid unused imports such as 'com.fasterxml.jackson.databind.ObjectWriter'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 23:41 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.business.PermissionLevel;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.business.PermissionLevel'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 23:41 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/business/PageAPIGraphQLTypesProvider.java
> +import com.dotcms.graphql.datafetcher.KeyValueFieldDataFetcher;
Codacy found an issue: [Avoid unused imports such as 'com.dotcms.graphql.datafetcher.KeyValueFieldDataFetcher'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 23:41 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import java.io.IOException;
Codacy found an issue: [Avoid unused imports such as 'java.io.IOException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 23:41 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/PageModeDataFetcher.java
> +import java.util.Map;
Codacy found an issue: [Avoid unused imports such as 'java.util.Map'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-19 23:41 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +        } catch (Exception e) {
Codacy found an issue: [Avoid catching generic exceptions such as NullPointerException, RuntimeException, Exception in try-catch block](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:46 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.exception.DotRuntimeException;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.exception.DotRuntimeException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:46 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/PageModeDataFetcher.java
> +import com.dotmarketing.portlets.htmlpageasset.model.HTMLPageAsset;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.portlets.htmlpageasset.model.HTMLPageAsset'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:46 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.business.PermissionLevel;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.business.PermissionLevel'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:46 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import java.io.IOException;
Codacy found an issue: [Avoid unused imports such as 'java.io.IOException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:46 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.exception.DotDataException;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.exception.DotDataException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:46 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/HTMLPageAssetRenderedAPI.java
> +import java.util.Set;
Codacy found an issue: [Avoid unused imports such as 'java.util.Set'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:46 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import java.io.CharArrayReader;
Codacy found an issue: [Avoid unused imports such as 'java.io.CharArrayReader'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:46 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/business/PageAPIGraphQLTypesProvider.java
> +import com.dotcms.graphql.datafetcher.KeyValueFieldDataFetcher;
Codacy found an issue: [Avoid unused imports such as 'com.dotcms.graphql.datafetcher.KeyValueFieldDataFetcher'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:46 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.exception.DotSecurityException;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.exception.DotSecurityException'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:46 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +        } catch (Exception e) {
Codacy found an issue: [Avoid catching generic exceptions such as NullPointerException, RuntimeException, Exception in try-catch block](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:46 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/PageModeDataFetcher.java
> +import com.dotmarketing.portlets.templates.model.Template;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.portlets.templates.model.Template'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:46 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/PageModeDataFetcher.java
> +        } catch (Exception e) {
Codacy found an issue: [Avoid catching generic exceptions such as NullPointerException, RuntimeException, Exception in try-catch block](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:46 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/business/PageAPIGraphQLTypesProvider.java
> +        viewAsFields.put("persona", new TypeFetcher(GraphQLTypeReference.typeRef("PersonaBaseType"),
Codacy found an issue: [The String literal "persona" appears 5 times in this file; the first occurrence is on line 137](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:46 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPI;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPI'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:47 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.fasterxml.jackson.databind.ObjectWriter;
Codacy found an issue: [Avoid unused imports such as 'com.fasterxml.jackson.databind.ObjectWriter'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:47 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import java.util.Objects;
Codacy found an issue: [Avoid unused imports such as 'java.util.Objects'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:47 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +import com.dotmarketing.portlets.htmlpageasset.business.render.page.JsonMapper;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.portlets.htmlpageasset.business.render.page.JsonMapper'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:47 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/visitor/domain/Visitor.java
> +        return GeoIp2CityDbUtil.getInstance().getGeolocation("189.209.114.118");
Codacy found an issue: [Do not hard code the IP address ](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:47 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/PageModeDataFetcher.java
> +import java.util.Map;
Codacy found an issue: [Avoid unused imports such as 'java.util.Map'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/visitor/domain/Visitor.java
> +        return GeoIp2CityDbUtil.getInstance().getGeolocation("189.209.114.118");
Codacy found an issue: [Do not hard code the IP address ](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +        } catch (Exception e) {
Codacy found an issue: [Avoid catching generic exceptions such as NullPointerException, RuntimeException, Exception in try-catch block](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 17:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/business/PageAPIGraphQLTypesProvider.java
> +        viewAsFields.put("persona", new TypeFetcher(GraphQLTypeReference.typeRef("PersonaBaseType"),
Codacy found an issue: [The String literal "persona" appears 5 times in this file; the first occurrence is on line 137](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 19:12 UTC, freddyucv requested changes

2020-08-20 19:12 UTC, freddyucv commented on dotCMS/src/main/java/com/dotcms/device/DeviceAPIImpl.java
> +public class DeviceAPIImpl implements DeviceAPI {
javadoc?

2020-08-20 19:12 UTC, freddyucv commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/HTMLPageAssetRenderedAPIImpl.java
> +    public ViewAsPageStatus getViewAsStatus(final HttpServletRequest request,
any test?

2020-08-20 19:44 UTC, dsilvam commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/HTMLPageAssetRenderedAPIImpl.java
> +    public ViewAsPageStatus getViewAsStatus(final HttpServletRequest request,
Postman test

2020-08-20 19:45 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/device/DeviceAPIImpl.java
> +    public Contentlet getCurrentDevice(final HttpServletRequest request, final User user)
Postman test

2020-08-20 19:48 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/device/DeviceAPIImpl.java
> +public class DeviceAPIImpl implements DeviceAPI {
done

2020-08-20 19:51 UTC, freddyucv approved these changes

2020-08-20 19:55 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/business/PageAPIGraphQLTypesProvider.java
> +        viewAsFields.put("persona", new TypeFetcher(GraphQLTypeReference.typeRef("PersonaBaseType"),
Codacy found an issue: [The String literal "persona" appears 5 times in this file; the first occurrence is on line 137](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 19:55 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/visitor/domain/Visitor.java
> +        return GeoIp2CityDbUtil.getInstance().getGeolocation("189.209.114.118");
Codacy found an issue: [Do not hard code the IP address ](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 19:55 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +        } catch (Exception e) {
Codacy found an issue: [Avoid catching generic exceptions such as NullPointerException, RuntimeException, Exception in try-catch block](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 20:04 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/business/PageAPIGraphQLTypesProvider.java
> +        viewAsFields.put("persona", new TypeFetcher(GraphQLTypeReference.typeRef("PersonaBaseType"),
Codacy found an issue: [The String literal "persona" appears 5 times in this file; the first occurrence is on line 137](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-20 20:04 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +        } catch (Exception e) {
Codacy found an issue: [Avoid catching generic exceptions such as NullPointerException, RuntimeException, Exception in try-catch block](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-24 15:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +        } catch (Exception e) {
Codacy found an issue: [Avoid catching generic exceptions such as NullPointerException, RuntimeException, Exception in try-catch block](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-24 15:29 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/business/PageAPIGraphQLTypesProvider.java
> +        viewAsFields.put("persona", new TypeFetcher(GraphQLTypeReference.typeRef("PersonaBaseType"),
Codacy found an issue: [The String literal "persona" appears 5 times in this file; the first occurrence is on line 137](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-24 16:34 UTC, victoralfaro-dotcms commented on dotCMS/src/main/java/com/dotcms/device/DeviceAPIImpl.java
> +        return currentDevice;
Is it OK to return null?

2020-08-24 17:05 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/device/DeviceAPIImpl.java
> +        return currentDevice;
Switched to Optional

2020-08-24 17:09 UTC, victoralfaro-dotcms approved these changes
LGTM

2020-08-24 17:12 UTC, merged

2020-08-24 17:15 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/business/PageAPIGraphQLTypesProvider.java
> +        viewAsFields.put("persona", new TypeFetcher(GraphQLTypeReference.typeRef("PersonaBaseType"),
Codacy found an issue: [The String literal "persona" appears 5 times in this file; the first occurrence is on line 137](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)

2020-08-24 17:15 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/datafetcher/page/ViewAsDataFetcher.java
> +        } catch (Exception e) {
Codacy found an issue: [Avoid catching generic exceptions such as NullPointerException, RuntimeException, Exception in try-catch block](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6028986)