#19147 : The evaluation order in Vanity URLs is still being used by s…
dotCMS/core pull request #19150
Opened 2020-08-24 21:28 UTC by jcastro-dotcms

…everal customers. The new version of the Vanity URL API was not setting the expected value for that. The API is now returning the Vanities in ascending order so that users can specify the appropriate way in which Vanities should match an incoming URL.

2020-08-24 21:47 UTC, jdotcms approved these changes

2020-08-25 02:23 UTC, wezell requested changes
Looks great, one minor thing.

2020-08-25 02:23 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/vanityurl/business/VanityUrlAPIImpl.java
> +          String.format("An error occurred when retrieving Vanity URLs: siteId=[%s], languageId=[%s]",
We should always append `e.getMessage()` to our message so the real root cause does not get eaten higher up.

2020-08-25 07:22 UTC, Xander-Steinmann commented
Does this code change mean that before the fix the ordering never worked?

2020-08-25 12:45 UTC, wezell commented
Apparently, ordering worked until the Vanity URL re-write that happened in 5.3.1, which was done to fix other problems with the vanities.

2020-08-25 13:26 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotcms/vanityurl/business/VanityUrlAPITest.java
> +        assert(cachedVanities.get(0).order < cachedVanities.get(numberOfTestVanities-1).order);
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6064444)

2020-08-25 13:26 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotcms/vanityurl/business/VanityUrlAPITest.java
> +    public void testing_vanityurl_ordering() throws Exception {
Codacy found an issue: [JUnit tests should include assert() or fail()](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6064444)

2020-08-25 13:26 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotcms/vanityurl/business/VanityUrlAPITest.java
> +        assert(cachedVanities.size() == numberOfTestVanities);
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6064444)

2020-08-25 13:26 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotcms/vanityurl/business/VanityUrlAPITest.java
> +            assert(cached.order >= previousCachedVanity.order);
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6064444)

2020-08-25 15:22 UTC, freddyucv approved these changes

2020-09-01 20:34 UTC, nollymar approved these changes

2020-09-01 20:43 UTC, merged