#19155 adding a fix for limited user creating content multi line
dotCMS/core pull request #19178
Opened 2020-08-27 07:34 UTC by jdotcms

When a Limited user tries to create a contentlet on diff lang, an error has been throwed.

2020-08-28 14:25 UTC, dsilvam approved these changes

2020-08-28 14:27 UTC, freddyucv requested changes

2020-08-28 14:27 UTC, freddyucv commented on dotCMS/src/main/java/com/dotmarketing/business/PermissionBitAPIImpl.java
> +                && Try.of(()->((Contentlet) permissionable).isLive()).getOrElse(false);
any test?

2020-08-28 14:27 UTC, freddyucv commented on dotCMS/src/main/webapp/html/portlet/ext/contentlet/edit_contentlet.jsp
>              && conPerAPI.doesUserHavePermissions(contentlet.getParentPermissionable(), "PERMISSIONS: " + PermissionAPI.PERMISSION_USE, user);
any test?

2020-08-28 17:54 UTC, erickgonzalez approved these changes

2020-09-02 14:17 UTC, erickgonzalez approved these changes

2020-09-02 16:30 UTC, erickgonzalez approved these changes

2020-09-02 18:56 UTC, merged