#19255 cache region for graphql schema
dotCMS/core pull request #19256
Opened 2020-09-10 23:10 UTC by dsilvam

2020-09-10 23:17 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/business/GraphQLSchemaCache.java
> +        return GROUPS;
Codacy found an issue: [Returning 'GROUPS' may expose an internal array.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6160696)

2020-09-10 23:30 UTC, victoralfaro-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/business/GraphQLSchemaCache.java
> +            return Optional.ofNullable((GraphQLSchema) cache.get(SCHEMA_KEY, GRAPHQL_SCHEMA_GROUP));
Does `cache.get()` throw a `DotCacheException`?

2020-09-11 13:57 UTC, freddyucv requested changes

2020-09-11 13:57 UTC, freddyucv commented on dotCMS/src/main/java/com/dotcms/graphql/business/GraphQLSchemaCache.java
> +public class GraphQLSchemaCache implements Cachable {
doc

2020-09-11 13:57 UTC, freddyucv commented on dotCMS/src/main/java/com/dotcms/graphql/DotGraphQLSchemaProvider.java
> +            APILocator.getGraphqlAPI().printSchema();
I think we are missing a test here

2020-09-11 17:11 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/graphql/business/GraphQLSchemaCache.java
> +public class GraphQLSchemaCache implements Cachable {
done

2020-09-11 17:17 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/graphql/business/GraphQLSchemaCache.java
> +        return GROUPS;
Codacy found an issue: [Returning 'GROUPS' may expose an internal array.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6160696)

2020-09-11 17:39 UTC, victoralfaro-dotcms approved these changes
LGTM

2020-09-11 18:19 UTC, freddyucv approved these changes

2020-09-11 19:00 UTC, merged