#18990 now the key value on the url map as a map instead of single st…
dotCMS/core pull request #19278
Opened 2020-09-17 17:48 UTC by jdotcms

Now on the page render api; the key value on the url map is being rendered as a map (json map) instead of a string

2020-09-17 17:54 UTC, dsilvam approved these changes

2020-09-17 17:55 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializerTest.java
> +import static org.mockito.Matchers.anyString;
Codacy found an issue: [Avoid unused imports such as 'org.mockito.Matchers.anyString'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-17 17:55 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializerTest.java
> +    public void createObjectMapUrlContent_convert_url_map_no_keyvalue() throws Exception {
Codacy found an issue: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-17 17:55 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializerTest.java
> +import com.dotmarketing.portlets.workflows.model.WorkflowScheme;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.portlets.workflows.model.WorkflowScheme'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-17 17:55 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializerTest.java
> +        urlContent.getMap().put("keyValue", keyValue);
Codacy found an issue: [The String literal "keyValue" appears 6 times in this file; the first occurrence is on line 51](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-17 17:55 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializerTest.java
> +import com.dotmarketing.business.APILocator;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.business.APILocator'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-17 17:55 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializerTest.java
> +import com.dotmarketing.business.PermissionAPI;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.business.PermissionAPI'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-17 17:55 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializerTest.java
> +    public static void prepare () throws Exception {
Codacy found an issue: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-17 17:55 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializerTest.java
> +    public void createObjectMapUrlContent_convert_url_map_keyvalue() throws Exception {
Codacy found an issue: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-17 18:19 UTC, wezell requested changes

2020-09-17 18:19 UTC, wezell commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializer.java
> +    protected Map<String, Object> createObjectMapKeyValue(final Contentlet contentlet, final ContentType contentType, final Map<String, Object> contentletMap) {
I think this code should be part of a more generic Serializer - `DotContentletTransformer`- any content can have a key/value field, not just Pages

2020-09-22 06:30 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializer.java
> +import com.dotmarketing.util.UtilMethods;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.util.UtilMethods'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 06:30 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializerTest.java
> +    public static void prepare () throws Exception {
Codacy found an issue: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 06:30 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializer.java
> +import java.util.List;
Codacy found an issue: [Avoid unused imports such as 'java.util.List'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 06:30 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializerTest.java
> +    public void createObjectMapUrlContent_convert_url_map_keyvalue() throws Exception {
Codacy found an issue: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 06:30 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializer.java
> +import com.dotcms.contenttype.model.field.Field;
Codacy found an issue: [Avoid unused imports such as 'com.dotcms.contenttype.model.field.Field'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 06:30 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializer.java
> +import com.dotcms.contenttype.model.field.KeyValueField;
Codacy found an issue: [Avoid unused imports such as 'com.dotcms.contenttype.model.field.KeyValueField'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 06:30 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializer.java
> +import static java.util.Collections.emptyMap;
Codacy found an issue: [Avoid unused imports such as 'java.util.Collections.emptyMap'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 06:30 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializerTest.java
> +        baseContent.getMap().put("keyValue", keyValue);
Codacy found an issue: [The String literal "keyValue" appears 10 times in this file; the first occurrence is on line 47](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 06:30 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializerTest.java
> +    public void createObjectMapUrlContent_convert_url_map_no_keyvalue() throws Exception {
Codacy found an issue: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 14:59 UTC, erickgonzalez approved these changes

2020-09-22 17:17 UTC, fabrizzio-dotCMS requested changes

2020-09-22 17:17 UTC, fabrizzio-dotCMS commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializer.java
> +    }
I don't think the strategy should be applied directly it must be applied from within the transformer. 

Let's say you do
`new DotTransformerBuilder().defaultOptions() `
the code that instructs the transformer to apply this strategy must be part of the options provided to the transformer. You should never apply a strategy outside of the transformer

2020-09-22 20:54 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializerTest.java
> +        assertTrue(pageViewMap.containsKey("urlContentMap"));
Codacy found an issue: [The String literal "urlContentMap" appears 6 times in this file; the first occurrence is on line 61](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 20:54 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializer.java
> +import com.dotmarketing.portlets.contentlet.transform.strategy.KeyValueViewStrategy;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.portlets.contentlet.transform.strategy.KeyValueViewStrategy'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 20:54 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializer.java
> +import com.dotcms.contenttype.model.type.ContentType;
Codacy found an issue: [Avoid unused imports such as 'com.dotcms.contenttype.model.type.ContentType'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 20:54 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializerTest.java
> +        baseContent.getMap().put("keyValue", keyValue);
Codacy found an issue: [The String literal "keyValue" appears 10 times in this file; the first occurrence is on line 47](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 20:54 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializer.java
> +import com.dotmarketing.util.UtilMethods;
Codacy found an issue: [Avoid unused imports such as 'com.dotmarketing.util.UtilMethods'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 20:54 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializerTest.java
> +    public void createObjectMapUrlContent_convert_url_map_no_keyvalue() throws Exception {
Codacy found an issue: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 20:54 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializerTest.java
> +        assertTrue((Map.class.cast(pageViewMap.get("urlContentMap")).containsKey("keyValue")));
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 20:54 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializerTest.java
> +    public static void prepare () throws Exception {
Codacy found an issue: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 20:54 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializerTest.java
> +import com.dotcms.contenttype.model.field.TextField;
Codacy found an issue: [Avoid unused imports such as 'com.dotcms.contenttype.model.field.TextField'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 20:54 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializer.java
> +import java.util.List;
Codacy found an issue: [Avoid unused imports such as 'java.util.List'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 20:54 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializer.java
> +import com.dotcms.contenttype.model.field.KeyValueField;
Codacy found an issue: [Avoid unused imports such as 'com.dotcms.contenttype.model.field.KeyValueField'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 20:54 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializer.java
> +import com.dotcms.contenttype.model.field.Field;
Codacy found an issue: [Avoid unused imports such as 'com.dotcms.contenttype.model.field.Field'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 20:54 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializerTest.java
> +    public void createObjectMapUrlContent_convert_url_map_keyvalue() throws Exception {
Codacy found an issue: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 20:54 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializer.java
> +import static java.util.Collections.emptyMap;
Codacy found an issue: [Avoid unused imports such as 'java.util.Collections.emptyMap'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 20:54 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/htmlpageasset/business/render/page/PageViewSerializerTest.java
> +import com.dotcms.contenttype.model.field.Field;
Codacy found an issue: [Avoid unused imports such as 'com.dotcms.contenttype.model.field.Field'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6197346)

2020-09-22 22:53 UTC, merged