Issue 18314 lucene search
dotCMS/core pull request #19327
Opened 2020-09-24 19:59 UTC by jdotcms

Adding an endpoint to allow the lucene query tool use Ajax to retrieve the information

2020-09-24 20:06 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    limit  = 0;
Codacy found an issue: [Field limit has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-24 20:06 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String query  = "";
Codacy found an issue: [Field query has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-24 20:06 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String userId;
Codacy found an issue: [Field userId has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-24 20:06 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    offset = 20;
Codacy found an issue: [Field offset has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-24 20:06 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    limit  = 0;
Codacy found an issue: [Avoid using redundant field initializer for 'limit'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-24 20:06 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String sort   = "";
Codacy found an issue: [Field sort has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-24 20:14 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String query  = "";
Codacy found an issue: [Field query has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-24 20:14 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String sort   = "";
Codacy found an issue: [Field sort has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-24 20:14 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    offset = 20;
Codacy found an issue: [Field offset has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-24 20:14 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String userId;
Codacy found an issue: [Field userId has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-24 20:14 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    limit  = 0;
Codacy found an issue: [Field limit has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-24 20:14 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    limit  = 0;
Codacy found an issue: [Avoid using redundant field initializer for 'limit'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-24 20:48 UTC, wezell requested changes

2020-09-24 20:48 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/rest/ContentResource.java
> +            contentletSearches = APILocator.getContentletAPI().searchIndex(query, limit, offset, sort, userForPull, pageMode.respectAnonPerms);
I would use the `ContentletAPI.indexCount` here, rather than return results and count them

2020-09-24 20:48 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/rest/ContentResource.java
> +            contentlets        = ContentUtils.pull(processQuery(query), offset, limit, sort, user, tmDate, pageMode.respectAnonPerms)
This needs to be run through the getJSON method so the results will match the existing api
```
                result = getJSON(contentlets, request, response, render, user, depth,
                        respectFrontendRoles, language, live, allCategoriesInfo);
```

2020-09-24 20:49 UTC, wezell requested changes

2020-09-24 20:49 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/rest/ContentResource.java
> +        final PageMode pageMode   = PageMode.get(request);
Missing the `render` param too

2020-09-25 00:12 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    limit  = 0;
Codacy found an issue: [Avoid using redundant field initializer for 'limit'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-25 00:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String query  = "";
Codacy found an issue: [Field query has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-25 00:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    limit  = 0;
Codacy found an issue: [Field limit has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-25 00:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    offset = 20;
Codacy found an issue: [Field offset has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-25 00:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String userId;
Codacy found an issue: [Field userId has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-25 00:13 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String sort   = "";
Codacy found an issue: [Field sort has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-27 21:48 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String query  = "";
Codacy found an issue: [Field query has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-27 21:48 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String userId;
Codacy found an issue: [Field userId has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-27 21:48 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty long languageId = -1;
Codacy found an issue: [Field languageId has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-27 21:48 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String sort   = "";
Codacy found an issue: [Field sort has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-27 21:48 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    offset = 20;
Codacy found an issue: [Field offset has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-27 21:48 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int depth       = -1;
Codacy found an issue: [Field depth has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-27 21:48 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    limit  = 0;
Codacy found an issue: [Avoid using redundant field initializer for 'limit'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-27 21:49 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String render;
Codacy found an issue: [Field render has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-27 21:49 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    limit  = 0;
Codacy found an issue: [Field limit has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-27 21:49 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty boolean allCategoriesInfo;
Codacy found an issue: [Field allCategoriesInfo has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 15:52 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String sort   = "";
Codacy found an issue: [Field sort has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 15:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty boolean allCategoriesInfo;
Codacy found an issue: [Field allCategoriesInfo has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 15:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty long languageId = -1;
Codacy found an issue: [Field languageId has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 15:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String userId;
Codacy found an issue: [Field userId has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 15:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String render;
Codacy found an issue: [Field render has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 15:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int depth       = -1;
Codacy found an issue: [Field depth has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 15:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    limit  = 0;
Codacy found an issue: [Field limit has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 15:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    limit  = 0;
Codacy found an issue: [Avoid using redundant field initializer for 'limit'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 15:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String query  = "";
Codacy found an issue: [Field query has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 15:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    offset = 20;
Codacy found an issue: [Field offset has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 22:46 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String render;
Codacy found an issue: [Field render has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 22:46 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String query  = "";
Codacy found an issue: [Field query has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 22:47 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    limit  = 0;
Codacy found an issue: [Field limit has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 22:47 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int depth       = -1;
Codacy found an issue: [Field depth has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 22:47 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String userId;
Codacy found an issue: [Field userId has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 22:47 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty boolean allCategoriesInfo;
Codacy found an issue: [Field allCategoriesInfo has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 22:47 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    limit  = 0;
Codacy found an issue: [Avoid using redundant field initializer for 'limit'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 22:47 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    offset = 20;
Codacy found an issue: [Field offset has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 22:47 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty long languageId = -1;
Codacy found an issue: [Field languageId has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 22:47 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String sort   = "";
Codacy found an issue: [Field sort has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 22:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty long languageId = -1;
Codacy found an issue: [Field languageId has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 22:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int depth       = -1;
Codacy found an issue: [Field depth has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 22:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String query  = "";
Codacy found an issue: [Field query has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 22:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String userId;
Codacy found an issue: [Field userId has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 22:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String render;
Codacy found an issue: [Field render has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 22:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    offset = 20;
Codacy found an issue: [Field offset has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 22:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    limit  = 0;
Codacy found an issue: [Field limit has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 22:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty boolean allCategoriesInfo;
Codacy found an issue: [Field allCategoriesInfo has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 22:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    limit  = 0;
Codacy found an issue: [Avoid using redundant field initializer for 'limit'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-09-28 22:53 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String sort   = "";
Codacy found an issue: [Field sort has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-10-06 18:09 UTC, nollymar approved these changes

2020-10-06 18:17 UTC, erickgonzalez approved these changes

2020-10-08 16:44 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    limit  = 0;
Codacy found an issue: [Avoid using redundant field initializer for 'limit'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-10-08 16:44 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String sort   = "";
Codacy found an issue: [Field sort has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-10-08 16:44 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty long languageId = -1;
Codacy found an issue: [Field languageId has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-10-08 16:44 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int depth       = -1;
Codacy found an issue: [Field depth has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-10-08 16:44 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty boolean allCategoriesInfo;
Codacy found an issue: [Field allCategoriesInfo has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-10-08 16:44 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String userId;
Codacy found an issue: [Field userId has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-10-08 16:44 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String query  = "";
Codacy found an issue: [Field query has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-10-08 16:44 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    limit  = 0;
Codacy found an issue: [Field limit has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-10-08 16:44 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    offset = 20;
Codacy found an issue: [Field offset has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-10-08 16:44 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String render;
Codacy found an issue: [Field render has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-10-08 18:27 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String userId;
Codacy found an issue: [Field userId has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-10-08 18:27 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    limit  = 0;
Codacy found an issue: [Avoid using redundant field initializer for 'limit'](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-10-08 18:27 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    offset = 20;
Codacy found an issue: [Field offset has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-10-08 18:27 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String query  = "";
Codacy found an issue: [Field query has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-10-08 18:27 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty long languageId = -1;
Codacy found an issue: [Field languageId has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-10-08 18:27 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String render;
Codacy found an issue: [Field render has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-10-08 18:27 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int    limit  = 0;
Codacy found an issue: [Field limit has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-10-08 18:27 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty String sort   = "";
Codacy found an issue: [Field sort has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-10-08 18:27 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty boolean allCategoriesInfo;
Codacy found an issue: [Field allCategoriesInfo has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-10-08 18:27 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/SearchForm.java
> +        private  @JsonProperty int depth       = -1;
Codacy found an issue: [Field depth has the same name as a method](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6233451)

2020-10-09 15:37 UTC, merged