Fixing postman test
dotCMS/core pull request #19418
Opened 2020-10-08 17:54 UTC by freddyucv

2020-10-08 19:21 UTC, dsilvam approved these changes

2020-10-09 15:33 UTC, erickgonzalez commented
@freddyucv there are still some tests failing https://raw.githack.com/dotCMS/test-results/fixing_postman_test/projects/core/current/curl/postgres/reports/html/index.html

2020-10-09 15:33 UTC, erickgonzalez requested changes
tests still failing https://raw.githack.com/dotCMS/test-results/fixing_postman_test/projects/core/current/curl/postgres/reports/html/index.html

2020-10-20 14:38 UTC, victoralfaro-dotcms approved these changes
LGTM

2020-10-20 14:39 UTC, merged