Issues 19395 19396 19397
dotCMS/core pull request #19441
Opened 2020-10-13 04:49 UTC by nollymar

New fields are included into the `identifier` table. These are: `owner`, `create_date` and `asset_subtype`

2020-10-13 14:35 UTC, freddyucv requested changes
any test?

2020-10-13 18:59 UTC, wezell requested changes
Also, we need the startup task that populates the new fields.

2020-10-13 18:59 UTC, wezell commented on dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task201013AddNewColumnsToIdentifierTable.java
> +                "alter table identifier add asset_subtype varchar(255);";
asset_subtype needs an index on it

2020-10-13 18:59 UTC, wezell commented on dotCMS/src/main/resources/mssql.sql
> +   asset_subtype NVARCHAR(255),
add index to `identifier.asset_subtype`

2020-10-13 23:13 UTC, nollymar commented on dotCMS/src/main/java/com/dotmarketing/beans/transform/IdentifierTransformer.java
> +        i.setAssetSubType((String) map.get("asset_subtype"));
Done

2020-10-13 23:13 UTC, nollymar commented
> any test?

Done

2020-10-15 22:38 UTC, nollymar commented on dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task201013AddNewColumnsToIdentifierTable.java
> +                "alter table identifier add asset_subtype varchar(255);";
Done

2020-10-15 22:39 UTC, nollymar commented on dotCMS/src/main/resources/mssql.sql
> +   asset_subtype NVARCHAR(255),
Done

2020-10-15 22:41 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task201013AddNewColumnsToIdentifierTable.java
> +                "create index idx_identifier_asset_subtype on identifier (asset_subtype);";
Codacy found an issue: [The String literal "create index idx_identifier_asset_subtype on identifier (asset_subtype);" appears 4 times in this file; the first occurrence is on line 29](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-15 22:41 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task201013AddNewColumnsToIdentifierTableTest.java
> +    public static void prepare() throws Exception {
Codacy found an issue: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-15 22:41 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task201014UpdateColumnsValuesInIdentifierTableTest.java
> +                ((!expectedResult.getAssetType().equals("contentlet") && !UtilMethods.isSet(result.get("asset_subtype")))
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-15 22:41 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task201014UpdateColumnsValuesInIdentifierTable.java
> +    private static final String UPDATE_FOLDER = "update identifier set owner=q.i_owner, create_date=q.create_date from "
Codacy found an issue: [The String literal "update identifier set owner=q.i_owner, create_date=q.create_date from " appears 4 times in this file; the first occurrence is on line 21](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-15 22:41 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task201014UpdateColumnsValuesInIdentifierTableTest.java
> +                        || (expectedResult.getAssetType().equals("contentlet") && result.get("asset_subtype").equals(expectedResult.getAssetSubType())));
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-15 22:41 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/business/IdentifierFactoryImpl.java
> +            identifier.setOwner((versionable instanceof WebAsset)
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-15 22:41 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task201014UpdateColumnsValuesInIdentifierTableTest.java
> +    public static void prepare() throws Exception {
Codacy found an issue: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-16 17:33 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task201014UpdateColumnsValuesInIdentifierTableTest.java
> +                ((!expectedResult.getAssetType().equals("contentlet") && !UtilMethods.isSet(result.get("asset_subtype")))
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-16 17:33 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task201014UpdateColumnsValuesInIdentifierTable.java
> +    private static final String UPDATE_FOLDER = "update identifier set owner=q.i_owner, create_date=q.create_date from "
Codacy found an issue: [The String literal "update identifier set owner=q.i_owner, create_date=q.create_date from " appears 4 times in this file; the first occurrence is on line 21](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-16 17:33 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task201014UpdateColumnsValuesInIdentifierTableTest.java
> +    public static void prepare() throws Exception {
Codacy found an issue: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-16 17:33 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task201013AddNewColumnsToIdentifierTableTest.java
> +    public static void prepare() throws Exception {
Codacy found an issue: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-16 17:33 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task201013AddNewColumnsToIdentifierTable.java
> +                "create index idx_identifier_asset_subtype on identifier (asset_subtype);";
Codacy found an issue: [The String literal "create index idx_identifier_asset_subtype on identifier (asset_subtype);" appears 4 times in this file; the first occurrence is on line 29](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-16 17:33 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task201014UpdateColumnsValuesInIdentifierTableTest.java
> +                        || (expectedResult.getAssetType().equals("contentlet") && result.get("asset_subtype").equals(expectedResult.getAssetSubType())));
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-16 17:33 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/business/IdentifierFactoryImpl.java
> +            identifier.setOwner((versionable instanceof WebAsset)
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-16 17:40 UTC, freddyucv approved these changes

2020-10-16 20:28 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task201013AddNewColumnsToIdentifierTable.java
> +                "create index idx_identifier_asset_subtype on identifier (asset_subtype);";
Codacy found an issue: [The String literal "create index idx_identifier_asset_subtype on identifier (asset_subtype);" appears 4 times in this file; the first occurrence is on line 29](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-16 20:28 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task201014UpdateColumnsValuesInIdentifierTableTest.java
> +                        || (expectedResult.getAssetType().equals("contentlet") && result.get("asset_subtype").equals(expectedResult.getAssetSubType())));
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-16 20:28 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/business/IdentifierFactoryImpl.java
> +            identifier.setOwner((versionable instanceof WebAsset)
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-16 20:28 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task201014UpdateColumnsValuesInIdentifierTable.java
> +    private static final String UPDATE_FOLDER = "update identifier set owner=q.i_owner, create_date=q.create_date from "
Codacy found an issue: [The String literal "update identifier set owner=q.i_owner, create_date=q.create_date from " appears 4 times in this file; the first occurrence is on line 21](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-16 20:28 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task201014UpdateColumnsValuesInIdentifierTableTest.java
> +    public static void prepare() throws Exception {
Codacy found an issue: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-16 20:28 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task201013AddNewColumnsToIdentifierTableTest.java
> +    public static void prepare() throws Exception {
Codacy found an issue: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-16 20:28 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task201014UpdateColumnsValuesInIdentifierTableTest.java
> +                ((!expectedResult.getAssetType().equals("contentlet") && !UtilMethods.isSet(result.get("asset_subtype")))
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-16 21:49 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task201014UpdateColumnsValuesInIdentifierTableTest.java
> +                        || (expectedResult.getAssetType().equals("contentlet") && result.get("asset_subtype").equals(expectedResult.getAssetSubType())));
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-16 21:49 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task201014UpdateColumnsValuesInIdentifierTableTest.java
> +                ((!expectedResult.getAssetType().equals("contentlet") && !UtilMethods.isSet(result.get("asset_subtype")))
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-16 21:49 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/business/IdentifierFactoryImpl.java
> +            identifier.setOwner((versionable instanceof WebAsset)
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-16 21:49 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task201013AddNewColumnsToIdentifierTable.java
> +                "create index idx_identifier_asset_subtype on identifier (asset_subtype);";
Codacy found an issue: [The String literal "create index idx_identifier_asset_subtype on identifier (asset_subtype);" appears 4 times in this file; the first occurrence is on line 29](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-16 21:49 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task201013AddNewColumnsToIdentifierTableTest.java
> +    public static void prepare() throws Exception {
Codacy found an issue: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-16 21:49 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task201014UpdateColumnsValuesInIdentifierTable.java
> +    private static final String UPDATE_FOLDER = "update identifier set owner=q.i_owner, create_date=q.create_date from "
Codacy found an issue: [The String literal "update identifier set owner=q.i_owner, create_date=q.create_date from " appears 4 times in this file; the first occurrence is on line 21](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-16 21:49 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task201014UpdateColumnsValuesInIdentifierTableTest.java
> +    public static void prepare() throws Exception {
Codacy found an issue: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-19 17:05 UTC, erickgonzalez approved these changes

2020-10-19 17:10 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/business/IdentifierFactoryImpl.java
> +        final Inode inode;
this looks like a candidate to create a private method

2020-10-19 17:11 UTC, jdotcms approved these changes

2020-10-19 18:21 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task201013AddNewColumnsToIdentifierTableTest.java
> +    public static void prepare() throws Exception {
Codacy found an issue: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-19 18:21 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task201014UpdateColumnsValuesInIdentifierTableTest.java
> +                        || (expectedResult.getAssetType().equals("contentlet") && result.get("asset_subtype").equals(expectedResult.getAssetSubType())));
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-19 18:21 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task201014UpdateColumnsValuesInIdentifierTableTest.java
> +    public static void prepare() throws Exception {
Codacy found an issue: [A method/constructor should not explicitly throw java.lang.Exception](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-19 18:21 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task201014UpdateColumnsValuesInIdentifierTable.java
> +    private static final String UPDATE_FOLDER = "update identifier set owner=q.i_owner, create_date=q.create_date from "
Codacy found an issue: [The String literal "update identifier set owner=q.i_owner, create_date=q.create_date from " appears 4 times in this file; the first occurrence is on line 21](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-19 18:21 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task201013AddNewColumnsToIdentifierTable.java
> +                "create index idx_identifier_asset_subtype on identifier (asset_subtype);";
Codacy found an issue: [The String literal "create index idx_identifier_asset_subtype on identifier (asset_subtype);" appears 4 times in this file; the first occurrence is on line 29](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-19 18:21 UTC, dev-dotcms commented on dotCMS/src/integration-test/java/com/dotmarketing/startup/runonce/Task201014UpdateColumnsValuesInIdentifierTableTest.java
> +                ((!expectedResult.getAssetType().equals("contentlet") && !UtilMethods.isSet(result.get("asset_subtype")))
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-19 18:21 UTC, dev-dotcms commented on dotCMS/src/main/java/com/dotmarketing/business/IdentifierFactoryImpl.java
> +            identifier.setOwner((versionable instanceof WebAsset)
Codacy found an issue: [Useless parentheses.](https://app.codacy.com/manual/dotCMS/core/pullRequest?prid=6327767)

2020-10-19 20:56 UTC, merged