Issue 19486 failed login timeout
dotCMS/core pull request #19487
Opened 2020-10-22 01:06 UTC by wezell

2020-11-02 15:30 UTC, fabrizzio-dotCMS requested changes
These properties will prevent those jobs from starting on a fresh install. But if we set those props to disable the jobs and we re-start an instance that previously had those jobs scheduled for regular execution. They will continue to kick-off. We need to purge them from the database if we truly want to get rid of them.


Additionally, I believe the login is sitting waiting undefinedly when the wrong password is entered.

2020-11-02 16:55 UTC, jdotcms approved these changes

2020-11-03 20:56 UTC, wezell commented
I think we should add `DELETE_EVENTS_OLDER_THAN=4` to delete system events older than 4 days

2020-11-03 22:01 UTC, fabrizzio-dotCMS approved these changes

2020-11-12 14:29 UTC, dsilvam approved these changes

2020-11-12 14:50 UTC, merged