#19489 #19458 Unique fields and tag fields are mapped as keywords
dotCMS/core pull request #19628
Opened 2020-11-25 17:07 UTC by nollymar

2020-12-01 14:46 UTC, dsilvam approved these changes

2020-12-01 14:54 UTC, wezell requested changes

2020-12-01 15:15 UTC, nollymar commented on dotCMS/src/main/java/com/dotcms/content/elasticsearch/util/ESMappingUtilHelper.java
> +                    if (field.unique() || field instanceof TagField) {
@wezell it's already implemented here: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESMappingAPIImpl.java#L703-L708 . But I'll confirm with Kibana 👍

2020-12-01 15:15 UTC, nollymar commented on dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java
> +                                        new LegacyFieldTransformer(field).from()))
I'll do some tests

2020-12-01 16:15 UTC, fabrizzio-dotCMS approved these changes

2020-12-01 16:42 UTC, nollymar commented on dotCMS/src/main/java/com/dotcms/content/elasticsearch/util/ESMappingUtilHelper.java
> +                    if (field.unique() || field instanceof TagField) {
I have confirmed. No additional change is needed

2020-12-02 01:45 UTC, nollymar commented on dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java
> +                                        new LegacyFieldTransformer(field).from()))
@wezell I have fixed it. I modified the logic to use the `_sha256` field to make the validation more accurate and consider special characters. 

Besides, `_sha256` are now mapped as `keyword`

2020-12-02 20:35 UTC, merged