#19831 : There are two main changes in this PR, beyond the usual Java…
dotCMS/core pull request #19833
Opened 2021-01-20 17:03 UTC by jcastro-dotcms

…doc/refactor changes:

1. The method that validates the URL in a page is retrieving the right Site now when pages are created at the root of the Site. This was not occurring as expected, and revealed a situation in which the `SYSTEM_FOLDER` was referencing a Site that is not the `SYSTEM_HOST`. This is an extremely random situation, and haven't been able to reproduce locally.

2. In the Folder Cache, I'm explicitly setting the `SYSTEM_FOLDER` to always point to the `SYSTEM_HOST`.

2021-01-20 17:52 UTC, jdotcms approved these changes

2021-01-21 15:43 UTC, erickgonzalez approved these changes

2021-01-21 18:18 UTC, nollymar requested changes
The validation added in FolderCacheImpl should have a couple of tests using SYSTEM_HOST and another site

2021-02-09 21:42 UTC, dsilvam approved these changes

2021-03-02 17:46 UTC, dsilvam commented
@nollymar integration tests were implemented

2021-03-02 18:01 UTC, nollymar approved these changes

2021-03-03 15:09 UTC, merged