#19832 : Handling exact matches for legacy IDs, which are simple numb…
dotCMS/core pull request #19834
Opened 2021-01-20 17:59 UTC by jcastro-dotcms

…ers and not UUIDs. Usual Javadoc/refactoring changes.

2021-01-20 18:01 UTC, wezell commented
We need to understand the performance implications of this change - every request hits these methods.

2021-01-21 15:41 UTC, erickgonzalez approved these changes

2021-01-21 18:19 UTC, nollymar requested changes

2021-01-21 18:19 UTC, nollymar commented on dotCMS/src/main/java/com/dotcms/uuid/shorty/ShortyIdAPIImpl.java
> +      final boolean isExactMatch = NumberUtils.isParsable(shortStr) ? Boolean.TRUE : Boolean.FALSE;
This logic should have a test

2021-02-09 20:28 UTC, dsilvam commented on dotCMS/src/integration-test/java/com/dotcms/uuid/shorty/LegacyShortyIdApiTest.java
> +    public void testShortify() {
javadoc

2021-02-09 20:28 UTC, dsilvam commented on dotCMS/src/integration-test/java/com/dotcms/uuid/shorty/LegacyShortyIdApiTest.java
> +    public void testShortyLookup() {
javadoc

2021-02-09 20:28 UTC, dsilvam commented on dotCMS/src/integration-test/java/com/dotcms/uuid/shorty/LegacyShortyIdApiTest.java
> +    public void testShortyCache() {
javadoc

2021-02-09 20:28 UTC, dsilvam commented on dotCMS/src/integration-test/java/com/dotcms/uuid/shorty/LegacyShortyIdApiTest.java
> +    public void testValidShorty() {
javadoc

2021-02-09 20:29 UTC, dsilvam commented on dotCMS/src/integration-test/java/com/dotcms/uuid/shorty/LegacyShortyIdApiTest.java
> +    public void test404Cache() {
javadoc

2021-02-09 20:29 UTC, dsilvam commented on dotCMS/src/integration-test/java/com/dotcms/uuid/shorty/LegacyShortyIdApiTest.java
> +    public void testIdentifier404CacheInvalidation() throws Exception{
javadoc

2021-02-09 20:29 UTC, dsilvam commented on dotCMS/src/integration-test/java/com/dotcms/uuid/shorty/LegacyShortyIdApiTest.java
> +    public void testContentlet404CacheInvalidation() throws Exception{
javadoc

2021-02-09 20:29 UTC, dsilvam commented on dotCMS/src/integration-test/java/com/dotcms/uuid/shorty/LegacyShortyIdApiTest.java
> +    public void testUuidIfy() {
javadoc

2021-02-09 20:29 UTC, dsilvam commented on dotCMS/src/integration-test/java/com/dotcms/uuid/shorty/LegacyShortyIdApiTest.java
> +    public void testLongerShorties() {
javadoc

2021-02-09 20:29 UTC, dsilvam commented on dotCMS/src/integration-test/java/com/dotcms/uuid/shorty/LegacyShortyIdApiTest.java
> +    public void testTempShorties() throws DotSecurityException, IOException {
javadoc

2021-02-18 16:39 UTC, nollymar commented on dotCMS/src/integration-test/java/com/dotcms/uuid/shorty/LegacyShortyIdApiTest.java
> +        Assert.assertEquals(shortyIdAPI.shortify(testCase._1), testCase._2);
the expected result should be the first parameter of the assert

2021-02-18 16:46 UTC, nollymar approved these changes

2021-02-18 18:03 UTC, merged