Issue 19992 no need for additional concurrency
dotCMS/core pull request #20002
Opened 2021-02-24 13:47 UTC by wezell

This removes the idea of starting the monitor in a separate thread - the code is already being run in a separate thread as a result of a Future, there is no need to spin up more threads.  What is important is that the EsMonitor.start() method can only get called once - and further calls to start it it should just return if it is started or starting.  This is because the start method makes 2 ES calls - and if you ES nodes are failing, then adding additional calls to those nodes is many times counter productive and causes runaway outages.

Th

2021-02-24 14:33 UTC, freddyucv requested changes, later dismissed
Are you sure it solve the bug? because I think the bug it here

https://github.com/dotCMS/core/blob/4b32284db0ea826ef6cff4e6afe857593635f1a8/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESReadOnlyMonitor.java#L169

Because we are starting the Monitor with the DotConcurrentFactory default values, I think this fix just avoid send request to check the ES Cluster read only state when the Monitor is already startered

2021-02-24 22:26 UTC, nollymar approved these changes

2021-02-24 22:27 UTC, nollymar commented
Beware of tests results before merging this change, ITs in postgres were cancelled after 360m

2021-03-01 16:59 UTC, jdotcms approved these changes

2021-03-24 20:13 UTC, closed without merging