Cleaned up fake emails for anonymous and system users
dotCMS/core pull request #20094
Opened 2021-03-12 19:58 UTC by swicken-dotcms

Cleaned up fake emails for anonymous and system users to be more friendly. Updated same emails in tests to reflect this change.

2021-03-15 14:01 UTC, freddyucv requested changes

2021-03-15 14:01 UTC, freddyucv commented on dotCMS/src/main/java/com/dotmarketing/business/UserAPIImpl.java
> +            user = createUser(CMS_ANON_USER_ID, "anonymous@dotcms.anonymoususer");
We should use a constant here

2021-03-15 14:01 UTC, freddyucv commented on dotCMS/src/main/java/com/dotmarketing/business/UserAPIImpl.java
> +            user = createUser(CMS_ANON_USER_ID, "anonymous@dotcms.anonymoususer");
same here

2021-03-15 15:57 UTC, swicken-dotcms commented on dotCMS/src/main/java/com/dotmarketing/business/UserAPIImpl.java
> +            user = createUser(CMS_ANON_USER_ID, "anonymous@dotcms.anonymoususer");
Agreed, moved to constant

2021-03-15 15:57 UTC, swicken-dotcms commented on dotCMS/src/main/java/com/dotmarketing/business/UserAPIImpl.java
> +            user = createUser(CMS_ANON_USER_ID, "anonymous@dotcms.anonymoususer");
Agreed, moved to constant

2021-03-18 15:50 UTC, dsilvam approved these changes

2021-03-18 17:28 UTC, freddyucv approved these changes

2021-03-18 17:30 UTC, merged