Missing code change
dotCMS/core pull request #20155
Opened 2021-03-26 15:38 UTC by jcastro-dotcms

2021-03-26 15:44 UTC, jdotcms approved these changes

2021-03-26 15:53 UTC, erickgonzalez approved these changes
looks good but it need tests

2021-03-30 15:07 UTC, dsilvam requested changes
Missing tests

2021-04-06 17:15 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/util/RegEX.java
> +		final RegEX i = getInstance();
better name here

2021-04-06 17:15 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/util/RegEX.java
> +		final List<RegExMatch> res = new ArrayList<>();
better name here

2021-04-06 17:16 UTC, jdotcms approved these changes

2021-04-06 21:54 UTC, dsilvam approved these changes

2021-04-07 17:35 UTC, merged