#21077 adding ability to the local events to be cluster wide
dotCMS/core pull request #20178
Opened 2021-04-01 17:05 UTC by jdotcms

Adding the ability to local events to be cluster wide at server level

2021-04-05 14:27 UTC, freddyucv approved these changes

2021-04-05 14:27 UTC, freddyucv commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/system/logger/ChangeLoggerLevelEvent.java
> +public class ChangeLoggerLevelEvent {
javadoc

2021-04-05 14:27 UTC, freddyucv commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/system/logger/LoggerResource.java
> +                                    )));
should the Resource trigger the event?

2021-04-06 05:20 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/system/logger/LoggerResource.java
> +                                    )));
agree, but there is not API for Logger.

2021-04-06 14:58 UTC, wezell requested changes, later dismissed

2021-04-06 14:58 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/api/system/event/SystemEventType.java
> +	LOCAL_SYSTEM_EVENT,
This should be `CLUSTER_WIDE_EVENT`   I would also put javadocs on each of the enum properties

2021-04-08 15:14 UTC, erickgonzalez approved these changes

2021-04-08 15:17 UTC, erickgonzalez commented
We need to merge master to this branch, so the tests run. We need to check the tests results before merging

2021-04-08 19:06 UTC, merged