#19646 Avoid Out of Memory with huge file
dotCMS/core pull request #20366
Opened 2021-05-07 22:18 UTC by freddyucv

2021-05-11 21:00 UTC, jcastro-dotcms requested changes

2021-05-11 21:00 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotcms/publishing/output/TarGzipBundleOutput.java
> +    public void innerCopyFile(final File source, final String destinationPath) throws IOException {
Javadoc

2021-05-11 21:00 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotcms/publishing/output/BundleOutput.java
> +    protected void innerCopyFile(final File source, final String destinationPath) throws IOException {
Javadoc

2021-05-11 22:29 UTC, jcastro-dotcms approved these changes

2021-05-12 14:35 UTC, victoralfaro-dotcms commented on dotCMS/src/main/java/com/dotcms/publishing/output/TarGzipBundleOutput.java
> +    public void innerCopyFile(final File source, final String destinationPath) throws IOException {
@Override annotation

2021-05-12 14:44 UTC, freddyucv commented on dotCMS/src/main/java/com/dotcms/publishing/output/TarGzipBundleOutput.java
> +    public void innerCopyFile(final File source, final String destinationPath) throws IOException {
done https://github.com/dotCMS/core/pull/20366/commits/7987a2ab154551b9e6b63a477d7028df144bcb29

2021-05-12 16:25 UTC, dsilvam approved these changes

2021-05-12 16:35 UTC, victoralfaro-dotcms approved these changes
LGTM

2021-05-13 17:39 UTC, jdotcms approved these changes

2021-05-14 18:51 UTC, closed without merging