#20334 the domain set on the cookies on a weird path, setting to / to…
dotCMS/core pull request #20418
Opened 2021-05-19 21:00 UTC by jdotcms

The CookieTool now set the path to root, this avoids the dupes

2021-05-20 14:24 UTC, nollymar reviewed
A couple of tests on CookieTool methods can be implemented

2021-05-20 15:36 UTC, jdotcms commented
> A couple of tests on CookieTool methods can be implemented

Done, thanks

2021-05-20 17:50 UTC, nollymar approved these changes

2021-05-21 15:13 UTC, erickgonzalez requested changes

2021-05-21 15:13 UTC, erickgonzalez commented on dotCMS/src/integration-test/java/org/apache/velocity/tools/view/tools/CookieToolTest.java
> +public class CookieToolTest {
Need to add this test to the MainSuite to make it run.

2021-05-24 22:52 UTC, merged