#20501 wrong id was set on copy action class
dotCMS/core pull request #20502
Opened 2021-06-08 04:21 UTC by jdotcms

Before this change, a wf with actionlet parameter could not be copied

2021-06-09 15:00 UTC, erickgonzalez commented
Tests created on this PR are failing.

2021-06-10 15:46 UTC, jcastro-dotcms approved these changes

2021-06-10 17:30 UTC, dsilvam approved these changes

2021-06-10 17:31 UTC, dsilvam requested changes
workflow postman tests failing

2021-06-10 18:08 UTC, erickgonzalez approved these changes

2021-06-11 15:53 UTC, jdotcms commented
> workflow postman tests failing

I have worked on WF fixes in three branches, unfortunately I push here the postman resource with the test for all of them, so some of the test are failing b/c the code does not exists yet on the branch.
Hopelly when the branches are merged, all issues will be gone

2021-06-11 15:54 UTC, dsilvam approved these changes

2021-06-14 14:40 UTC, merged