Issue 20060 wf multiple contentlet
dotCMS/core pull request #20511
Opened 2021-06-09 04:38 UTC by jdotcms

First intent of the fire multiple contentlets in just one request

2021-06-09 15:11 UTC, erickgonzalez commented
Tests related to Workflow Resource are failing.

2021-06-10 15:49 UTC, jcastro-dotcms requested changes

2021-06-10 15:49 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotcms/workflow/form/FireMultipleActionForm.java
> +public class FireMultipleActionForm extends Validated {
Javadoc

2021-06-10 15:49 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/workflow/WorkflowResource.java
> +    private void saveMultipleContentletsByDefaultAction(final List<Map<String, Object>> contentletsToSaveList,
Javadoc

2021-06-10 15:49 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/workflow/WorkflowResource.java
> +                    Logger.error(this, "Error in contentlet: " + id + ", msg: " + e.getMessage(), e);
Is it possible to include what specific action failed for this content? If it is, we need to log it.

2021-06-10 18:08 UTC, erickgonzalez approved these changes

2021-07-09 17:47 UTC, jcastro-dotcms approved these changes

2021-07-20 17:15 UTC, nollymar commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/workflow/WorkflowResource.java
> +    //@Produces({MediaType.APPLICATION_JSON, "application/javascript"})
Please remove this commented line

2021-07-20 17:18 UTC, nollymar approved these changes

2021-07-22 14:28 UTC, merged