#20677 adding the login as to the current user
dotCMS/core pull request #20683
Opened 2021-07-16 22:29 UTC by jdotcms

Adding logic to limited the ability of doing login as only to the users with login as role assigned

2021-07-19 19:37 UTC, jcastro-dotcms requested changes

2021-07-19 19:37 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/user/UserResource.java
> +			throw new DotSecurityException("Must have the Login As role to execute this action");
Add User ID to error message

2021-07-19 19:48 UTC, jcastro-dotcms approved these changes

2021-07-19 19:55 UTC, nollymar commented on dotCMS/src/curl-test/UserResource.postman_collection.json
> +		{
please add a description to this test

2021-07-20 15:05 UTC, dsilvam approved these changes

2021-07-26 14:10 UTC, erickgonzalez approved these changes

2021-07-26 15:01 UTC, nollymar approved these changes

2021-07-26 15:02 UTC, merged