#20685 : When creating a Vanity URL from a Contentlet object, we need…
dotCMS/core pull request #20692
Opened 2021-07-20 16:23 UTC by jcastro-dotcms

… to validate it in order to make sure it's not missing any required parameters. Now we're checking that (1) it has the expected properties, and (2) that such properties are not null or empty. Adding more Javadoc, and some refactoring.

2021-07-23 15:05 UTC, erickgonzalez approved these changes

2021-07-29 14:51 UTC, nollymar requested changes
These validations should be covered by an IT

2021-08-03 18:50 UTC, nollymar approved these changes

2021-08-09 16:13 UTC, jdotcms approved these changes

2021-08-10 18:30 UTC, merged