#20718 Checking if id != null
dotCMS/core pull request #20730
Opened 2021-07-29 18:27 UTC by freddyucv

2021-07-29 18:59 UTC, jdotcms approved these changes

2021-07-29 22:03 UTC, dsilvam approved these changes

2021-07-29 22:04 UTC, dsilvam commented
Missing test

2021-07-29 22:05 UTC, dsilvam requested changes
missing test

2021-07-30 15:13 UTC, erickgonzalez approved these changes

2021-07-30 15:14 UTC, erickgonzalez approved these changes
Check Tests, lot of them are broken related to PP

2021-08-06 15:25 UTC, dsilvam approved these changes

2021-08-11 14:20 UTC, merged