#20504 add validation to check if content already exist at new path
dotCMS/core pull request #20739
Opened 2021-07-30 18:30 UTC by erickgonzalez

2021-07-30 21:54 UTC, jcastro-dotcms requested changes

2021-07-30 21:54 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java
> +            throw new IllegalArgumentException("Content with the same name already exists at the new path");
Add file path and name to the error message

2021-07-30 21:55 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java
> +        if(APILocator.getFileAssetAPI().fileNameExists(host, folder, identifier.getAssetName(), contentlet.getIdentifier())){
include more info: at least the id of the identifier and the folder path

2021-07-30 22:20 UTC, jdotcms approved these changes

2021-08-02 14:18 UTC, jcastro-dotcms approved these changes

2021-08-02 14:43 UTC, merged