Ad download Manifest Download button / Avoid create a empty manifest …
dotCMS/core pull request #20767
Opened 2021-08-05 15:57 UTC by freddyucv

Add download Manifest button, Also avoid create a empty Manifest file in static publish for now

2021-08-05 20:21 UTC, nollymar approved these changes

2021-08-05 21:36 UTC, jcastro-dotcms requested changes

2021-08-05 21:36 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            throw new DoesNotExistException("Th+e bundle not exists: " + bundleId);
Typo

2021-08-06 15:21 UTC, freddyucv commented on dotCMS/src/main/java/com/dotcms/rest/BundleResource.java
> +            throw new DoesNotExistException("Th+e bundle not exists: " + bundleId);
done https://github.com/dotCMS/core/pull/20767/commits/be1cb543159542c708a6765ffc57b1e6a7f5490a#diff-2e4f2aadb1a2604874bcc2b2bd36e33cc4feb91991d5e7866ad2b9088e0609a4L942

2021-08-11 14:23 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/publishing/PublisherConfig.java
> +			return Optional.empty();
Log exception?

2021-08-11 15:15 UTC, dsilvam approved these changes

2021-08-11 15:29 UTC, merged