Issue 20891 config endpoint
dotCMS/core pull request #20894
Opened 2021-09-01 20:51 UTC by jdotcms

Adding a new endpoint to retrieve configuration from the dotmarketing config, allowed by while list key set and not restricted by the black list

2021-09-02 14:03 UTC, freddyucv requested changes
curl-test missing

2021-09-02 18:29 UTC, erickgonzalez approved these changes

2021-09-03 15:51 UTC, nollymar commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/system/ConfigurationResource.java
> +			Config.getStringProperty("OBFUSCATE_SYSTEM_ENVIRONMENTAL_VARIABLES", "passw|pass|passwd|secret|key|token"),
I think we already have a `OBFUSCATE_SYSTEM_ENVIRONMENTAL_VARIABLES` defined in the JVMInfoResource. Wouldn't be convenient to have a public constant shared by both endpoints?

2021-09-03 15:54 UTC, nollymar commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/system/ConfigurationResource.java
> +			return Config.getIntProperty(key.replace("boolean:", StringPool.BLANK), 0);
The replace here shouldn't be: `Config.getIntProperty(key.replace("number:", StringPool.BLANK), 0);` ?

2021-09-03 17:31 UTC, nollymar approved these changes

2021-09-07 20:16 UTC, merged