Issue 20971 large bundles make the viewing publishing queue slow
dotCMS/core pull request #21056
Opened 2021-09-21 22:26 UTC by freddyucv

Create a new end point to get the assets from a bundle.
Update the 'view_unpushed_bundles.jsp ' to show just 20 assets by bundle, and add a link to view all the asset

2021-09-22 15:10 UTC, victoralfaro-dotcms approved these changes
LGTM

2021-09-22 18:56 UTC, jdotcms approved these changes

2021-10-07 22:36 UTC, jcastro-dotcms requested changes

2021-10-07 22:53 UTC, jdotcms approved these changes

2021-10-11 14:13 UTC, victoralfaro-dotcms approved these changes
LGTM

2021-10-11 15:53 UTC, jcastro-dotcms approved these changes

2021-10-11 20:56 UTC, jdotcms approved these changes

2021-10-13 16:59 UTC, merged