Issue 21011 contentlet as json 2
dotCMS/core pull request #21148
Opened 2021-10-12 16:40 UTC by fabrizzio-dotCMS

This adds storing contentlet as JSON capabilities.
A New column was added. The upsert command was modified to support the new column plus it handles the special formating required by postgres.
Also, the way we return keyValues was modified so we always get a Map and not String.

2021-10-25 17:24 UTC, nollymar requested changes
I left some comments

2021-11-02 21:04 UTC, nollymar approved these changes

2021-11-02 21:07 UTC, spbolton approved these changes

2021-11-02 21:08 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/content/business/ContentletJsonAPI.java
> + *
Doc

2021-11-02 21:11 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/content/business/ContentletJsonAPIImpl.java
> +        return objectMapper;
We already have an one for the Rest endpoints, but I guess Fab has a reason to config their own one

2021-11-02 21:14 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentFactoryImpl.java
> +                    Logger.info(ESContentletAPIImpl.class, asJson);
is that ok, may be so noisy

2021-11-02 21:15 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentFactoryImpl.java
> +        if (prefix.equals("integer") || prefix.equals("float")){
constants should be in the left

2021-11-02 21:31 UTC, jdotcms approved these changes

2021-11-03 15:10 UTC, merged