#21177 : Removed unnecessary debugging logging. Added a status messag…
dotCMS/core pull request #21181
Opened 2021-10-19 20:11 UTC by jcastro-dotcms

…e that logs every 100 processed records in the CSV file.  Added unexpected error handling when unique field search returns an Inode that doesn't exist in the DB anymore. Fixed UI to correctly disable and display the right label after clicking the "Preview" button.

2021-10-20 14:59 UTC, erickgonzalez approved these changes

2021-10-26 14:27 UTC, freddyucv approved these changes

2021-11-17 17:25 UTC, jdotcms approved these changes

2021-11-30 21:31 UTC, nollymar approved these changes

2021-12-02 14:30 UTC, nollymar requested changes
Some tests are failing because of these changes

2021-12-10 17:49 UTC, fabrizzio-dotCMS commented
> 

They're fixed now

2021-12-13 15:46 UTC, nollymar approved these changes

2021-12-13 15:47 UTC, merged