#21100 missing the server id when sending a PubSub message
dotCMS/core pull request #21292
Opened 2021-11-22 18:32 UTC by jdotcms

When sending the event out the server id was missing

2021-11-22 19:24 UTC, nollymar approved these changes

2021-11-23 14:08 UTC, freddyucv requested changes
any test here?

2021-11-23 14:09 UTC, freddyucv requested changes

2021-11-23 14:09 UTC, freddyucv commented on dotCMS/src/main/java/com/dotcms/dotpubsub/RedisPubSubImpl.java
> +    public boolean publish(final DotPubSubEvent eventIn) {
doc?

2021-11-23 14:09 UTC, freddyucv commented on dotCMS/src/main/java/com/dotcms/dotpubsub/RedisPubSubImpl.java
> +    public final String serverId;
it is public, is it ok or it should be private?

2021-11-30 16:28 UTC, erickgonzalez approved these changes

2021-11-30 17:33 UTC, erickgonzalez commented
Closing in favor https://github.com/dotCMS/core/pull/21329

2021-11-30 17:33 UTC, closed without merging