21154 bulk actions timing out
dotCMS/core pull request #21332
Opened 2021-11-30 19:52 UTC by dsilvam

Almost done

2021-11-30 21:09 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/workflows/business/WorkflowAPI.java
> +	void fireBulkActionTasks(final WorkflowAction action,
Add doc

2021-11-30 21:16 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/workflow/WorkflowResource.java
> +        new Thread(new Runnable() {
use the DotConcurrent

2021-11-30 21:19 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/workflow/WorkflowResource.java
> +        final EventOutput eventOutput = new EventOutput();
I think this is ok but eventually you can encapsulate this on an API or Delegate such as
```
ServerSideEventDelegate delegate = SystemEventsAPI.createServerSideEventDelegate();
// .....
delegate.sendMap(map("success", delta));
// .....
delegate.sendString("failed:" + inode));
```

2021-12-08 21:09 UTC, wezell requested changes

2021-12-08 21:09 UTC, wezell commented on dotCMS/src/main/java/com/dotmarketing/portlets/workflows/business/WorkflowAPIImpl.java
> +						NotificationLevel.INFO, NotificationType.GENERIC, Visibility.ROLE, cmsAdminRole.getId(), systemUser.getUserId(),
Send the notification to the user who ran the bulk action only

2021-12-08 21:10 UTC, wezell requested changes

2021-12-08 21:10 UTC, wezell commented on dotCMS/src/main/webapp/html/portlet/ext/contentlet/view_bulk_actions_inc.jsp
> +            console.log(e.data);
remove `console.log` from the production code

2021-12-10 16:21 UTC, erickgonzalez approved these changes

2021-12-16 21:59 UTC, victoralfaro-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/workflows/business/WorkflowAPIImpl.java
> +			//final long skipsCount = (inodes.size() - contentlets.size());
Nitpick: remove unused

2021-12-17 20:31 UTC, victoralfaro-dotcms approved these changes
LGTM

2022-01-03 20:21 UTC, merged