dotCMS/core#21279 Editor content is overflowing
dotCMS/core pull request #21355
Opened 2021-12-03 14:22 UTC by rjvelazco

#### Description
When you add a lot of content in the editor is overflowing out of the editor.

#### Screenshots
| Issue  | Fix |
| ----------- | ----------- |
|  ![image](https://user-images.githubusercontent.com/72418962/144617679-333f5f2e-c2cb-4707-bdd5-8c9af89ae2b6.png) |  ![image](https://user-images.githubusercontent.com/72418962/144617592-8ff80b4a-bac2-442a-b101-fd2530820000.png) |

2021-12-03 15:24 UTC, nollymar approved these changes

2021-12-03 17:04 UTC, hmoreras approved these changes

2021-12-06 12:51 UTC, fmontes requested changes

2021-12-06 12:51 UTC, fmontes commented on dotCMS/src/main/webapp/html/portlet/ext/contentlet/field/edit_field.jsp
> -            <dotcms-block-editor style="width: 100%; height: 500px; display: block;"></dotcms-block-editor>
We do want a max-height here, so this is not a fix, we need to figure it out how we can do a max-height without breaking the editor.

2021-12-07 14:49 UTC, merged