Issue 21432 container endpoint
dotCMS/core pull request #21455
Opened 2021-12-22 17:01 UTC by jdotcms

Draft of Containers endpoint

2022-01-12 14:11 UTC, freddyucv approved these changes

2022-03-14 19:57 UTC, nollymar requested changes
~~There are some logic in ContainerFactoryImpl and ContainerAPIImpl that don't seem to be covered by the curl tests, for example: validations. 

Besides, I would include some doc to the curl test cases. It will be really helpful when we break them with future changes.~~

Now, I see the new tests and the doc but some curl-tests are broken.

2022-05-12 23:16 UTC, jdotcms commented
> ~There are some logic in ContainerFactoryImpl and ContainerAPIImpl that don't seem to be covered by the curl tests, for example: validations.~
> 
> ~Besides, I would include some doc to the curl test cases. It will be really helpful when we break them with future changes.~
> 
> Now, I see the new tests and the doc but some curl-tests are broken.

Curl are now working, the issue was that the default host, wasn't the default and the container vtl files were saved on the host but could reach it out when make the request, now I have introduce a new call to set the default host as default one

2022-05-13 13:44 UTC, jcastro-dotcms requested changes

2022-05-13 13:44 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/container/ContainerResource.java
> +        if(!APILocator.getPermissionAPI().doesUserHavePermission(host, PermissionAPI.PERMISSION_CAN_ADD_CHILDREN, user, pageMode.respectAnonPerms)
Shouldn't we check permissions at API level instead of the REST Endpoint?

2022-05-13 13:44 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/container/ContainerResource.java
> +        if(!APILocator.getPermissionAPI().doesUserHavePermission(host, PermissionAPI.PERMISSION_CAN_ADD_CHILDREN, user, pageMode.respectAnonPerms)
Shouldn't we check permissions at API level instead of the REST Endpoint?

2022-05-13 13:44 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/container/ContainerResource.java
> +        Logger.error(this, "The container: " + container.getIdentifier() + " has been updated");
It should be `logger.info`, not `logger.error`

2022-05-13 13:44 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/containers/business/ContainerAPI.java
>  	/**
Please bring the correct Javadoc back.

2022-05-13 13:44 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/containers/business/ContainerAPI.java
> -	@Deprecated
Please bring the correct Javadoc back.

2022-05-13 19:43 UTC, nollymar approved these changes

2022-05-13 20:05 UTC, merged