Issue 20892 update docker clean
dotCMS/core pull request #21530
Opened 2022-01-13 20:15 UTC by nollymar

2022-01-14 15:43 UTC, jdotcms approved these changes

2022-01-18 15:15 UTC, victoralfaro-dotcms approved these changes

2022-01-18 15:26 UTC, erickgonzalez requested changes

2022-01-18 15:26 UTC, erickgonzalez commented on docker/dotcms/Dockerfile
> +FROM dotcms/java-base:22.01 as container-base
is this ok?

2022-01-18 15:26 UTC, erickgonzalez commented on dotCMS/src/main/java/com/dotmarketing/db/SystemEnvDataSourceStrategy.java
> +                : "jdbc:postgresql://db.dotcms.site/dotcms");
is this ok?

2022-01-18 15:52 UTC, nollymar commented on .github/workflows/core-cicd-tests.yml
> +      DOT_CICD_BRANCH: issue-20892-update-docker-clean
I set it this way to make sure tests run ok, but it will be changed to `release-22.02` once the PR is approved

2022-01-18 15:52 UTC, nollymar commented on docker/dotcms/Dockerfile
> +FROM dotcms/java-base:22.01 as container-base
yes, it is

2022-01-18 15:53 UTC, nollymar commented on dotCMS/src/main/java/com/dotmarketing/db/SystemEnvDataSourceStrategy.java
> +                : "jdbc:postgresql://db.dotcms.site/dotcms");
yes, it is

2022-01-18 15:56 UTC, erickgonzalez approved these changes

2022-01-19 15:13 UTC, merged