#20929 Update Powermock and Mokito to Java 11 supported version 2.x
dotCMS/core pull request #21548
Opened 2022-01-19 14:00 UTC by freddyucv

2022-01-19 22:22 UTC, nollymar requested changes
There is one test failing [here](https://raw.githack.com/dotCMS/test-results/issue-20929-Update-Powermock-and-Mokito-to-Java-11-supported-version/projects/core/current/integration/postgres/reports/html/classes/com.dotcms.rest.api.v1.workflow.WorkflowResourceLicenseIntegrationTest.html#Find_Available_Default_Actions_No_Read_Permission_Invalid_License). Might it be related to your changes?

2022-01-20 14:10 UTC, freddyucv commented
> There is one test failing [here](https://raw.githack.com/dotCMS/test-results/issue-20929-Update-Powermock-and-Mokito-to-Java-11-supported-version/projects/core/current/integration/postgres/reports/html/classes/com.dotcms.rest.api.v1.workflow.WorkflowResourceLicenseIntegrationTest.html#Find_Available_Default_Actions_No_Read_Permission_Invalid_License). Might it be related to your changes?

I have ran the test 3 times without any change and that WorkflowResourceLicenseIntegrationTest  test not fail in the previos one so  it is a blinker test

2022-01-20 16:47 UTC, nollymar approved these changes

2022-01-20 19:13 UTC, jdotcms approved these changes

2022-01-20 20:35 UTC, dsilvam approved these changes

2022-01-20 20:35 UTC, merged