Issue 21122 htmldiff
dotCMS/core pull request #21580
Opened 2022-01-21 16:21 UTC by jdotcms

this new endpoint adds the ability to retrieve the live and preview version of a page, in order to do the what's changed on the FE side

2022-01-26 15:44 UTC, erickgonzalez approved these changes

2022-01-27 15:15 UTC, freddyucv requested changes
it need a curl-test

2022-01-31 14:57 UTC, fabrizzio-dotCMS approved these changes

2022-01-31 16:12 UTC, dsilvam approved these changes

2022-01-31 19:25 UTC, merged