#21454 Copying server.xml to the right path
dotCMS/core pull request #21593
Opened 2022-01-24 15:52 UTC by nollymar

With the cleanup, some required steps were removed

2022-01-24 15:53 UTC, jdotcms approved these changes

2022-01-24 15:55 UTC, fabrizzio-dotCMS approved these changes

2022-01-24 16:11 UTC, wezell commented on docker/dotcms/ROOT/srv/20-copy-overriden-files.sh
> +mv $TOMCAT_HOME/conf/server-${TOMCAT_VERSION}.xml $TOMCAT_HOME/conf/server.xml && \
I think the fix is to change the filename from `server-${TOMCAT_VERSION}.xml` to `server.xml`.  With the Dockerfile in the core repo, we do not need to support multiple versions of tomcat in any given branch and can remove all that  conditional logic.

2022-01-24 16:11 UTC, wezell requested changes
see my comment.  We need to remove any conditional tomcat version logic as in any given branch we know the exact path/version of tomcat

2022-01-25 00:45 UTC, nollymar commented
> see my comment. We need to remove any conditional tomcat version logic as in any given branch we know the exact path/version of tomcat

@wezell Done! Please take a look at my latest changes

2022-01-26 19:56 UTC, wezell commented on docker/dotcms/Dockerfile
> +RUN groupadd -f -g $USER_GID $USER_NAME
this needs to be changed to USER_GROUP

2022-01-26 19:57 UTC, wezell commented on docker/dotcms/README.md
> +| USER_GROUP    | Group name for user |
Add what the defaults are

2022-01-26 22:50 UTC, nollymar commented on docker/dotcms/Dockerfile
> +RUN groupadd -f -g $USER_GID $USER_NAME
Done

2022-01-26 22:50 UTC, nollymar commented on docker/dotcms/README.md
> +| USER_GROUP    | Group name for user |
Done

2022-01-26 22:50 UTC, merged