Release 22.02 to master
dotCMS/core pull request #21637
Opened 2022-01-31 16:18 UTC by fmontes

2022-01-31 16:53 UTC, dsilvam commented on .github/workflows/core-cicd-tests.yml
> +      DOT_CICD_BRANCH: release-22.02
discard

2022-01-31 16:53 UTC, dsilvam commented on .github/workflows/pre-release-process.yml
> +      DOT_CICD_BRANCH: release-22.02
discard

2022-01-31 16:53 UTC, dsilvam commented on .github/workflows/release-process.yml
> +      DOT_CICD_BRANCH: release-22.02
discard

2022-01-31 16:54 UTC, dsilvam commented on .gitmodules
> +	branch = release-22.02
discard

2022-01-31 16:54 UTC, dsilvam commented on dotCMS/gradle.properties
> +dotcmsReleaseVersion=22.02
discard these three

2022-01-31 21:03 UTC, dsilvam approved these changes

2022-02-01 21:48 UTC, erickgonzalez requested changes

2022-02-01 21:48 UTC, erickgonzalez commented on dotCMS/build.gradle
> +    // starter group: 'com.dotcms', name: 'starter', version: 'empty_20211201', ext: 'zip'
We ship with empty starter, these changes needs to be reverteed

2022-02-01 22:56 UTC, nollymar approved these changes

2022-02-02 15:11 UTC, erickgonzalez approved these changes

2022-02-02 16:04 UTC, closed without merging