#21718 adding changes to the copy host
dotCMS/core pull request #21826
Opened 2022-03-07 19:07 UTC by jdotcms

A few changes to avoid freezing the copy host job

2022-03-09 15:15 UTC, freddyucv requested changes

2022-03-30 19:56 UTC, nollymar commented on dotCMS/dependencies.gradle
> +    //compile fileTree(dir: 'src/main/enterprise/build/libs', include: ['ee_clean.jar'])
please remove this line

2022-03-30 20:11 UTC, jcastro-dotcms approved these changes

2022-03-30 20:13 UTC, jcastro-dotcms requested changes

2022-03-30 20:13 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/hostadmin/business/CopyHostContentUtil.java
>  			Logger.error(this, e.getMessage(), e);
Let's include the `newSite` in both the logged message and exception's message

2022-03-30 21:03 UTC, victoralfaro-dotcms approved these changes
LGTM

2022-03-30 21:08 UTC, nollymar approved these changes

2022-03-30 22:36 UTC, merged