#21889 Change Vanity URL field type to HostFolderField
dotCMS/core pull request #21923
Opened 2022-03-30 17:33 UTC by freddyucv

2022-03-30 20:01 UTC, wezell requested changes

2022-03-30 20:01 UTC, wezell commented on dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task220330ChangeVanityURLSiteFieldType.java
> +                + "WHERE field_name = 'Site' and structure_inode in (select inode from structure where structuretype = 7)";
where clause should use the `velocity_var_name` as field_name is not unique

2022-04-06 16:25 UTC, jdotcms approved these changes

2022-04-08 16:21 UTC, victoralfaro-dotcms commented on dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task220330ChangeVanityURLSiteFieldType.java
> +public class Task220330ChangeVanityURLSiteFieldType implements StartupTask {
Javadoc

2022-04-08 16:32 UTC, dsilvam commented on dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task220330ChangeVanityURLSiteFieldType.java
> +public class Task220330ChangeVanityURLSiteFieldType implements StartupTask {
javadoc

2022-04-08 16:37 UTC, wezell commented
Guys, can we get this merged so we can cherry-pick it into a 5.3.8 test branch?  We can do the javadoc after this.  A customer is waiting for a fix.

2022-04-08 16:37 UTC, dsilvam approved these changes

2022-04-08 16:43 UTC, freddyucv commented on dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task220330ChangeVanityURLSiteFieldType.java
> +public class Task220330ChangeVanityURLSiteFieldType implements StartupTask {
done https://github.com/dotCMS/core/pull/21923/commits/a0f04ac75eadcd9317cbf91cb0039ca074f80011

2022-04-08 16:43 UTC, freddyucv commented on dotCMS/src/main/java/com/dotmarketing/startup/runonce/Task220330ChangeVanityURLSiteFieldType.java
> +public class Task220330ChangeVanityURLSiteFieldType implements StartupTask {
done https://github.com/dotCMS/core/pull/21923/commits/a0f04ac75eadcd9317cbf91cb0039ca074f80011

2022-04-08 16:44 UTC, victoralfaro-dotcms approved these changes
LGTM

2022-04-08 17:39 UTC, dsilvam approved these changes

2022-04-08 17:42 UTC, merged