Issue 21882 osgi upload share lock
dotCMS/core pull request #21958
Opened 2022-04-05 05:50 UTC by jdotcms

Implementing a cluster share lock, this allows a block cluster wide over parallel threads running on diff nodes (by using a db table by default)

2022-04-18 21:50 UTC, nollymar commented on dotCMS/dependencies.gradle
> +    //compile fileTree(dir: 'src/main/enterprise/build/libs', include: ['ee_clean.jar'])
Please remove this line

2022-04-18 21:51 UTC, nollymar commented
MSSQL tests aren't running: https://raw.githack.com/dotCMS/test-results/issue-21882-osgi-upload-share-lock/projects/core/current/integration/mssql/reports/html/packages/com.dotcms.html

2022-04-18 21:52 UTC, nollymar requested changes
Please check out MSSQL tests

2022-04-19 06:10 UTC, jdotcms commented
> 

it seems to be the same thing that Fabrizzio is looking

2022-04-19 18:26 UTC, jdotcms commented
> MSSQL tests aren't running: https://raw.githack.com/dotCMS/test-results/issue-21882-osgi-upload-share-lock/projects/core/current/integration/mssql/reports/html/packages/com.dotcms.html

I have add a fix in order to avoid start the sub pub on mssql, since it only runs on postgres

2022-04-20 23:28 UTC, merged