#22119 no error on null get
dotCMS/core pull request #22121
Opened 2022-04-29 21:19 UTC by wezell

This prevents an error from being thrown when a .get returns a null value.

2022-04-29 21:56 UTC, jdotcms approved these changes

2022-04-30 21:52 UTC, nollymar requested changes
Some ITs of StoryBlockMapTest are broken

2022-05-03 15:41 UTC, fmontes commented
Issue: https://github.com/dotCMS/core/issues/22128

2022-05-03 19:36 UTC, fmontes commented
Close in favor of: https://github.com/dotCMS/core/issues/22128#issuecomment-1116429603

2022-05-03 19:36 UTC, closed without merging