Issue 22128 storyblock velocity
dotCMS/core pull request #22133
Opened 2022-05-03 14:03 UTC by wezell

This cleans up the velocity files for the storyblock field.

2022-05-03 15:42 UTC, jdotcms approved these changes

2022-05-09 21:43 UTC, jcastro-dotcms commented on dotCMS/src/integration-test/java/com/dotcms/rendering/velocity/viewtools/content/StoryBlockMapTest.java
>      }
Shouldn't you include the `</li>` and `</ol>` tags in the test as well?

2022-05-09 22:52 UTC, nollymar requested changes
The ITs are broken: https://raw.githack.com/dotCMS/test-results/issue-22128-storyblock-velocity/projects/core/current/integration/postgres/reports/html/index.html

2022-05-11 16:00 UTC, fmontes commented
This fix:

- https://github.com/dotCMS/core/issues/22074
- https://github.com/dotCMS/core/issues/22128
- https://github.com/dotCMS/core/issues/22092

2022-05-17 22:04 UTC, merged