#21060 Using XStreamFactory everywhere
dotCMS/core pull request #22192
Opened 2022-05-10 21:56 UTC by freddyucv

Using XStreamFactory everywhere

2022-05-19 17:07 UTC, fabrizzio-dotCMS approved these changes

2022-05-19 17:11 UTC, jdotcms approved these changes

2022-05-19 17:18 UTC, jcastro-dotcms approved these changes

2022-05-19 22:05 UTC, nollymar requested changes
This test https://raw.githack.com/dotCMS/test-results/issue-21060-using-XStreamFactory-everywhere/projects/core/current/integration/postgres/reports/html/classes/com.dotcms.publisher.business.PublishAuditAPITest.html#allThePublishAuditHistoryWithOneAssets fails in both databases

2022-05-26 22:15 UTC, nollymar approved these changes

2022-05-26 23:05 UTC, merged