#21265 : Updating Empty Starter to exclude both System Template and Container as Files
dotCMS/core pull request #22252
Opened 2022-05-18 20:20 UTC by jcastro-dotcms

2022-05-18 20:22 UTC, jdotcms approved these changes

2022-05-18 20:23 UTC, fabrizzio-dotCMS approved these changes

2022-05-19 14:21 UTC, nollymar requested changes
@jcastro-dotcms could you please run these tests locally (using this empty starter):

https://raw.githack.com/dotCMS/test-results/issue-21265-move-system-template-to-velocity-pr2/projects/core/current/integration/postgres/reports/html/classes/com.liferay.portal.ejb.UserUtilTest.html#testFindByC_PWithLimit
https://raw.githack.com/dotCMS/test-results/issue-21265-move-system-template-to-velocity-pr2/projects/core/current/curl/postgres/reports/html/Browser_Resource.html

2022-05-19 21:58 UTC, nollymar approved these changes

2022-05-20 14:45 UTC, merged