Issue 22184 create osgi system framework
dotCMS/core pull request #22265
Opened 2022-05-19 21:30 UTC by jdotcms

Adding a draft for the osgi system framework

2022-06-08 01:54 UTC, wezell requested changes

2022-06-08 01:54 UTC, wezell commented on dotCMS/src/main/java/org/apache/felix/framework/OSGISystem.java
> +    public String getExtraOSGIPackages() throws IOException {
Most of these methods should be private, I think.  No reason to expose them publically

2022-06-08 01:54 UTC, wezell commented on dotCMS/src/main/java/org/apache/felix/framework/OSGISystem.java
> +    public String getBaseDirectory() {
private

2022-06-28 15:06 UTC, wezell approved these changes
Working as expected

2022-06-28 16:03 UTC, jcastro-dotcms approved these changes

2022-07-07 14:56 UTC, merged