#22144 fix invalid path coming from starter
dotCMS/core pull request #22355
Opened 2022-06-06 16:50 UTC by fabrizzio-dotCMS

### Proposed Changes
* Since the starter is generated using an absolute file-path on for file assets this causes the import starter metadata to fail. This will attempt to fix such a situation by matching the file against the local file that has been already written

### Checklist
- [ ] Tests 
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2022-06-06 19:16 UTC, nollymar requested changes
This test was not included in MainSuite

2022-06-06 20:31 UTC, fabrizzio-dotCMS commented
> This test was not included in MainSuite

@nollymar done

2022-06-07 15:22 UTC, nollymar commented
> > This test was not included in MainSuite
> 
> @nollymar done

@fabrizzio-dotCMS https://raw.githack.com/dotCMS/test-results/issue-22144-fix-metadata-gen-loading-starter/projects/core/current/integration/postgres/reports/html/classes/com.dotcms.content.model.hydration.MetadataDelegateTest.html#Test_File_Asset_Path_Normalized

2022-06-09 15:18 UTC, jcastro-dotcms approved these changes

2022-06-09 22:24 UTC, nollymar approved these changes

2022-06-09 22:24 UTC, merged