dotCMS/core#22323 Relationships will get cleared if you Save a contentlet before they are loaded
dotCMS/core pull request #22467
Opened 2022-06-22 18:29 UTC by rjvelazco

2022-06-28 17:40 UTC, hmoreras commented on dotCMS/src/main/webapp/html/portlet/ext/contentlet/contentlet_actions_inc.jsp
> +			<!--  Step: 3 - Agregar la clase 'disabled-contentlet-action' cuando existen relaciones -->
english.

2022-06-28 17:42 UTC, hmoreras requested changes

2022-06-28 17:42 UTC, wezell commented on dotCMS/src/main/webapp/html/portlet/ext/contentlet/edit_contentlet.jsp
> +				ådijit.byId('populateDialog').show();
utf-8 char looks like it slipped in there...

2022-06-28 17:44 UTC, wezell reviewed
Can you post a screencap/vid of the new interactivity?

2022-06-28 20:46 UTC, rjvelazco commented on dotCMS/src/main/webapp/html/portlet/ext/contentlet/edit_contentlet.jsp
> +				ådijit.byId('populateDialog').show();
Done!

2022-06-28 21:06 UTC, rjvelazco commented
@wezell Here is a video of [how it works](https://www.loom.com/share/4c3db341316f4d45a3f30748eb9a9c8f). 

In the FE, we do another request to get the `relationship fields`, that's why when the form is submitted the relationship data has not been loaded. After talking to @jcastro-dotcms, it looks like the easier solution.

2022-06-28 21:22 UTC, wezell commented
> @wezell Here is a video of [how it works](https://www.loom.com/share/4c3db341316f4d45a3f30748eb9a9c8f).
> 
> In the FE, we do another request to get the `relationship fields`, that's why when the form is submitted the relationship data has not been loaded. After talking to @jcastro-dotcms, it looks like the easier solution.

Ah, that is kind of what I was afraid of - it is actively blocking the user from completing their task and could give rise to user frustration.  

How about something like this:

When a user hits one of the workflow actions, we throw up a progress bar/spinner but only call `saveContent` once the relationships are all loaded.  Then once the `saveContent` is done, the  progress bar/spinner gets closed when the workflow action is returned. This way, it just feels like it is taking a little longer to save, rather than a user clicking an nothing happening.

1.  User load content to edit
2. Relationships not loaded....
3. User edits content and hits save and we show the `progress bar/dialog` like normal, but do not run the `saveContentlet`  yet, so it looks like it is saving normally
4. Relationships still not loaded....
5. `progress bar/dialog` still spinning ... 
6. Relationships finally load....
7. once the relationships are all loaded, we call the `saveContentlet` 
8. Once the `saveContentlet` completes, we close the `progress bar/dialog` like normal.

2022-06-30 14:10 UTC, oidacra approved these changes

2022-06-30 14:17 UTC, alfredo-dotcms approved these changes

2022-06-30 15:53 UTC, fmontes approved these changes

2022-06-30 15:57 UTC, nollymar approved these changes

2022-06-30 16:01 UTC, merged