#21713 migrating the EMA OVR to core
dotCMS/core pull request #22465
Opened 2022-06-21 22:37 UTC by jdotcms

Moving the EMA OVR changes to core.
Supporting override by query string + json rewrite on the url config

2022-06-22 21:42 UTC, jcastro-dotcms requested changes

2022-06-23 16:05 UTC, wezell commented
Also, I think we need to update the .yml to include more description and provide an example config.  The hint field takes markdown and we can provide a complete markdown.  Obviously this json is wrong but you get the idea.
```
    hint: "Your rendering server and endpoint that dotCMS will be proxying the request to, including the port, e.g. https://myspa.com:3000.  If you want to proxy different paths to different endpoints, you can specify this as json, e.g. ```\n{\"render\":\"testing\"}```"
```

2022-06-27 17:14 UTC, jcastro-dotcms approved these changes

2022-06-27 23:47 UTC, wezell approved these changes
Nice

2022-06-28 16:06 UTC, nollymar approved these changes

2022-06-28 17:13 UTC, merged