dotCMS/core#22335  fix storybook tasks nx
dotCMS/core pull request #22509
Opened 2022-07-01 15:46 UTC by oidacra

Fix storybook apps.

2022-07-01 16:21 UTC, hmoreras requested changes

2022-07-01 16:29 UTC, hmoreras requested changes

2022-07-01 16:29 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/api/services/dot-contentlet-locker/dot-contentlet-locker.service.ts
> +            .pipe(pluck('entity'));
the response changed in the endpoint ?

2022-07-01 16:29 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/api/services/dot-contentlet-locker/dot-contentlet-locker.service.ts
> +            .pipe(pluck('entity'));
the response changed in the endpoint ?

2022-07-01 16:29 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/api/services/notifications-service.ts
all the responses changed in the endpoints ?

2022-07-01 16:29 UTC, hmoreras commented on core-web/libs/dotcms-js/src/lib/core/core-web.service.ts
> +import { map, catchError, filter, tap } from 'rxjs/operators';
`tap` needed ?

2022-07-14 20:57 UTC, oidacra commented
Close in favor of https://github.com/dotCMS/core/pull/22514/

2022-07-14 20:57 UTC, closed without merging