#22522 sharing the conn pool between http clients and limitating the …
dotCMS/core pull request #22571
Opened 2022-07-13 22:40 UTC by jdotcms

sharing the connections pool between http clients and limit the number of concurrent connections

2022-07-14 13:53 UTC, wezell commented
I think I'd like to see this PR with only the limiting of the threads and without the change to `HttpClientConnectionManager` and `PoolingHttpClientConnectionManager`.  Moving to use a `PoolingHttpClientConnectionManager` for arbitrary outbound connections seems like a premature optimization and could have some unusual side effects and cause unneeded issues.  We have had no issues or complaints regarding the speed of the current closable connections and I think we should leave it as is for now.  If we were writing a dedicated client for some webservice where performance was at a premium, I would probably think differently.

2022-07-14 13:58 UTC, wezell requested changes

2022-07-14 13:58 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/http/CircuitBreakerUrl.java
> +            Logger.info(this, "The maximum number of connections has been reached, size: " + threadIdConnectionCountSet.size());
Please log the url that is trying to be accessed

2022-07-14 13:58 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/http/CircuitBreakerUrl.java
> +        threadIdConnectionCountSet.add(Thread.currentThread().getId());
Does it make sense to add the current thread in the try?

2022-07-14 13:58 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/http/CircuitBreakerUrl.java
> +        threadIdConnectionCountSet.add(Thread.currentThread().getId());
also, under load, it might be possible to exceed the `circuitBreakerMaxConnTotal` by a few.  This might be acceptable rather than syncing

2022-07-18 22:35 UTC, jdotcms commented
> I think I'd like to see this PR with only the limiting of the threads and without the change to `HttpClientConnectionManager` and `PoolingHttpClientConnectionManager`. Moving to use a `PoolingHttpClientConnectionManager` for arbitrary outbound connections seems like a premature optimization and could have some unusual side effects and cause unneeded issues. We have had no issues or complaints regarding the speed of the current closable connections and I think we should leave it as is for now. If we were writing a dedicated client for some webservice where performance was at a premium, I would probably think differently.

Agree, I have removed the customization of the pool

2022-07-26 22:23 UTC, wezell reviewed
What does this print out in velocity when there are no more connections?  Anything? 
```
$json.fetch("https://www.google.com/")

```

2022-08-16 18:30 UTC, wezell approved these changes
This looks good

2022-08-16 22:16 UTC, nollymar approved these changes

2022-08-16 22:16 UTC, merged