dotCMS/core#22488 Transform WYSIWYG field to block editor fields
dotCMS/core pull request #22713
Opened 2022-08-09 18:32 UTC by fmontes

### Proposed Changes
* Set HTML ot JSON to the block editor in `edit_field.jsp`
* Fix the `dotcms-block-editor` storybook not starting

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2022-08-19 15:15 UTC, alfredo-dotcms commented on core-web/apps/dotcms-ui/src/app/portlets/shared/dot-content-types-edit/components/dot-convert-wysiwyg-to-block/dot-convert-wysiwyg-to-block.component.html
> +<h3 id="convert" data-testId="infoHeader">
double IDs `convert`

2022-08-19 15:31 UTC, hmoreras requested changes

2022-08-19 15:31 UTC, hmoreras commented on dotCMS/src/main/webapp/html/portlet/ext/contentlet/field/edit_field.jsp
> +                console.log({json, html})
remove

2022-08-19 15:31 UTC, hmoreras commented on dotCMS/src/main/webapp/html/portlet/ext/contentlet/field/edit_field.jsp
> +                try {
add doc of why the try/cath

2022-08-19 15:53 UTC, hmoreras approved these changes

2022-08-19 15:54 UTC, alfredo-dotcms approved these changes

2022-08-23 22:14 UTC, jcastro-dotcms commented on dotCMS/src/main/webapp/html/portlet/ext/contentlet/field/edit_field.jsp
> +                try {
Done!

2022-08-23 22:19 UTC, alfredo-dotcms approved these changes

2022-08-30 21:55 UTC, nollymar approved these changes

2022-08-30 21:58 UTC, merged