Added Container List Context Menu actions and Added Service to handle them
dotCMS/core pull request #23018
Opened 2022-09-19 17:35 UTC by motasimvd

### Proposed Changes
* Added Container List Context Menu
* Added Service To Handle Context Menu Actions

### Checklist
- [x] Tests
- [x] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** Changes are WIP, Merging to canary to use dotCMS as base **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2022-09-20 15:44 UTC, rjvelazco requested changes

2022-09-21 13:32 UTC, motasimvd commented on core-web/apps/dotcms-ui/src/app/api/services/dot-containers/dot-containers.service.ts
> +}
Trying not to break the Workaround due to type mapping, this was just copied from template Service

2022-09-26 15:27 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/api/services/dot-containers/dot-containers.service.ts
> +     * Updates a template
missing param in doc

2022-09-26 15:29 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/api/services/dot-containers/dot-containers.service.ts
> +     * Unpublish a template00
00?

2022-09-26 18:34 UTC, alfredo-dotcms commented on core-web/apps/dotcms-ui/src/app/portlets/dot-containers/container-list/container-list.component.ts
> +export class ContainerListComponent {
this files and all the files in the **container-list** directory needs to have the prefix **"dot-"**

ex: DotContainerListComponent

2022-09-26 18:34 UTC, alfredo-dotcms commented on core-web/apps/dotcms-ui/src/app/portlets/dot-containers/container-list/container-list.component.ts
> +    setContainerActions(container: DotContainer): DotActionMenuItem[] {
doc?

2022-09-26 18:37 UTC, fmontes requested changes

2022-09-26 18:37 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/api/services/dot-router/dot-router.service.ts
> +            inode ? `/container-new/edit/${id}/inode/${inode}` : `/container-new/edit/${id}`
Let's replace the route to be `containers`.

Let's catch that as soon as possible.

2022-11-07 23:21 UTC, closed without merging