#23009 now can set categories on velocity on wf
dotCMS/core pull request #23010
Opened 2022-09-16 18:31 UTC by jdotcms

Now you can run this
```
#set($parentCategory = $categories.getCategoryByKey('ageOrGender'))
#set($cats= $categories.getChildrenCategories($categories.getCategoryByKey('ageOrGender')))
#set($contentDeps = $workflow.copyContentletDependenciesBuilder().categories($cats).build())
$workflow.setContentletDependencies($contentDeps))
```

To set the categories on workflow

2022-09-16 19:55 UTC, freddyucv approved these changes

2022-09-26 18:43 UTC, victoralfaro-dotcms approved these changes

2022-09-26 18:48 UTC, nollymar requested changes
This test must be included in MainSuite

2022-10-19 17:50 UTC, jdotcms commented
> This test must be included in MainSuite

Done

2022-10-24 16:21 UTC, merged