dotCMS/core#23088 System Container shows broken images when adding
dotCMS/core pull request #23145
Opened 2022-10-11 17:20 UTC by rjvelazco

**What we did here**

1. Update velocity code to display images only when needed.
2. Add a card style for the `system container` content.

**Card Style**
|  Desktop |  Responsive  |
|---|---|
|  <img width="1792" alt="desktop" src="https://user-images.githubusercontent.com/72418962/196235178-c032c7b5-0988-48c9-83fb-5f4b5e552680.png"> | <img width="1792" alt="responsive" src="https://user-images.githubusercontent.com/72418962/196235452-2db99f62-144f-4611-9b67-8ae15726782c.png"> |

**Behavior**

https://user-images.githubusercontent.com/72418962/196234798-df022580-54c3-4a4e-962b-0cfc69241bb9.mov

2022-10-17 16:55 UTC, rjvelazco commented
Hey, @wezell, I hope you are doing great!

I talked to Jason and he came up with this card style. Can you take a look to see if you like it?

<img width="1792" alt="system_container" src="https://user-images.githubusercontent.com/72418962/196237701-2f4874fa-ff27-4fb0-abc0-03ce358e11fa.png">

2022-10-18 16:12 UTC, oidacra approved these changes

2022-10-19 15:41 UTC, hmoreras requested changes

2022-10-19 15:41 UTC, hmoreras commented on dotCMS/src/main/webapp/WEB-INF/velocity/static/system_theme/template.vtl
> +.badge {
add more specificity to this classes and bellow this one.

2022-10-19 16:32 UTC, jdotcms commented on dotCMS/src/main/resources/com/dotmarketing/portlets/containers/business/default_container.vtl
> +            <span class="badge">#if($!{contentMap})$contentType.name()#{else}DRAFT#end</span>
DRAFT shouldn't be i18n

2022-10-19 16:33 UTC, jdotcms approved these changes

2022-10-20 13:25 UTC, rjvelazco commented on dotCMS/src/main/resources/com/dotmarketing/portlets/containers/business/default_container.vtl
> +            <div class="status #if($contentlet.isLive())live#{else}working#end"></div>
In this case, `live` and `working` work as `CSS` classes.

2022-10-21 22:46 UTC, hmoreras approved these changes

2022-10-24 13:30 UTC, merged