#22365  initial commit
dotCMS/core pull request #23171
Opened 2022-10-13 19:59 UTC by fabrizzio-dotCMS

THIS IS A DRAFT!!!!!

Adding CT Push Pull functionality to the CLI

2022-10-26 15:02 UTC, wezell reviewed
Please add a README.md on how to build the cli

2022-10-26 15:03 UTC, wezell commented on tools/dotcms-cli/api-data-model/src/main/java/com/dotcms/contenttype/model/type/ContentType.java
> +    public abstract int sortOrder();
not needed

2022-10-26 15:04 UTC, wezell requested changes
Please add a README.md on how to build the cli

2022-10-26 15:04 UTC, wezell commented on tools/dotcms-cli/api-data-model/src/main/java/com/dotcms/contenttype/model/type/ContentType.java
> +    public abstract Boolean versionable();
not needed

2022-10-26 15:04 UTC, wezell commented on tools/dotcms-cli/api-data-model/src/main/java/com/dotcms/contenttype/model/type/ContentType.java
> +    public abstract Boolean multilingualable();
not needed

2022-10-26 18:41 UTC, fabrizzio-dotCMS commented
> Please add a README.md on how to build the cli

done. Readme's in

2022-10-26 18:52 UTC, jdotcms approved these changes

2022-10-27 18:45 UTC, spbolton approved these changes

2022-10-27 21:44 UTC, merged