dotCMS/core#22904 Block Editor: Add char count information
dotCMS/core pull request #23198
Opened 2022-10-19 23:24 UTC by rjvelazco

2022-10-21 16:25 UTC, fmontes requested changes

2022-10-21 16:25 UTC, fmontes commented on core-web/libs/block-editor/src/lib/components/dot-block-editor/dot-block-editor.component.ts
> +        this.subject.pipe(debounceTime(250)).subscribe(() => this.updateChartCount());
takeUntil?

2022-10-21 16:30 UTC, rjvelazco commented on core-web/libs/block-editor/src/lib/components/dot-block-editor/dot-block-editor.component.ts
> +        this.subject.pipe(debounceTime(250)).subscribe(() => this.updateChartCount());
Right! Great catch!

2022-10-21 16:30 UTC, rjvelazco commented on core-web/libs/block-editor/src/lib/components/dot-block-editor/dot-block-editor.component.scss
> +        color: #868e96;
Sure!

2022-10-25 15:03 UTC, hmoreras commented on dotCMS/src/main/webapp/html/portlet/ext/contentlet/field/edit_field.jsp
> +                if("displayCountBar".equalsIgnoreCase(fv.getKey())){
add the doc needed in the card.

2022-10-25 15:08 UTC, hmoreras approved these changes

2022-10-25 19:14 UTC, fmontes approved these changes

2022-10-25 19:15 UTC, merged