#23224 making a whole copy of a page
dotCMS/core pull request #23273
Opened 2022-10-31 20:38 UTC by jdotcms

The idea is to reuse previous copy contentlet code in order to do a whole copy page

2022-10-31 20:46 UTC, jcastro-dotcms approved these changes

2022-11-02 17:35 UTC, fabrizzio-dotCMS requested changes

2022-11-02 17:35 UTC, fabrizzio-dotCMS commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResourceHelper.java
> +
I think this method requires of a test

2022-11-02 18:37 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResourceHelper.java
> +
It is already tested by the curl. test

2022-11-07 17:24 UTC, dsilvam approved these changes

2022-11-07 17:54 UTC, merged