dotCMS/core#22908 Block Editor: Add UI to configure block editor field
dotCMS/core pull request #23408
Opened 2022-11-21 20:25 UTC by rjvelazco

### Proposed Changes
* change 1
* change 2

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2022-11-29 18:02 UTC, fmontes requested changes

2022-11-29 19:23 UTC, oidacra approved these changes

2022-11-29 20:10 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/portlets/shared/dot-content-types-edit/components/dot-block-editor-settings/dot-block-editor-settings.component.spec.ts
> +        it('should have a multiselect', () => {
not needed.

2022-11-29 20:10 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/portlets/shared/dot-content-types-edit/components/dot-block-editor-settings/dot-block-editor-settings.component.ts
> +// import { getFieldVariableValue } from '.';
remove

2022-12-02 14:02 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/portlets/shared/dot-content-types-edit/components/dot-block-editor-settings/dot-block-editor-settings.component.spec.ts
> +        component.saveSettings();
instead do the click event in the accept button ?

2022-12-02 14:03 UTC, hmoreras approved these changes

2022-12-02 18:24 UTC, merged