dotCMS/core#23311 Filter forms is not working as expected
dotCMS/core pull request #23438
Opened 2022-11-25 11:55 UTC by zulqarnainvd

### Proposed Changes
* Add Content Type Search Filter

### Checklist
- [x] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2022-11-25 12:38 UTC, zulqarnainvd commented
I added an extra parameter from the front end but currently, API does not support the Content Type filter.

2022-11-28 14:36 UTC, alfredo-dotcms approved these changes

2022-11-28 16:54 UTC, rjvelazco approved these changes

2022-11-28 17:07 UTC, hmoreras approved these changes

2022-11-28 18:19 UTC, fmontes requested changes

2022-11-29 08:04 UTC, zulqarnainvd commented on core-web/apps/dotcms-ui/src/app/portlets/dot-containers/container-list/container-list.component.spec.ts
> +        expect(comp.changeBaseTypeSelector).toHaveBeenCalledWith('test');
Noted

2022-11-29 09:10 UTC, zulqarnainvd commented on core-web/apps/dotcms-ui/src/app/portlets/dot-containers/container-list/container-list.component.spec.ts
> +        expect(comp.changeBaseTypeSelector).toHaveBeenCalledWith('test');
updated

2022-11-29 09:10 UTC, zulqarnainvd commented on core-web/apps/dotcms-ui/src/app/portlets/dot-containers/container-list/container-list.component.spec.ts
> +        expect(comp.changeBaseTypeSelector).toHaveBeenCalledWith('test');
updated

2022-11-29 18:12 UTC, merged