add p-menu to the actions in the table
dotCMS/core pull request #23654
Opened 2022-12-21 23:42 UTC by hmoreras

### Proposed Changes
* The actions in the table now use `p-menu`
* Now only shows only one menu active in the table.
* gets the position above or below, depending of the space. 

### Screenshots

https://user-images.githubusercontent.com/31667212/209023851-5a6618f3-b3eb-4277-8523-3abce3d115f3.mov

2022-12-22 18:58 UTC, alfredo-dotcms approved these changes

2022-12-22 19:46 UTC, rjvelazco requested changes

2022-12-22 19:46 UTC, rjvelazco commented on core-web/apps/dotcms-ui/src/app/view/components/_common/dot-menu/dot-menu.component.ts
> -        $event.stopPropagation();
If we click on the menu, isn't the list item marked as checked?

2022-12-23 10:14 UTC, zulqarnainvd approved these changes

2022-12-26 17:29 UTC, fmontes approved these changes

2022-12-26 17:29 UTC, merged