23.01 merge to master 01 03
dotCMS/core pull request #23716
Opened 2023-01-03 19:05 UTC by victoralfaro-dotcms

2023-01-03 19:37 UTC, fmontes requested changes, later dismissed

2023-01-03 19:37 UTC, fmontes commented on .github/workflows/release-process.yml
> +      DOT_CICD_BRANCH: release-23.01
```suggestion
      DOT_CICD_BRANCH: master
```

2023-01-03 19:37 UTC, fmontes commented on .gitmodules
> +	branch = release-23.01
```suggestion
	branch = master
```

2023-01-04 01:10 UTC, victoralfaro-dotcms commented
Merging 23.01 to master

2023-01-04 01:10 UTC, merged