dotCMS/core#23557 Add container code to advanced template is broken
dotCMS/core pull request #23743
Opened 2023-01-05 22:06 UTC by hmoreras

### Proposed Changes
* Fix reference of the monaco editor in advanced template.

2023-01-05 22:09 UTC, fmontes requested changes

2023-01-05 22:09 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/view/components/_common/dot-textarea-content/dot-textarea-content.component.spec.ts
> +    fit('should init editor with the correct value', () => {
remove fit.

2023-01-05 22:09 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/portlets/dot-templates/dot-template-create-edit/dot-template-advanced/dot-template-advanced.component.ts
> +     * @param {*} editorInfo
Fix the param.

2023-01-06 14:38 UTC, zulqarnainvd approved these changes

2023-01-06 16:36 UTC, merged