Fix for filtering images on image selector
dotCMS/core pull request #24048
Opened 2023-02-06 23:12 UTC by hassan-mustafa-baig

### Proposed Changes
* Image filtering has been fixed for image selector

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:

![image](https://user-images.githubusercontent.com/111717530/217108325-6775363e-35a1-4a76-ad94-81b9e208552c.png)

![image](https://user-images.githubusercontent.com/111717530/217108345-862bdb22-16b0-4713-be7b-c4fd93b00b91.png)

![image](https://user-images.githubusercontent.com/111717530/217108363-5621d4cc-029e-4ab0-9a61-e9fd375ccf5f.png)

2023-02-07 14:09 UTC, jcastro-dotcms requested changes

2023-02-07 14:52 UTC, hassan-mustafa-baig commented on dotCMS/src/main/java/com/dotmarketing/portlets/browser/ajax/BrowserAjax.java
>  						   .showMimeTypes(mimeTypes)
we need to check image specifically therefore specific method is created for image

2023-02-07 15:35 UTC, jcastro-dotcms requested changes

2023-02-07 15:35 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/browser/ajax/BrowserAjax.java
>  						   .showMimeTypes(mimeTypes)
But this MIME Type should come from the JS or JSP instead, shouldn't it?

2023-02-09 16:21 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/browser/BrowserQuery.java
> +        public Builder showImages(@Nonnull List<String> mimeTypes) {
show methods used to receive a boolean, such as 
```

        public Builder showImages(boolean showImages) {
        ```

The responsability of the calculation of the boolean should be outside of the showImages method

2023-02-14 16:20 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/browser/BrowserAPIImpl.java
> +            final String[] spliter = filterText.split(" ");
shouldn't sanitize it, if it is not already sanitized

2023-02-14 16:39 UTC, jcastro-dotcms approved these changes

2023-02-15 14:45 UTC, jdotcms approved these changes

2023-02-15 15:18 UTC, merged