Updating Stalebot Criteria
dotCMS/core pull request #24043
Opened 2023-02-06 17:09 UTC by damen-dotcms

Updating it so that issues won't go stale once an OKR has been assigned to it. I'll work to get each stakeholder OK with having their requests go stale, but right now trying to fix the issue "I put things in GitHub and they just get closed."

### Proposed Changes
* change 1
* change 2

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2023-02-06 17:28 UTC, wezell reviewed
I fear this change will effectively make stalebot useless.

2023-02-15 22:42 UTC, damen-dotcms reviewed
@wezell Updated based on discussion.

2023-02-16 02:55 UTC, wezell requested changes
Exempt Defects?  I have the same pushback here.

2023-02-23 20:43 UTC, jdotcms approved these changes

2023-04-03 01:52 UTC, closed without merging