dotCMS/core#22988 Change Traffic Load of experiment
dotCMS/core pull request #24053
Opened 2023-02-08 16:41 UTC by hmoreras

### Proposed Changes
* Adding traffic allocation to experiments. 

https://user-images.githubusercontent.com/31667212/217594416-6b231aa6-7add-4f4e-b216-ca5b5e3aa323.mov

2023-02-08 16:49 UTC, alfredo-dotcms commented on core-web/libs/dot-primeng-theme-styles/src/scss/dotcms-theme/components/_slider.scss
> +    transition: background-color 0.2s, color 0.2s, border-color 0.2s, box-shadow 0.2s, bottom 0.2s;
var to DRY?

2023-02-08 16:50 UTC, alfredo-dotcms commented on core-web/apps/dotcms-ui/src/app/portlets/dot-experiments/shared/services/dot-experiments.service.ts
> +     * @param {string} trafficAllocation
fix doc

2023-02-08 20:38 UTC, hmoreras commented on core-web/libs/dot-primeng-theme-styles/src/scss/dotcms-theme/components/_slider.scss
> +    transition: background-color 0.2s, color 0.2s, border-color 0.2s, box-shadow 0.2s, bottom 0.2s;
done

2023-02-08 20:38 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/portlets/dot-experiments/shared/services/dot-experiments.service.ts
> +     * @param {string} trafficAllocation
done

2023-02-10 15:38 UTC, oidacra requested changes

2023-02-10 15:38 UTC, oidacra commented on core-web/apps/dotcms-ui/src/app/portlets/dot-experiments/dot-experiments-configuration/components/dot-experiments-configuration-traffic-allocation-add/dot-experiments-configuration-traffic-allocation-add.component.scss
> +form input[type="number"] {
Please add   text-align: center;

2023-02-10 16:23 UTC, oidacra approved these changes

2023-02-10 16:42 UTC, alfredo-dotcms approved these changes

2023-02-10 17:49 UTC, merged