dotCMS#23623 Experiment Split Traffic
dotCMS/core pull request #24113
Opened 2023-02-14 23:57 UTC by hmoreras

### Proposed Changes
* Allow to change the split traffic over the different variants 

https://user-images.githubusercontent.com/31667212/218890214-e2884aad-aaf0-4f28-b9b0-4f222a4776a2.mov

2023-02-15 15:49 UTC, oidacra commented on core-web/apps/dotcms-ui/src/app/portlets/dot-experiments/dot-experiments-configuration/components/dot-experiments-configuration-traffic-split-add/dot-experiments-configuration-traffic-split-add.component.html
> +                        value="SPLIT_EVENLY"
Use the constant Enum

2023-02-15 15:49 UTC, oidacra commented on core-web/apps/dotcms-ui/src/app/portlets/dot-experiments/dot-experiments-configuration/components/dot-experiments-configuration-traffic-split-add/dot-experiments-configuration-traffic-split-add.component.html
> +                        value="CUSTOM_PERCENTAGES"
Same.

2023-02-15 15:49 UTC, oidacra commented on core-web/apps/dotcms-ui/src/app/portlets/dot-experiments/dot-experiments-configuration/components/dot-experiments-configuration-traffic-split-add/dot-experiments-configuration-traffic-split-add.component.html
> +                                *ngIf="form.value.type === 'CUSTOM_PERCENTAGES'; else splitEven"
Use the constant

2023-02-15 16:04 UTC, alfredo-dotcms commented on core-web/apps/dotcms-ui/src/app/portlets/dot-experiments/dot-experiments-configuration/components/dot-experiments-configuration-traffic/dot-experiments-configuration-traffic.component.ts
>      changeTrafficAllocation() {
doc

2023-02-16 20:04 UTC, fmontes requested changes, later dismissed

2023-02-23 20:46 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/portlets/dot-experiments/dot-experiments-configuration/components/dot-experiments-configuration-traffic-split-add/dot-experiments-configuration-traffic-split-add.component.html
> +                        value="SPLIT_EVENLY"
done

2023-02-23 20:54 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/portlets/dot-experiments/dot-experiments-configuration/components/dot-experiments-configuration-traffic-split-add/dot-experiments-configuration-traffic-split-add.component.spec.ts
> +    });
a message handled in the store.

2023-02-23 21:01 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/portlets/dot-experiments/dot-experiments-configuration/components/dot-experiments-configuration-traffic-split-add/dot-experiments-configuration-traffic-split-add.component.ts
> +        });
just once, to init de form.

2023-02-23 21:34 UTC, alfredo-dotcms approved these changes

2023-02-24 20:30 UTC, oidacra approved these changes

2023-02-24 21:28 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/portlets/dot-experiments/dot-experiments-configuration/components/dot-experiments-configuration-traffic-split-add/dot-experiments-configuration-traffic-split-add.component.spec.ts
> +    });
Ok, make sure you check that in the store.

2023-02-27 21:18 UTC, merged