[Issue-24032]: block editor allow users to add options to the suggestion menu
dotCMS/core pull request #24141
Opened 2023-02-16 20:06 UTC by manuelrojas

### Proposed Changes
* Adding the ability include options in the suggestions menu
* Refactor part of the code to being able to add options in suggestions menu

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info

Implemented using the following JSON file:
```
{
	"extensions": [{
		"url": "http://localhost:8080/application/customBlocks.js",
		"actions": [{
			"name": "CustomExtension",
			"command": "insertProduct",
			"menuLabel": "Custom Extension",
			"icon": "javascript"
		}, {
			"name": "HighlightCustom",
			"command": "toggleHighlight",
			"menuLabel": "Highlight Custom",
			"icon": "highlight"
		}, {
			"name": "CustomNode",
			"command": "addHelloWorld",
			"menuLabel": "Custom Node",
			"icon": "javascript"
		}]
	}]
}
```

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  <img width="1602" alt="image" src="https://user-images.githubusercontent.com/3438705/219474099-3269eea2-a702-415f-98c0-db9f1cda80a4.png">

![Feb-16-2023 14-11-21](https://user-images.githubusercontent.com/3438705/219477338-7c55fd87-6551-4f97-8818-8f4310f90c68.gif)

2023-02-16 21:11 UTC, fmontes requested changes

2023-02-16 21:11 UTC, fmontes commented on core-web/libs/block-editor/src/lib/components/dot-block-editor/dot-block-editor.component.ts
> +            console.warn('JSON parse fails, please check the JSON format.');
Print the error in the console.

2023-02-16 21:11 UTC, fmontes commented on core-web/libs/block-editor/src/lib/extensions/action-button/actions-menu.extension.ts
> +                console.warn('Custom command does not exists.');
```suggestion
                console.warn(`Custom command ${option.commandKey} does not exists.`);
```

2023-02-16 21:11 UTC, fmontes commented on core-web/libs/block-editor/src/lib/extensions/action-button/actions-menu.extension.ts
> +import { CustomBlock } from '@dotcms/dotcms-models';
I think the name should be more like: "RemoteCustomExtentions" or something very clear.

2023-02-16 21:11 UTC, fmontes commented on core-web/libs/block-editor/src/lib/extensions/action-button/actions-menu.extension.ts
> +        suggestionsComponent.instance.items = [...items, ...[]];
What is the `...[]` for?

2023-02-16 21:11 UTC, fmontes commented on core-web/libs/block-editor/src/lib/components/dot-block-editor/dot-block-editor.component.ts
> +            .subscribe((blocks) => {
```suggestion
            .subscribe((extensions) => {
```

2023-02-16 21:11 UTC, fmontes commented on core-web/libs/block-editor/src/lib/extensions/action-button/actions-menu.extension.ts
> +        id: action.name
Do we have types for this?

2023-02-17 15:21 UTC, rjvelazco approved these changes

2023-02-21 20:11 UTC, fmontes requested changes

2023-02-21 20:11 UTC, fmontes commented on core-web/libs/block-editor/src/lib/components/dot-block-editor/dot-block-editor.component.ts
> +            console.warn('JSON parse fails, please check the JSON format.');
We can have just the warn:

```
console.warn('JSON parse fails, please check the JSON format.', e);
```

2023-02-21 20:11 UTC, fmontes commented on core-web/libs/block-editor/src/lib/components/dot-block-editor/dot-block-editor.component.ts
> +
Use this extension which provides a more structured doc: https://marketplace.visualstudio.com/items?itemName=oouo-diogo-perdigao.docthis

2023-02-21 20:11 UTC, fmontes commented on core-web/libs/block-editor/src/lib/extensions/action-button/actions-menu.extension.ts
> +        id: action.name
Do we have a type of the `actions`?

2023-02-21 20:11 UTC, fmontes commented on core-web/libs/block-editor/src/lib/extensions/action-button/actions-menu.extension.ts
> +    return flatten(customBlocks.extensions.map((extension) => mapCustomActions(extension.actions)));
I don't think we need lodash anymore: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

Also, not sure if lodash has tree shaking in newer version, it used to be a problem back in the days.

2023-02-21 20:11 UTC, fmontes commented on core-web/libs/block-editor/src/lib/extensions/action-button/actions-menu.extension.ts
> +        suggestionsComponent.instance.items = [...items];
If I am not mistaken, you are creating a new array but the internal objects will have the same ref.

2023-02-21 20:11 UTC, fmontes commented on core-web/libs/block-editor/src/lib/shared/components/suggestions/suggestions.component.ts
> +    @Input() onSelectContentlet: (props: SuggestionsCommandProps) => void;
We don't  select contentlets all the time, it could also be other blocks no?

2023-02-22 20:32 UTC, merged