Added a support to show children categories count through the getById Rest API
dotCMS/core pull request #24140
Opened 2023-02-16 17:48 UTC by hassan-mustafa-baig

### Proposed Changes
* A rest API upgraded to accept showChildrenCount parameter. Upon providing **showChildrenCount=true** it will expose child categories count in the API response that will be visible in the **childrenCount** property but in case of **showChildrenCount=false** the property **childrenCount** will be excluded from the Rest API response

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:

![image](https://user-images.githubusercontent.com/111717530/219446297-3fd8a891-d993-4864-be0f-5cfb70efff5e.png)

![image](https://user-images.githubusercontent.com/111717530/219446342-f323f1e7-ab04-433d-96b7-d75544e3976f.png)

2023-02-16 17:53 UTC, jcastro-dotcms requested changes

2023-02-16 17:53 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/categories/CategoryHelper.java
> +    public Response toCategoryWithChildCountView(final Category category, final User user) throws DotDataException, DotSecurityException {
Missing Javadoc

2023-02-16 17:53 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/categories/CategoryWithChildCountView.java
> +public class CategoryWithChildCountView {
Missing Javadoc

2023-02-16 17:53 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/categories/CategoryHelper.java
> +        return Response.ok(new ResponseEntityView(categoryView)).build();
you need to use a sub class if use Response as a return type, so swagger may do the doc

2023-02-16 17:55 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/categories/CategoryHelper.java
> +                    false, "").size();
Use StringPool.BLANK

2023-02-16 17:55 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/categories/CategoryHelper.java
> +        return Response.ok(new ResponseEntityView(categoryWithChildCountView)).build();
Same here

2023-02-17 17:26 UTC, jcastro-dotcms approved these changes

2023-02-21 14:45 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/categories/CategoriesResource.java
> +        return showChildrenCount ? Response.ok(new ResponseEntityView(this.categoryHelper.toCategoryWithChildCountView(category, user))).build() :
still the same, need to use ResponseEntityView<> at least

2023-02-22 15:06 UTC, jdotcms approved these changes

2023-02-22 20:40 UTC, merged