Fix for searching dotAsset through image picker filter
dotCMS/core pull request #24192
Opened 2023-02-23 13:08 UTC by hassan-mustafa-baig

### Proposed Changes
* This fix will allow user to search both image and dotAsset through image picker filter

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

![image](https://user-images.githubusercontent.com/111717530/220915088-8a5f40d9-eb2d-43d2-b328-687c04e5ddef.png)

![image](https://user-images.githubusercontent.com/111717530/220915132-3905f359-0ff6-459f-ae4e-1117e67a22cb.png)

![image](https://user-images.githubusercontent.com/111717530/220915166-296fc0a9-149b-4fa5-b35e-02b1ba66d765.png)

2023-02-23 15:28 UTC, jcastro-dotcms approved these changes

2023-02-23 16:16 UTC, jdotcms reviewed
missing unit test for both db's

2023-02-27 02:58 UTC, hassan-mustafa-baig commented
> missing unit test for both db's

it has been addressed as two unit tests have been written please review - thanks

2023-02-27 16:21 UTC, jdotcms approved these changes

2023-02-27 18:29 UTC, nollymar requested changes
BrowserAPIImplTest.java seems to be an integration test because it requires a DB connection. Please move it to the integration-test package and add it at the end of the MainSuite class

2023-03-01 02:51 UTC, merged