#23847 Add configuration to Reach Page type Goal
dotCMS/core pull request #24196
Opened 2023-02-23 20:11 UTC by oidacra

### Proposed Changes
* Add the ability for the user to configure Reach Page (Define Name, y Conditions)

### Checklist
- [x] Tests
- [x] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
Reuse the sidebar 

### Screenshots
Original    
![old-set-goal](https://user-images.githubusercontent.com/1909643/221018564-510a37f3-7777-431a-a271-a4ff65d94190.gif)

New config
![new-set-goal](https://user-images.githubusercontent.com/1909643/221019166-64c1c101-401a-415a-91e2-c80b2003037d.gif)

2023-02-23 22:46 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/portlets/dot-experiments/dot-experiments-configuration/components/dot-experiments-configuration-goal-select/dot-experiments-configuration-goal-select.component.spec.ts
> +    it('should call saveForm() when a item is selected and the button of apply is valid', () => {
better, should call setSelectedGoal....

2023-02-23 22:48 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/portlets/dot-experiments/dot-experiments-configuration/components/dot-experiments-configuration-goal-select/dot-experiments-configuration-goal-select.component.ts
> +     */
missing, `memberof`

2023-02-24 15:35 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/portlets/dot-experiments/dot-experiments-configuration/components/dot-experiments-configuration-goal-select/dot-experiments-configuration-goal-select.component.ts
> +     */
Use https://marketplace.visualstudio.com/items?itemName=oouo-diogo-perdigao.docthis

2023-02-24 16:22 UTC, fmontes requested changes, later dismissed

2023-02-24 16:22 UTC, fmontes commented on core-web/libs/dot-primeng-theme-styles/src/scss/_variables.scss
> +$font-weight-bold: 700;
This is getting out of hand... I will check with Melissa to unify this.

2023-02-24 16:53 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/portlets/dot-experiments/shared/ui/dot-experiment-options/dot-experiment-options.component.ts
> +    /**
fix documentation missing `memberof`

2023-02-24 17:21 UTC, oidacra commented on core-web/apps/dotcms-ui/src/app/test/dot-message-mock.pipe.ts
> +export class DotMessagePipe implements PipeTransform {
The IDE when I try lo import show me this.

2023-02-24 19:04 UTC, rjvelazco approved these changes

2023-02-24 19:04 UTC, rjvelazco commented on core-web/apps/dotcms-ui/src/app/portlets/dot-experiments/shared/ui/dot-experiment-options/directives/dot-experiment-option-content.directive.ts
> +}
What is the goal of this `directive`? I know this directive is being used in an `ng-template`. However, I don't know where the `templateRef` is being used.

2023-02-27 21:52 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/portlets/dot-experiments/dot-experiments-configuration/components/dot-experiments-configuration-scheduling/dot-experiments-configuration-scheduling.component.spec.ts
> +    xit('should render the date range in the button when present', () => {
it's ok.. for the others, we need to mock `new Date()` here. Will do it on other PR.

2023-02-27 21:53 UTC, hmoreras approved these changes

2023-02-28 16:29 UTC, merged