dotCMS/core#24173 Create dialog for 'Create Page' button
dotCMS/core pull request #24215
Opened 2023-02-24 22:47 UTC by alfredo-dotcms

### Proposed Changes
* change 1
* change 2

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2023-02-27 23:24 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-pages-create-page-dialog/dot-pages-create-page-dialog.component.html
> +<div class="dot-pages-create-page-dialog__page-types-container" *ngIf="vm$ | async as vm">
why no the `ngif` in all html ?

2023-02-27 23:31 UTC, hmoreras approved these changes

2023-02-28 08:06 UTC, zulqarnainvd approved these changes

2023-03-01 21:03 UTC, fmontes requested changes
.

2023-03-01 21:03 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-pages.component.ts
> +            width: '800px'
Use rems.

2023-03-03 22:36 UTC, alfredo-dotcms commented on core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-pages-create-page-dialog/dot-pages-create-page-dialog.component.spec.ts
> +            de.query(By.css(`.dot-pages-create-page-dialog__search-container dot-icon`))
fixed!

2023-03-03 22:36 UTC, alfredo-dotcms commented on core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-pages.component.ts
> +            width: '800px'
fixed!

2023-03-03 22:36 UTC, alfredo-dotcms commented on core-web/libs/data-access/src/lib/dot-es-content/dot-es-content.service.spec.ts
> +            '{"query":"+contentType: blog   ","sort":"modDate DESC","limit":40,"offset":"0"}'
fixed!

2023-03-03 22:37 UTC, alfredo-dotcms commented on core-web/libs/data-access/src/lib/dot-page-types/dot-page-types.service.ts
> +     * Get the value of specific key
fixed!

2023-03-03 22:37 UTC, alfredo-dotcms commented on core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-pages.module.ts
> +        DotPageStore
reverted!

2023-03-03 22:38 UTC, alfredo-dotcms commented on core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-pages-create-page-dialog/dot-pages-create-page-dialog.component.ts
> +        private store: DotPageStore,
fixed, store removed and `DotPagesCreatePageDialogComponent` is a dummy components that gets data from inputs

2023-03-06 16:34 UTC, fmontes requested changes
Couple of comments.

2023-03-06 17:17 UTC, fmontes approved these changes

2023-03-06 21:06 UTC, alfredo-dotcms commented on core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-pages-listing-panel/dot-pages-listing-panel.component.ts
> +    @Output() createPage = new EventEmitter();
fixed

2023-03-06 21:06 UTC, alfredo-dotcms commented on core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-pages-create-page-dialog/dot-pages-create-page-dialog.component.ts
> +            });
fixed

2023-03-06 22:15 UTC, merged