Merging release-23.03 into master
dotCMS/core pull request #24211
Opened 2023-02-24 18:00 UTC by jcastro-dotcms

### Proposed Changes
* Merging release-23.03 into master

2023-02-24 18:10 UTC, fmontes requested changes

2023-02-24 18:10 UTC, fmontes commented on .github/workflows/release-process.yml
> +      DOT_CICD_BRANCH: release-23.03
```suggestion
      DOT_CICD_BRANCH: master
```

2023-02-24 18:10 UTC, fmontes commented on .gitmodules
> +	branch = release-23.03
```suggestion
	branch = master

2023-02-24 18:10 UTC, fmontes commented on core-web/package.json
> +  "version": "23.3.0-rc.23",
```suggestion
  "version": "23.3.0-next.16",
```

2023-02-24 18:10 UTC, fmontes commented on dotCMS/gradle.properties
> +webComponentsReleaseVersion=rc
```suggestion
dotcmsReleaseVersion=master
coreWebReleaseVersion=next
webComponentsReleaseVersion=next
```

2023-02-24 20:07 UTC, jdotcms approved these changes

2023-02-27 23:34 UTC, fmontes approved these changes

2023-02-28 13:22 UTC, merged