dotCMS/core#24219 fix redirect from pages listing is not considering languageId
dotCMS/core pull request #24232
Opened 2023-02-28 18:35 UTC by alfredo-dotcms

### Proposed Changes
* change 1
* change 2

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2023-02-28 19:41 UTC, oidacra approved these changes

2023-03-01 21:13 UTC, fmontes requested changes
.

2023-03-02 14:35 UTC, hmoreras approved these changes

2023-03-02 17:17 UTC, alfredo-dotcms commented on core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-pages-listing-panel/dot-pages-listing-panel.component.ts
> +        }&device_inode=`;
@fmontes yes, othewise EDIT MODE will display the previous device shown, and it needs to be Desktop by default

2023-03-27 13:27 UTC, fmontes requested changes
N/A

2023-03-27 13:32 UTC, zJaaal approved these changes

2023-04-05 19:30 UTC, damen-dotcms commented
I think desktop by default is fine. Good to move the device and language variables to the URL, but we don't need to save those as session variables. Someone edits one page, then edits another... the 2nd page would just start with "default" screen sizes and languages.

2023-04-10 16:38 UTC, fmontes approved these changes

2023-04-12 01:20 UTC, merged