Allowed ContentletRelationships type to be copied for contentlet
dotCMS/core pull request #24284
Opened 2023-03-06 18:25 UTC by hassan-mustafa-baig

### Proposed Changes
* Fix to allow workflow action API to create relationship

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2023-03-06 18:46 UTC, jdotcms approved these changes

2023-03-06 18:46 UTC, jcastro-dotcms approved these changes

2023-03-09 19:55 UTC, nollymar requested changes
Ideally, this change should have a test case in the ESContentletAPIImplTest and the postman test implemented should describe the real case fixed, especially because this is an issue caught by a customer.

2023-03-22 19:52 UTC, erickgonzalez requested changes

2023-03-22 19:52 UTC, erickgonzalez commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/workflows/business/WorkflowAPITest.java
> +
If this is intended to be commented, let's removed

2023-04-03 19:56 UTC, jdotcms commented
> Ideally, this change should have a test case in the ESContentletAPIImplTest and the postman test implemented should describe the real case fixed, especially because this is an issue caught by a customer.

Hi @nollymar not sure what you mean about real case, Hassan has created a post man test that does exactly that the issue described:
1) create a couple content types
2) Related between them
3) Create the instances
4) ask for the relationship

Regarding the Integration test @nollymar and @erickgonzalez, I am not sure why it is commented but I will take a look

2023-04-04 19:20 UTC, nollymar approved these changes

2023-07-18 16:11 UTC, fmontes commented
we need to fix this and merge with master

2023-08-23 20:29 UTC, merged