Issue 23058 listing favorite pages not refreshing after saved
dotCMS/core pull request #24335
Opened 2023-03-09 20:41 UTC by alfredo-dotcms

### Proposed Changes
* fix listing favorite pages not refreshing after saved
* fix actions in context menu not matching same order from Content Search

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2023-03-09 20:42 UTC, alfredo-dotcms commented on core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-pages-store/dot-pages.store.ts
fix actions in context menu not matching same order from Content Search

2023-03-13 17:21 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-pages-store/dot-pages.store.ts
> +        let currentPages = this.get().pages.items;
Can you sent this from UI?

2023-03-13 17:23 UTC, fmontes requested changes

2023-03-13 17:23 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-pages-store/dot-pages.store.ts
> +        let currentPages = this.get().pages.items;
Can you pass this from UI?

2023-03-13 17:23 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/view/components/dot-contentlet-editor/components/dot-contentlet-wrapper/dot-contentlet-wrapper.component.ts
> +                        retryLoading: true
When don't we need this?

2023-03-15 16:54 UTC, closed without merging