dotCMS/core#23681 Let's show the whole path when select a folder in the host selector
dotCMS/core pull request #24364
Opened 2023-03-14 11:43 UTC by zulqarnainvd

### Proposed Changes
* show full path on host selector field

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **
![image](https://user-images.githubusercontent.com/113915849/224990248-56a20b0f-9e24-418a-81c7-a81b644550f7.png)|![image](https://user-images.githubusercontent.com/113915849/224990148-5e312ebe-69b2-4662-b8ce-ea4f2d15ca48.png)

2023-03-14 17:45 UTC, wezell commented
@zulqarnainvd This does not work as expected.  It only shows the parent folder and not the full path. Look at a file asset on starter under `/images/gallery/beach`

2023-03-15 07:04 UTC, zulqarnainvd commented
> @zulqarnainvd This does not work as expected. It only shows the parent folder and not the full path. Look at a file asset on starter under `/images/gallery/beach`

Noted, let me check

2023-03-15 13:13 UTC, fmontes requested changes

2023-03-15 13:13 UTC, fmontes commented on dotCMS/src/main/webapp/html/css/dijit-dotcms/dotcms.css
> +  width: 100%;
Can you make it, not but around 50%?

2023-03-15 13:20 UTC, zulqarnainvd commented on dotCMS/src/main/webapp/html/css/dijit-dotcms/dotcms.css
> +  width: 100%;
Noted

2023-03-15 13:20 UTC, zulqarnainvd commented on core-web/libs/dojo-theme/scss/backend/_dojo.scss
> +        width: 100%;
Noted

2023-03-22 10:01 UTC, zulqarnainvd commented
![image](https://user-images.githubusercontent.com/113915849/226867179-1ff17024-f416-4ae0-bc38-99f54c304ecb.png)

Also need to add `parentPath` on this function `findHostFolder` because in edit mode it is not returning the `parentPath`
@fmontes

2023-03-28 17:06 UTC, closed without merging