[Issue 23687] block editor lets show the + button all the time
dotCMS/core pull request #24453
Opened 2023-03-23 04:00 UTC by manuelrojas

### Proposed Changes
*  Let's keep the + button on empty block

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  
<img width="1823" alt="image" src="https://user-images.githubusercontent.com/3438705/227099406-3173c150-7b8f-44fd-8176-6db5ed72dd53.png">

2023-03-27 13:28 UTC, zJaaal approved these changes

2023-03-27 13:35 UTC, fmontes requested changes

2023-03-27 13:35 UTC, fmontes commented on core-web/libs/block-editor/src/lib/shared/plugins/floating.plugin.ts
> +        }, 1000);
What is this TO doing? why is so high?

2023-03-29 19:19 UTC, rjvelazco requested changes

2023-03-29 19:19 UTC, rjvelazco commented on core-web/libs/block-editor/src/lib/shared/plugins/floating.plugin.ts
> +        console.log('selection', selection);
Remove `console.log`

2023-03-29 19:21 UTC, rjvelazco approved these changes

2023-03-29 20:17 UTC, merged