#18123 Adding deps on page render
dotCMS/core pull request #24520
Opened 2023-03-30 06:05 UTC by jdotcms

On page render now we return the dependencies when the field is a relationship

2023-03-31 20:46 UTC, jcastro-dotcms requested changes

2023-03-31 20:46 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotcms/rendering/velocity/services/PageRenderUtil.java
> +                    Logger.error(this, e.getMessage(), e);
Let's add the Contentlet ID to the error message and/or any other important info

2023-04-06 20:41 UTC, nollymar requested changes
The new postman tests are broken

2023-05-03 17:24 UTC, jcastro-dotcms approved these changes

2023-05-03 20:24 UTC, nollymar approved these changes

2023-05-04 21:01 UTC, merged