dotCMS/core#24583 When you click Edit go straight to EDIT in Edit Page.
dotCMS/core pull request #24589
Opened 2023-04-10 22:40 UTC by hmoreras

### Proposed Changes
* Allow "deeplink" with the edit mode tabs.
* The configuration screen in experiments the edit button in each variant show load the edit mode in the edit tab
* remove `editPageTab ` and `EditPageTabs ` since we already have `mode` and `DotPageMode `

2023-04-11 14:21 UTC, oidacra approved these changes

2023-04-11 18:41 UTC, fmontes requested changes

2023-04-11 18:41 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/shared/services/dot-edit-page-resolver/dot-edit-page-resolver.service.ts
> +    }
This is hard to read, I suggest keep it simple:

```suggestion
private getDotPageRenderOptions(route: ActivatedRouteSnapshot): DotPageRenderOptions {
    const queryParams = route.queryParams;
    const options: DotPageRenderOptions = {
        url: queryParams.url,
    };
    if (queryParams.mode) {
        options.mode = queryParams.mode;
    }
    if (queryParams.language_id) {
        options.viewAs = {
            language: queryParams.language_id
        };
    }
    return options;
}
```

2023-04-11 19:32 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/portlets/dot-experiments/dot-experiments-list/dot-experiments-list.component.ts
> +                mode: null,
to clean the URL when landing to reports, that params can trigger a specific state in experiments.

2023-04-12 19:23 UTC, fmontes approved these changes

2023-04-12 21:52 UTC, merged