Merge 23.05 into master 04.20.23
dotCMS/core pull request #24707
Opened 2023-04-20 17:32 UTC by dsilvam

Merge release 23.05 into master

2023-04-20 17:40 UTC, jdotcms approved these changes

2023-04-20 18:51 UTC, zJaaal approved these changes

2023-04-21 14:21 UTC, rjvelazco requested changes
Frontend checks are failing. Some imports are missing, I asked Alfredo to take a look.

https://github.com/dotCMS/core/actions/runs/4759004298/jobs/8457754589?pr=24707

2023-04-21 16:04 UTC, erickgonzalez commented
Tests didn't run, maybe because of issues with FE??

2023-04-21 17:00 UTC, rjvelazco approved these changes

2023-04-21 19:43 UTC, merged