#23528: caching running experiments when job runs
dotCMS/core pull request #24701
Opened 2023-04-20 01:32 UTC by victoralfaro-dotcms

### Proposed Changes
Caching running experiments when starting scheduled experiments.

2023-04-20 14:57 UTC, dsilvam approved these changes

2023-04-20 14:57 UTC, freddyucv requested changes
any test?

2023-04-21 15:13 UTC, freddyucv approved these changes

2023-04-25 04:25 UTC, merged

2023-04-25 20:09 UTC, victoralfaro-dotcms commented
PR: https://github.com/dotCMS/core/pull/24701