#24801 adding a fix to handle content type permission inheritance
dotCMS/core pull request #24813
Opened 2023-05-02 22:05 UTC by jdotcms

The idea is when the user does not have permission over the contentlet, check if the content type has permissions

2023-05-03 18:28 UTC, AndreyDotcms approved these changes

2023-05-05 21:02 UTC, freddyucv requested changes

2023-05-05 21:02 UTC, freddyucv commented on dotCMS/src/integration-test/java/com/dotmarketing/portlets/workflows/business/WorkflowAPITest.java
> +    @Test()
doc

2023-05-05 21:04 UTC, freddyucv reviewed
Also you have this test failing

[ExperimentAPIImpIT](https://raw.githack.com/dotCMS/test-results/issue-24801-permissions_72b0427e/projects/core/integration/postgres/reports/html/classes/com.dotcms.experiments.business.ExperimentAPIImpIT.html). [testStartExperiment_shouldPublishContent](https://raw.githack.com/dotCMS/test-results/issue-24801-permissions_72b0427e/projects/core/integration/postgres/reports/html/classes/com.dotcms.experiments.business.ExperimentAPIImpIT.html#testStartExperiment_shouldPublishContent)

it is very weird, maybe is it  a blinker?

2023-05-07 23:04 UTC, jdotcms commented
> Also you have this test failing
> 
> [ExperimentAPIImpIT](https://raw.githack.com/dotCMS/test-results/issue-24801-permissions_72b0427e/projects/core/integration/postgres/reports/html/classes/com.dotcms.experiments.business.ExperimentAPIImpIT.html). [testStartExperiment_shouldPublishContent](https://raw.githack.com/dotCMS/test-results/issue-24801-permissions_72b0427e/projects/core/integration/postgres/reports/html/classes/com.dotcms.experiments.business.ExperimentAPIImpIT.html#testStartExperiment_shouldPublishContent)
> 
> it is very weird, maybe is it a blinker?

it is failing locally
```
Only RUNNING experiments can be ended
com.dotmarketing.business.DotStateException: Only RUNNING experiments can be ended
```

I think the test is not idempotent

2023-05-08 15:48 UTC, erickgonzalez approved these changes

2023-05-08 15:55 UTC, dsilvam commented on dotCMS/src/main/java/com/dotmarketing/business/PermissionBitAPIImpl.java
> +			if(!checkIfContentletTypeHasEditPermissions(permissionable, user)) {
I would rename to `doesContentTypeHaveEditPermissions()`

2023-05-08 15:55 UTC, dsilvam approved these changes

2023-05-08 18:07 UTC, merged