#18123 adding the ability to add children relationships to the urlmap…
dotCMS/core pull request #24939
Opened 2023-05-15 19:02 UTC by jdotcms

Adding the same scenario of depth but for the UrlContentMap

A minor refactor has been done in order to reuse the PageRenderUtil add relationship logic into the Page View Serializer, the idea will be to pull the relationship when the contentlet is a urlmap there reusing the same previous logic

2023-05-15 21:24 UTC, nollymar requested changes
Some postman tests are failing and probably it is related to changes in the expected response (ContentResource, ContentResourceV1 and WorkflowResource)

2023-05-15 22:53 UTC, fabrizzio-dotCMS approved these changes

2023-05-24 22:06 UTC, jdotcms commented
> Some postman tests are failing and probably it is related to changes in the expected response (ContentResource, ContentResourceV1 and WorkflowResource)

The fails are the same of release-23.06

2023-05-24 22:09 UTC, nollymar approved these changes

2023-05-24 22:10 UTC, merged