#24980 adding just a minor change to hide dot fav on content search
dotCMS/core pull request #24989
Opened 2023-05-19 02:13 UTC by jdotcms

Now system types are not showed up on content search

2023-05-25 13:30 UTC, jcastro-dotcms approved these changes

2023-05-26 20:47 UTC, nollymar requested changes

2023-05-26 20:47 UTC, nollymar commented on dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/ajax/ContentletAjax.java
> +			luceneQuery.append("+" + ESMappingConstants.SYSTEM_TYPE + ":false ");
I think you need to add a whitespace after this query sentence, otherwise the following appends will be broken

2023-05-26 20:48 UTC, nollymar approved these changes

2023-05-30 17:48 UTC, merged