Fix #24801 Adding a fix to handle content type permission inheritance…
dotCMS/core pull request #24997
Opened 2023-05-19 22:00 UTC by jdotcms

Trying to migrate the issue-24801-allow-wf-rest-publish-limiteduser to 23.06

2023-05-24 21:19 UTC, jcastro-dotcms requested changes

2023-05-24 21:19 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/user/UserResource.java
> +		throw new ForbiddenException("User does not have permissions to create users");
Let's add the User ID to the error msg.

2023-05-24 21:19 UTC, jcastro-dotcms commented on dotCMS/src/main/webapp/html/portlet/ext/common/edit_permissions_tab_js_inc.jsp
> +			//role["add-children-permission-style"] = 'display: none'
Lets' get rid of this commented code.

2023-05-24 21:48 UTC, dsilvam approved these changes

2023-05-25 13:26 UTC, jcastro-dotcms approved these changes

2023-05-26 14:57 UTC, merged