Issue 25071: favorite pages update cards and add star
dotCMS/core pull request #25107
Opened 2023-05-31 22:11 UTC by danielmdob

### Proposed Changes
* Remove star symbol for editing bookmark in pages panel
* Add star symbol besides checklist

### Checklist
- [X] Tests
- [X] Translations
- [X] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
![image](https://github.com/dotCMS/core/assets/29465918/d6f5a51e-da3d-400d-9839-cc42e60e2269) |  ![image](https://github.com/dotCMS/core/assets/29465918/fa998d88-29af-45e8-bb08-e7338cb1892b) ![image](https://github.com/dotCMS/core/assets/29465918/cadddfb5-aa0e-4f8a-aa47-4bc68cc0f57c)

2023-05-31 22:17 UTC, jdotcms approved these changes

2023-06-01 12:55 UTC, zJaaal approved these changes

2023-06-01 14:09 UTC, manuelrojas approved these changes

2023-06-01 15:47 UTC, rjvelazco approved these changes

2023-06-01 17:41 UTC, fmontes requested changes

2023-06-01 17:41 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/portlets/dot-pages/dot-pages-favorite-panel/dot-pages-favorite-panel.component.scss
> +    }
We need to move this to the panel scss file and it should look like our icon button.

2023-06-01 20:45 UTC, zJaaal approved these changes

2023-06-02 14:20 UTC, merged