#24895 Creating a new operator REGEX to avoid this problem
dotCMS/core pull request #25112
Opened 2023-06-01 16:37 UTC by freddyucv

### Proposed Changes
* change 1
* change 2

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2023-06-13 16:22 UTC, jcastro-dotcms requested changes

2023-06-13 16:22 UTC, jcastro-dotcms commented on dotCMS/src/integration-test/java/com/dotcms/experiments/business/ExperimentAPIImpIntegrationTest.java
> +>>>>>>> origin/master
Merging problems?

2023-06-13 19:29 UTC, jdotcms approved these changes

2023-06-20 15:47 UTC, jcastro-dotcms approved these changes

2023-06-21 14:17 UTC, merged