key/value sorting functionality should not mix data
dotCMS/core pull request #25402
Opened 2023-06-30 18:20 UTC by AndreyDotcms

### Proposed Changes
*The sorting functionality should be applied to each key/value field independently, without mixing or altering the data between fields.

### Summary
Add the sort listener only for the current element, not for all on the page.

### Updated Record

https://github.com/dotCMS/core/assets/127987858/75c773e0-a092-4728-bedf-59278f4f4c3e

rd

2023-06-30 19:15 UTC, zJaaal approved these changes

2023-07-03 14:48 UTC, rjvelazco approved these changes

2023-07-03 16:06 UTC, fmontes requested changes

2023-07-03 16:06 UTC, fmontes commented on core-web/libs/dotcms-webcomponents/src/components/contenttypes-fields/dot-key-value/dot-key-value.tsx
> +        const tblElement = targetElement.querySelector('table');
You might want to use `this.el.querySelector` here as well.

2023-07-05 16:56 UTC, fmontes approved these changes

2023-07-05 18:17 UTC, jdotcms commented on core-web/libs/dotcms-webcomponents/src/components/contenttypes-fields/dot-key-value/components/key-value-table/key-value-table.tsx
> +    @Element() el: HTMLElement;
would be better to rename to currentElement?

2023-07-13 15:00 UTC, erickgonzalez approved these changes

2023-07-13 15:12 UTC, merged