dotCMS/core#25317 [UI] Add Add to Push Publish to the 3 dots Menu in Experiment Configuration
dotCMS/core pull request #25447
Opened 2023-07-07 20:24 UTC by hmoreras

### Proposed Changes
* Add Push Publish Option in the experiment listing and configuration screens. 

### Screenshots

#### Listing

<img width="1078" alt="image" src="https://github.com/dotCMS/core/assets/31667212/456ab389-3240-4143-b229-cde13f467a21">

#### Configuration 

<img width="1035" alt="image" src="https://github.com/dotCMS/core/assets/31667212/6f5955a4-df0b-4ef9-8304-5dd4f1472a7b">

#### Dialog ( Standard across DotCMS ) 

<img width="533" alt="image" src="https://github.com/dotCMS/core/assets/31667212/d8ac593d-2815-4c52-b046-3829eec81596">

2023-07-10 14:02 UTC, zJaaal requested changes, later dismissed

2023-07-10 16:35 UTC, fmontes requested changes, later dismissed

2023-07-10 16:35 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/portlets/shared/resolvers/dot-push-publish-enviroments-resolver.service.ts
Is this new? no tests?

2023-07-10 16:35 UTC, fmontes commented on core-web/package-lock.json
Good question.

2023-07-10 18:31 UTC, oidacra approved these changes

2023-07-10 19:44 UTC, zJaaal commented on core-web/package-lock.json
@fmontes Is there a way to warn us that we are commiting the `package-lock.json`?

I'm seeing that this is happening to all of us and it would be awesome to have a confirm dialog or something that tell us that we are commiting this file, just to be sure that we really want to commit this in case we installed a new dependency and not do it by accident.

2023-07-11 18:40 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/portlets/shared/resolvers/dot-push-publish-enviroments-resolver.service.ts
done

2023-07-11 20:58 UTC, hmoreras commented on core-web/package-lock.json
removed from the PR.

2023-07-12 14:31 UTC, freddyucv approved these changes

2023-07-12 14:47 UTC, merged