#25587 first draft for scripting role on secret tool
dotCMS/core pull request #25588
Opened 2023-07-21 17:14 UTC by jdotcms

Adding a constraint for Scripting Developer role on velocity secrets

2023-08-28 18:55 UTC, wezell requested changes
see feedback

2023-08-28 18:55 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/rendering/velocity/viewtools/SecretTool.java
> +            throw new SecurityException("External scripting is disabled in your dotcms instance.");
Just throw a SecurityException once in the `canUserEvaluate` and get rid of all these if statements

2023-08-28 18:55 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/rendering/velocity/viewtools/SecretTool.java
> +				hasScriptingRole = APILocator.getRoleAPI().doesUserHaveRole(user, scripting);
I think I would check this second, to prevent cache churn.  The majority of use cases will use the template to find out if it should be rendered

2023-09-06 19:27 UTC, AndreyDotcms approved these changes
The requested changes were applied, LGTM.

2023-09-13 16:58 UTC, jcastro-dotcms approved these changes

2023-09-14 14:29 UTC, merged