dotCMS/core#25688 [UI] Add Multi-Land and Personas on experiments (variants)
dotCMS/core pull request #25717
Opened 2023-08-07 18:47 UTC by hmoreras

### Proposed Changes
* Put back the ability to select a language and personas in experiments layout.

2023-08-07 19:01 UTC, zJaaal requested changes
do we need tests for this?

2023-08-07 20:05 UTC, hmoreras commented
> do we need tests for this?

we never put them when initially added a few months ago.

2023-08-07 20:09 UTC, zJaaal approved these changes

2023-08-08 15:39 UTC, oidacra approved these changes

2023-08-08 18:59 UTC, merged