dotCMS/core#25722 [UI] Content palette should show when editing a variant
dotCMS/core pull request #25807
Opened 2023-08-16 21:08 UTC by hmoreras

### Proposed Changes
* content palette wasn't showing when refresh the page in, a experiment variant. 

### Checklist
- [ x ] Tests not needed.

2023-08-17 13:18 UTC, zJaaal approved these changes

2023-08-17 13:25 UTC, fmontes requested changes

2023-08-17 13:25 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/content/dot-edit-content.component.html
> +            *ngIf="(isEnterpriseLicense | async) && isEditMode && allowedContent"
```suggestion
            *ngIf="(isEnterpriseLicense$ | async) && isEditMode && allowedContent"
```

2023-08-17 13:25 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/content/dot-edit-content.component.ts
> +    isEnterpriseLicense = of(false);
```suggestion
    isEnterpriseLicense$ = of(false);
```

2023-08-17 20:51 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/content/dot-edit-content.component.html
> +            *ngIf="(isEnterpriseLicense | async) && isEditMode && allowedContent"
done

2023-08-18 18:25 UTC, fmontes approved these changes

2023-08-21 08:15 UTC, merged