Fix #25860: Add Theme Column for Template Listing
dotCMS/core pull request #26129
Opened 2023-09-15 20:10 UTC by zJaaal

will update when I have more progress

Blocked By: https://github.com/dotCMS/core/pull/26107/

2023-09-18 21:18 UTC, oidacra approved these changes

2023-09-18 21:28 UTC, fmontes requested changes

2023-09-18 21:28 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/portlets/dot-templates/dot-template-list/dot-template-list.component.spec.ts
> +            expect(mockGoToFolder).toHaveBeenCalled();
```suggestion
            expect(mockGoToFolder).toHaveBeenCalled();
```
```suggestion
            expect(mockGoToFolder).toHaveBeenCalledWith(xx, xx, xxx);
```

2023-09-18 21:28 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/portlets/dot-templates/dot-template-list/dot-template-list.component.spec.ts
> +            expect(mockGoToFolder).not.toHaveBeenCalled();
System theme have no folder, so should not have link

2023-09-18 21:28 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/portlets/dot-templates/dot-template-list/dot-template-list.component.spec.ts
> +            expect(mockGoToFolder).not.toHaveBeenCalled();
If you are only testing the render, why are you doing the click?

2023-09-18 21:28 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/portlets/dot-templates/dot-template-list/dot-template-list.component.ts
> +        this.dotSiteBrowserService.setSelectedFolder(path).subscribe(() => {
```suggestion
        this.dotSiteBrowserService.setSelectedFolder(path).pipe(take(1)).subscribe(() => {
```

2023-09-18 21:36 UTC, zJaaal commented on core-web/apps/dotcms-ui/src/app/portlets/dot-templates/dot-template-list/dot-template-list.component.ts
> +        this.dotSiteBrowserService.setSelectedFolder(path).subscribe(() => {
That method takes one under the hood

2023-09-19 14:13 UTC, fmontes approved these changes

2023-09-19 14:13 UTC, merged