Fix of prod error fix
dotCMS/core pull request #26139
Opened 2023-09-16 01:17 UTC by victoralfaro-dotcms

2023-09-18 11:56 UTC, dsilvam approved these changes

2023-09-18 13:36 UTC, wezell requested changes
This change seems to incorporate Sanchez's DotSecrets changes.  It should be a cleaner PR.

2023-09-18 14:01 UTC, spbolton approved these changes

2023-09-19 17:25 UTC, wezell approved these changes
Looks good. Let's see if it can build.

2023-09-19 17:35 UTC, merged