feat(edit-ema): Sync client and editor routing
dotCMS/core pull request #26808
Opened 2023-11-23 03:59 UTC by fmontes

### Proposed Changes
* Emit event from customer
* Catch event in Angular and update the routing
* There is a reload of the iframe, not sure how can avoid it.

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2023-11-27 20:56 UTC, hmoreras approved these changes

2023-11-27 20:57 UTC, oidacra approved these changes

2023-11-28 12:38 UTC, zJaaal requested changes

2023-11-28 12:38 UTC, zJaaal commented on core-web/libs/portlets/dot-ema/src/lib/shared/enums.ts
> +    SET_URL = 'set-url', // The customer hit add button
Fix the comment here.

2023-11-28 12:38 UTC, zJaaal commented on ema/nextjs/src/components/dotcms-page.js
> +    }, [pathname]);
We need to talk about this.

2023-11-28 13:45 UTC, zJaaal approved these changes

2023-11-28 13:45 UTC, zJaaal commented on ema/nextjs/src/components/dotcms-page.js
> +    }, [pathname]);
Left as it is.

2023-11-28 13:48 UTC, KevinDavilaDotCMS approved these changes

2023-11-28 13:48 UTC, merged