Upgrading xstream to version 1.4.20
dotCMS/core pull request #26936
Opened 2023-12-08 17:14 UTC by nollymar

### Proposed Changes
* xstream lib was upgraded from 1.4.17 to 1.4.20 to fix some security vulnerabilities

2024-01-04 13:36 UTC, spbolton requested changes, later dismissed
@nollymar.longa If you view the check run and download the log archive you can see the following in the 0_JVM IT Tests - JDK 11 MainSuite 1a.txt file.    Although your code changes have Added xstream.addPermission in ContentHandler this is not the only place that an Xstream instance is created.  The error shows that Xstream is used from com.dotcms.publisher.business.PublishAuditHistory.getObjectFromString and it uses an instance of XStream created on line 116 of PublishAuditHistory "static XStream xstream=new XStream(new DomDriver());"

So we don't have to add permissions to every time we create a new XStream object in the code we need to refactor to make sure all cases we use Xstream use the same instance through a singleton or instance from a generated with the same permissions with a factory.   Searching the whole codebase for "new XStream("  can easily find all the cases that will need to be refactored.

```
9:00:54.036 f1 main INFO  junit.RuleWatcher - >>>>>>>>>>>>>>>>>>>>>>>>>>
2023-12-20T19:00:54.0466285Z 19:00:54.036 f1 main INFO  junit.RuleWatcher - >>> createStaticBundle[0: com.dotcms.enterprise.publishing.staticpublishing.StaticPublisherIntegrationTestHelper$TestCase@3aa63af2](com.dotcms.enterprise.publishing.staticpublishing.StaticPublisherIntegrationTest) - starting...
2023-12-20T19:00:54.0469118Z 19:00:54.036 f1 main INFO  junit.RuleWatcher - >>>>>>>>>>>>>>>>>>>>>>>>>>
2023-12-20T19:00:54.0470646Z 19:00:54.038 f1 main INFO  util.StdOutErrLog - [class com.dotcms.enterprise.publishing.staticpublishing.StaticPublisher]
2023-12-20T19:00:54.1464167Z 19:00:54.064 f1 main ERROR business.PublishAuditHistory - com.dotcms.publisher.business.PublishAuditHistory
2023-12-20T19:00:54.1470169Z 19:00:54.045 f1 main INFO  util.PushPublishLogger - class com.dotcms.publisher.business.PublishAuditStatus : Status Update: Pending.
2023-12-20T19:00:54.1472432Z com.thoughtworks.xstream.security.ForbiddenClassException: com.dotcms.publisher.business.PublishAuditHistory
2023-12-20T19:00:54.1474520Z 	at com.thoughtworks.xstream.security.NoTypePermission.allows(NoTypePermission.java:26) ~[xstream-1.4.20.jar:1.4.20]
2023-12-20T19:00:54.1475951Z 	at com.thoughtworks.xstream.mapper.SecurityMapper.realClass(SecurityMapper.java:74) ~[xstream-1.4.20.jar:1.4.20]
2023-12-20T19:00:54.1477110Z 	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125) ~[xstream-1.4.20.jar:1.4.20]
2023-12-20T19:00:54.1479016Z 	at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:47) ~[xstream-1.4.20.jar:1.4.20]
2023-12-20T19:00:54.1481426Z 	at com.thoughtworks.xstream.core.util.HierarchicalStreams.readClassType(HierarchicalStreams.java:29) ~[xstream-1.4.20.jar:1.4.20]
2023-12-20T19:00:54.1482956Z 	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:135) ~[xstream-1.4.20.jar:1.4.20]
2023-12-20T19:00:54.1484274Z 	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32) ~[xstream-1.4.20.jar:1.4.20]
2023-12-20T19:00:54.1485466Z 	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1464) ~[xstream-1.4.20.jar:1.4.20]
2023-12-20T19:00:54.1486457Z 	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1441) ~[xstream-1.4.20.jar:1.4.20]
2023-12-20T19:00:54.1487367Z 	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1321) ~[xstream-1.4.20.jar:1.4.20]
2023-12-20T19:00:54.1488252Z 	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1312) ~[xstream-1.4.20.jar:1.4.20]
2023-12-20T19:00:54.1489442Z 	at com.dotcms.publisher.business.PublishAuditHistory.getObjectFromString(PublishAuditHistory.java:128) ~[dotcms-core-1.0.0-SNAPSHOT.jar:?]
2023-12-20T19:00:54.1490938Z 	at com.dotcms.publisher.mapper.PublishAuditStatusMapper.mapObject(PublishAuditStatusMapper.java:18) ~[dotcms-core-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
2023-12-20T19:00:54.1493407Z 	at com.dotcms.publisher.business.PublishAuditAPIImpl.getPublishAuditStatus(PublishAuditAPIImpl.java:234) ~[dotcms-core-1.0.0-SNAPSHOT.jar:?]
2023-12-20T19:00:54.1496147Z 	at com.dotcms.publisher.business.PublishAuditAPIImpl.getPublishAuditStatus(PublishAuditAPIImpl.java:213) ~[dotcms-core-1.0.0-SNAPSHOT.jar:?]
2023-12-20T19:00:54.1499076Z 	at com.dotcms.publisher.business.PublishAuditAPIImpl.isPublishRetry(PublishAuditAPIImpl.java:495) ~[dotcms-core-1.0.0-SNAPSHOT.jar:?]
2023-12-20T19:00:54.1501429Z 	at com.dotcms.publishing.PublisherAPIImpl.publish(PublisherAPIImpl.java:116) ~[dotcms-core-1.0.0-SNAPSHOT.jar:?]
```

2024-01-05 16:09 UTC, jdotcms approved these changes

2024-01-05 21:56 UTC, AndreyDotcms commented
Please review, so many tests are failing

2024-01-22 16:09 UTC, dcolina approved these changes

2024-01-23 13:43 UTC, merged