Fix #26988: Edit EMA render the Template Builder in Layout
dotCMS/core pull request #27014
Opened 2023-12-14 15:17 UTC by zJaaal

will update when I got more progress.

2023-12-19 19:06 UTC, fmontes requested changes

2023-12-19 19:06 UTC, fmontes commented on core-web/libs/portlets/dot-ema/src/lib/services/dot-page-api.service.ts
> +    containers: DotPageContainerStructure;
Why don't we do a `Pick` here of what we need? is just an idea so we can easily mock stuff around, well if that helps.

2023-12-19 20:01 UTC, zJaaal commented on core-web/libs/portlets/dot-ema/src/lib/edit-ema-layout/edit-ema-layout.component.ts
> +    private pageID: string;
I saw it. I forgot to change it LOL

2023-12-19 20:03 UTC, zJaaal commented on core-web/libs/portlets/dot-ema/jest.config.ts
> +    transformIgnorePatterns: ['<rootDir>/node_modules/(?!.*\\.mjs$)'],
Yes! Gridstack is not supported by Jest, so we add this to ignore the whole node modules. You did it in Template Builder for the same reason. Here is the [docs](https://jestjs.io/docs/code-transformation)

2023-12-19 20:05 UTC, zJaaal commented on core-web/apps/dotcms-ui/.storybook/tsconfig.json
> +        "../../../libs/dotcms-models/src/lib/navigation"
I didn't explicitly changed this. I'll discard this.

2023-12-20 14:29 UTC, zJaaal commented on core-web/libs/portlets/dot-ema/src/lib/edit-ema-editor/edit-ema-editor.component.spec.ts
Yes. Already fixed

2023-12-20 14:31 UTC, zJaaal commented on core-web/libs/portlets/dot-ema/src/lib/dot-ema-shell/store/dot-ema.store.spec.ts
> +                expect(state as unknown).toEqual({
Tbh I did this to clean the logs to write the tests of layout. Indeed we need to fix this, thanks for the reminding me

2023-12-20 14:33 UTC, zJaaal commented on core-web/libs/portlets/dot-ema/src/lib/edit-ema-layout/edit-ema-layout.component.spec.ts
> +            const updateTemplate = jest.spyOn(component.updateTemplate, 'next');
LOL

2023-12-20 14:51 UTC, zJaaal commented on core-web/libs/portlets/dot-ema/src/lib/dot-ema-shell/store/dot-ema.store.spec.ts
> +                expect(state as unknown).toEqual({
Fixed!

2023-12-20 16:15 UTC, fmontes approved these changes

2023-12-20 16:58 UTC, KevinDavilaDotCMS approved these changes

2023-12-20 17:21 UTC, merged