Update Tags_Resource_V2.postman_collection.json
dotCMS/core pull request #27052
Opened 2023-12-19 09:56 UTC by rashik1144

### Added the following postman test:

* XSS injection test in the 'save-tags' API

2023-12-19 15:41 UTC, rashik1144 commented
@bryanboza The status code is still 200 when XSS is present. We may need to solve this as this shouldn't be functionally correct. Tag is not admin only feature.

2024-01-05 16:04 UTC, jdotcms approved these changes

2024-01-05 21:03 UTC, AndreyDotcms approved these changes

2024-01-23 03:56 UTC, mbiuki commented
@bryanboza - is this ready to merge?

2024-01-30 16:48 UTC, jdotcms approved these changes

2024-01-31 15:55 UTC, nollymar requested changes
Please fix the broken test

2024-02-05 03:22 UTC, mbiuki commented
@rashik1144 - can you please address the comment?

2024-02-05 03:23 UTC, rashik1144 commented
@mbiuki We may need to add positive and negative test in different one by making copy.

2024-03-20 06:21 UTC, mbiuki commented
We are not going to fix XSS issues of the same nature. Please close this pull request.

2024-03-20 06:21 UTC, closed without merging