feat(edit-page) ask to copy non-existent language page
dotCMS/core pull request #27311
Opened 2024-01-10 22:11 UTC by oidacra

### Proposed Changes
* change 1
* change 2

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2024-01-11 18:35 UTC, fmontes reviewed
Looking good.

2024-01-12 13:29 UTC, fmontes requested changes

2024-01-12 13:29 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/content/components/dot-edit-page-view-as-controller/dot-edit-page-view-as-controller.component.spec.ts
https://github.com/dotCMS/core/assets/751424/4bc3c9d3-eb07-4008-b22e-08ad312eac71

2024-01-12 13:29 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/content/components/dot-edit-page-view-as-controller/dot-edit-page-view-as-controller.component.spec.ts
The confirmation dialog:

Title: Create New Language Version?

Message:
Page does not exist in the selected language. Create a new version in [selected language]?

2024-01-12 16:09 UTC, oidacra commented on core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/content/components/dot-edit-page-view-as-controller/dot-edit-page-view-as-controller.component.spec.ts
<img width="819" alt="Screenshot 2024-01-12 at 11 09 06 AM" src="https://github.com/dotCMS/core/assets/1909643/a8a4faec-4269-4875-b94a-3d9b4677fc19">

Done.

2024-01-12 16:09 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/portlets/dot-edit-page/content/components/dot-edit-page-view-as-controller/dot-edit-page-view-as-controller.component.spec.ts
Push push :D

2024-01-16 12:46 UTC, zJaaal approved these changes

2024-01-16 13:05 UTC, fmontes approved these changes

2024-01-16 14:28 UTC, merged