chore(edit-content): Use DotContentletThumbnail Component in Binary File
dotCMS/core pull request #27321
Opened 2024-01-11 20:55 UTC by rjvelazco

2024-01-12 17:13 UTC, zJaaal requested changes

2024-01-12 17:15 UTC, rjvelazco commented on core-web/libs/dotcms-webcomponents/src/elements/dot-contentlet-thumbnail/dot-contentlet-thumbnail.tsx
> +        console.log(this.contentlet);
Thanks!

2024-01-12 19:00 UTC, KevinDavilaDotCMS commented on core-web/libs/edit-content/src/lib/fields/dot-edit-content-binary-field/components/dot-binary-field-preview/dot-binary-field-preview.component.html
> +            <ng-container *ngIf="tempFile; else contentletThumbnail">
is necessary wrap in ng-container here?

2024-01-12 19:42 UTC, fmontes requested changes

2024-01-12 19:42 UTC, fmontes commented on core-web/libs/dotcms-webcomponents/src/elements/dot-video-thumbnail/dot-video-thumbnail.tsx
> +                    )
Is no src, should we add an icon?

2024-01-12 19:42 UTC, fmontes commented on core-web/libs/edit-content/src/lib/fields/dot-edit-content-binary-field/components/dot-binary-field-preview/dot-binary-field-preview.component.html
> +            <ng-container *ngIf="tempFile; else contentletThumbnail">
Looks like not.

2024-01-12 19:42 UTC, fmontes commented on core-web/libs/ui/src/lib/components/dot-temp-file-thumbnail/dot-temp-file-thumbnail.component.ts
> +    selector: 'dot-temp-file-thumbnail',
Where do we use this?

2024-01-12 20:07 UTC, KevinDavilaDotCMS approved these changes

2024-01-16 12:50 UTC, zJaaal approved these changes

2024-01-16 13:36 UTC, fmontes approved these changes

2024-01-16 15:04 UTC, oidacra commented on core-web/libs/dotcms-webcomponents/src/components.d.ts
> +        "playableVideo": boolean;
this file is generated?

2024-01-16 15:04 UTC, oidacra approved these changes

2024-01-16 15:51 UTC, merged