#27878 removing the lock to look for on the cache
dotCMS/core pull request #27889
Opened 2024-03-07 18:55 UTC by jdotcms

removing the look for the system cache look up on the system table

2024-03-11 12:59 UTC, wezell commented on dotCMS/src/main/java/com/dotcms/business/CacheableEagerFactory.java
> +        final Map<K, V> records = new LinkedHashMap<>();
Why a LinkedHashMap?  Why a TreeMap?

2024-03-12 18:20 UTC, jdotcms commented on dotCMS/src/main/java/com/dotcms/business/CacheableEagerFactory.java
> +        final Map<K, V> records = new LinkedHashMap<>();
I think it was a mistake good catch

2024-03-15 12:32 UTC, wezell requested changes

2024-03-15 12:32 UTC, wezell commented on dotcms-integration/src/test/java/com/dotcms/vanityurl/business/VanityUrlAPITest.java
> +    @Ignore  // this test is not valid anymore since now all contents are saved as json
delete it

2024-03-15 13:28 UTC, jcastro-dotcms approved these changes

2024-03-19 18:56 UTC, wezell approved these changes
looks good

2024-03-19 22:33 UTC, merged