fix(edit-content-2): Internal Links Navigation Bug
dotCMS/core pull request #28098
Opened 2024-03-27 22:25 UTC by fmontes

### Proposed Changes
* Listen the click and check if is an href
* The downside is that any JavaScript base navigation will fail.

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2024-03-27 23:19 UTC, oidacra approved these changes

2024-04-02 13:01 UTC, zJaaal requested changes

2024-04-02 13:01 UTC, zJaaal commented on core-web/libs/portlets/edit-ema/portlet/src/lib/edit-ema-editor/edit-ema-editor.component.ts
> +                        }
What happens if the href if an external link?

2024-04-03 18:16 UTC, zJaaal approved these changes

2024-04-03 21:24 UTC, fmontes commented
Close cuz pipeline.

2024-04-03 21:24 UTC, closed without merging