Feat(Edit Contentlet): Allow user to configure Image URL Format Pattern in WYSIWYG Field
dotCMS/core pull request #28120
Opened 2024-04-01 16:42 UTC by rjvelazco

- Allow users to configure image URL pattern for the `WYSIWYG` field

### Video

https://github.com/dotCMS/core/assets/72418962/81203899-263e-4b31-a093-f095bb27b11c

2024-04-01 20:13 UTC, zJaaal requested changes

2024-04-01 20:13 UTC, zJaaal commented on core-web/libs/edit-content/src/lib/fields/dot-edit-content-wysiwyg-field/dot-wysiwyg-plugin/utils/editor.utils.ts
> +        .replace(/{shortyId}/g, asset.identifier.replace('-', '').substring(0, 10));
Can we avoid this? There should be a better way to do this.

2024-04-01 21:06 UTC, KevinDavilaDotCMS approved these changes

2024-04-01 21:08 UTC, fmontes approved these changes

2024-04-02 13:00 UTC, zJaaal approved these changes

2024-04-02 15:13 UTC, rjvelazco commented on core-web/libs/edit-content/src/lib/fields/dot-edit-content-wysiwyg-field/dot-wysiwyg-plugin/dot-wysiwyg-plugin.service.ts
> +            .getKey('WYSIWYG_IMAGE_URL_PATTERN')
Since this is an HTTP request, it will trigger only once

2024-04-02 18:22 UTC, merged