Issue 27725 new user field exceeds 100 characters
dotCMS/core pull request #28148
Opened 2024-04-03 23:45 UTC by Neehakethi

SQL Errors on Demo

https://github.com/dotCMS/core/assets/139247809/3b3962d8-149c-499c-ae8b-42059724edbb

Changes made to throw validation messages are below 

https://github.com/dotCMS/core/assets/139247809/e97b9358-ab65-4442-af40-bcfe4fe2df4e

2024-04-04 15:11 UTC, erickgonzalez requested changes

2024-04-04 15:11 UTC, erickgonzalez commented on dotCMS/src/test/java/com/dotmarketing/util/UtilMethodsTest.java
> +	@Test
Let's add Doc, here is an example:

```
    /**
     * Method to test: {@link Config#getStringProperty(String, String)}
     * Given Scenario: Will request a property that does not exist on config nor system table
     * ExpectedResult: Should return default value
     */
```

2024-04-04 20:17 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/business/UserFactoryImpl.java
> +        } catch (DotDataException e) {
you may want to log debug this

2024-04-04 20:17 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/business/UserHelper.java
> +    public static void validateMaximumLength(String firstName, String lastName, String email) throws DotDataException {
set to final the parameters

2024-04-04 20:17 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/business/UserHelper.java
> +    public static void validateMaximumLength(String firstName, String lastName, String email) throws DotDataException {
good

2024-04-04 20:18 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/util/UtilMethods.java
> +        if (value instanceof String) {
you may want to user Charsequence instead of String to have more subclasses covered
set parameters to final too

2024-04-04 20:52 UTC, Neehakethi commented on dotCMS/src/main/java/com/dotmarketing/business/UserFactoryImpl.java
> +            validateMaximumLength(user.getFirstName(),user.getLastName(),user.getEmailAddress());
Validation can be moved and will be placed in below methods related (Both backend and API-related)
UserAjax.addUser
UserAjax.updateUser
UserResource.createUser
UserAPIImpl.save

We will discuss this and proceed accordingly

2024-04-08 16:47 UTC, erickgonzalez approved these changes

2024-04-10 19:45 UTC, dsolistorres approved these changes

2024-04-16 20:47 UTC, merged