set current user on viewtools velocity context for email subaction (#28352)
dotCMS/core pull request #28373
Opened 2024-04-29 14:07 UTC by dsolistorres

### Proposed Changes
* Changed `executeAction()` method from `EmailActionlet` class to set the velocity context using the http request, that allow to the view tools list dotcontent to get the current user from the request attributes.
* Added a new integration test to check that the velocity context has the appropriate user and dotcontent viewtool works as expected.

### Checklist
- [x] Tests

2024-04-29 16:30 UTC, nollymar requested changes

2024-04-29 16:35 UTC, erickgonzalez commented on dotcms-integration/src/test/java/com/dotmarketing/portlets/workflows/actionlet/EmailActionletTest.java
> +public class EmailActionletTest extends BaseWorkflowIntegrationTest {
I talked with @spbolton he told me that the MainSuite should be removed, since it's no longer used.

2024-04-29 17:25 UTC, jdotcms approved these changes

2024-04-29 17:28 UTC, nollymar approved these changes

2024-04-30 20:09 UTC, erickgonzalez approved these changes

2024-04-30 22:49 UTC, merged