#27959-embeddings: adding integration tests for EmbeddingsTool
dotCMS/core pull request #28488
Opened 2024-05-08 17:49 UTC by victoralfaro-dotcms

And refactoring direct calls from Runner and Resource classes to rather use EmbeddingsAPI calls annotated with transaction annotations.

2024-05-10 22:34 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/ai/api/EmbeddingsRunner.java
> +                embeddingsAPI.deleteEmbedding(deleteOldVersions);
Nice!

2024-05-10 22:39 UTC, dsilvam requested changes

2024-05-10 22:39 UTC, dsilvam commented on dotcms-integration/src/test/java/com/dotcms/ai/viewtool/SearchToolTest.java
> +=======
Merging issue

2024-05-13 14:46 UTC, freddyDOTCMS approved these changes

2024-05-13 15:57 UTC, dsilvam approved these changes

2024-05-13 18:06 UTC, merged