#28059 Postman test enhancements
dotCMS/core pull request #28515
Opened 2024-05-09 20:42 UTC by bryanboza

### Proposed Changes
* change 1
* change 2

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2024-05-09 21:32 UTC, dsilvam approved these changes

2024-05-09 23:04 UTC, jgambarios approved these changes

2024-05-14 00:27 UTC, spbolton requested changes
If you could modify .github/filters.yaml and add an entry for - 'dotcms-postman/**' above the similar entry for dotcms-integration it should make sure that your PR causes the postman tests to actually run in the PR build so issues are found before being added to the merge queue.  Theoretically we could split out the flags so it does not run the integration tests, but it does not really add more time to the build as they are run in parallel, just would save resources. 

Thanks.

2024-05-14 18:53 UTC, bryanboza commented
> If you could modify .github/filters.yaml and add an entry for - 'dotcms-postman/**' above the similar entry for dotcms-integration it should make sure that your PR causes the postman tests to actually run in the PR build so issues are found before being added to the merge queue. Theoretically we could split out the flags so it does not run the integration tests, but it does not really add more time to the build as they are run in parallel, just would save resources.
> 
> Thanks.

Done

2024-05-14 22:03 UTC, spbolton approved these changes

2024-05-15 03:33 UTC, merged