#22033 Start The PruneTimeMachineJob
dotCMS/core pull request #28586
Opened 2024-05-16 15:57 UTC by freddyDOTCMS

### Proposed Changes
* change 1
* change 2

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2024-05-16 19:46 UTC, jcastro-dotcms approved these changes

2024-05-16 21:54 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/timemachine/business/TimeMachineAPIImpl.java
> +        runPruneTimeMachineJo();
Let's schedule it regardless.

2024-05-16 21:54 UTC, dsilvam requested changes
See comments

2024-05-23 16:47 UTC, dsilvam approved these changes

2024-05-23 17:02 UTC, victoralfaro-dotcms commented on dotcms-integration/src/test/java/com/dotcms/timemachine/business/TimeMachineAPITest.java
> +import static org.junit.Assert.*;
Use individual imports.

2024-05-23 17:19 UTC, freddyDOTCMS commented on dotcms-integration/src/test/java/com/dotcms/timemachine/business/TimeMachineAPITest.java
> +import static org.junit.Assert.*;
done https://github.com/dotCMS/core/pull/28586/commits/e0bd87dfea0bd0324573561b2965758e59ff248a

2024-05-23 17:20 UTC, victoralfaro-dotcms approved these changes

2024-05-23 21:44 UTC, merged