Issue 28563 removing template ajax and js deps
dotCMS/core pull request #28618
Opened 2024-05-20 22:36 UTC by jdotcms

First draft to remove the templateAjax

2024-05-21 13:34 UTC, jcastro-dotcms requested changes

2024-05-21 13:34 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/template/TemplateResource.java
> +     * Return live version {@link com.dotmarketing.portlets.templates.model.Template} based on the id
Javadoc doesn't seem to match the method's definition, or it's name is not right.

2024-05-24 18:42 UTC, dsolistorres approved these changes

2024-05-24 19:30 UTC, freddyDOTCMS reviewed
postman test?

2024-05-24 19:32 UTC, freddyDOTCMS requested changes

2024-05-28 20:25 UTC, wezell commented on dotCMS/src/main/java/com/dotmarketing/portlets/templates/business/TemplateAPIImpl.java
> +	public Contentlet getImageContentlet(final Template template) throws DotDataException, DotSecurityException {
Probably should return an optional

2024-05-28 20:25 UTC, wezell approved these changes
Left a comment but still approving.

2024-05-28 20:41 UTC, freddyDOTCMS approved these changes

2024-05-28 21:49 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/portlets/templates/business/TemplateAPIImpl.java
> +	public Contentlet getImageContentlet(final Template template) throws DotDataException, DotSecurityException {
feedback done, thx

2024-05-28 21:54 UTC, wezell approved these changes
Nice stuff!

2024-06-06 21:36 UTC, jcastro-dotcms approved these changes

2024-06-06 22:55 UTC, merged