#28719: Adding AI Generative postman tests
dotCMS/core pull request #28795
Opened 2024-06-07 03:44 UTC by victoralfaro-dotcms

2024-06-10 18:10 UTC, dsilvam commented on dotcms-postman/src/main/resources/postman/AI.postman_collection.json
> +				{
These postman tests are missing negative cases

2024-06-10 18:11 UTC, dsilvam requested changes, later dismissed
Include negative cases for the postman tests

2024-06-10 18:41 UTC, freddyDOTCMS approved these changes
According to the title, it looks like it is just postman test but we are including several changes in code here.
I think that maybe we should sent this changes on a second PR

2024-06-10 23:55 UTC, victoralfaro-dotcms commented on dotcms-postman/src/main/resources/postman/AI.postman_collection.json
> +				{
Negative postman tests added.

2024-06-11 18:55 UTC, dsilvam approved these changes

2024-06-11 23:30 UTC, merged