disable localization enhancements feature for release
dotCMS/core pull request #28866
Opened 2024-06-12 22:50 UTC by fabrizzio-dotCMS

### Proposed Changes
* We're simply disabling this feature as it is not ready for relase

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2024-06-12 22:54 UTC, jdotcms approved these changes

2024-06-12 22:56 UTC, nollymar requested changes
Disable it in the dotmarketing-config instead

2024-06-12 23:22 UTC, fabrizzio-dotCMS commented
> Disable it in the dotmarketing-config instead

done

2024-06-13 00:02 UTC, nollymar approved these changes

2024-06-13 03:13 UTC, merged