feat(sdk): Add missing code
dotCMS/core pull request #28864
Opened 2024-06-12 18:23 UTC by KevinDavilaDotCMS

### Proposed Changes
* Added CustomNoComponent code (missed in some PR)
* Added env variable for HTTPS pages

2024-06-12 19:14 UTC, zJaaal approved these changes
Approved with one suggestion

2024-06-12 19:14 UTC, zJaaal commented on examples/nextjs/.env.local.example
> +# This is for HTTPS server
Can we add a link with the docs of node for a further explanation of how this works?

2024-06-12 19:33 UTC, fmontes requested changes

2024-06-12 19:33 UTC, fmontes commented on examples/nextjs/.env.local.example
> +# This is for HTTPS server
```suggestion
# If your local dotcms instance is running in https, this setting allows Node.js to connect to servers with invalid SSL certificates. For testing purposes only.
```

2024-06-12 20:23 UTC, KevinDavilaDotCMS commented on examples/nextjs/.env.local.example
> +# This is for HTTPS server
Added!

2024-06-13 15:55 UTC, nicobytes approved these changes

2024-06-13 16:06 UTC, jdotcms approved these changes

2024-06-13 16:44 UTC, fmontes approved these changes

2024-06-13 18:04 UTC, merged