fix: Issue 28846 fixing templates select
dotCMS/core pull request #28872
Opened 2024-06-13 16:35 UTC by jdotcms

Trying to fix the template on edit page

2024-06-13 20:10 UTC, zJaaal requested changes

2024-06-13 20:10 UTC, zJaaal commented on dotCMS/src/main/webapp/html/js/dotcms/dojo/data/TemplateReadStore.js
> +				.then(async () => {
Maybe we should take the response from the arguments of this function

`.then(async ( response ) =>{...`

2024-06-14 19:12 UTC, zJaaal approved these changes

2024-06-14 22:50 UTC, dsilvam approved these changes

2024-06-16 06:31 UTC, merged