Filter system host when is isRequired
dotCMS/core pull request #28931
Opened 2024-06-18 20:15 UTC by nicobytes

If a host/folder field is marked as required, then we do not allow/show SYSTEM_HOST

### Proposed Changes
* Add isRequired attr to enable filter

### Checklist
- [x] Tests
- [x] Translations
- [x] Security Implications Contemplated (add notes if applicable)

2024-06-18 21:01 UTC, zJaaal requested changes

2024-06-18 21:01 UTC, zJaaal commented on core-web/libs/edit-content/src/lib/fields/dot-edit-content-host-folder-field/store/methods/loadSites.ts
> +                            return sites;
Maybe this can be one filter

2024-06-18 21:10 UTC, nicobytes commented on core-web/libs/edit-content/src/lib/fields/dot-edit-content-host-folder-field/store/methods/loadSites.ts
> +                            return sites;
@zJaaal Great suggestion, already done!

2024-06-18 21:21 UTC, zJaaal approved these changes

2024-06-18 21:31 UTC, zJaaal approved these changes

2024-06-19 00:47 UTC, oidacra commented on core-web/libs/edit-content/src/lib/fields/dot-edit-content-host-folder-field/store/methods/loadSites.spec.ts
> +        const rxMethod = TestBed.runInInjectionContext(() => loadSites(store, service));
I was wondering how this was done.

2024-06-19 00:48 UTC, oidacra approved these changes

2024-06-19 02:41 UTC, fmontes commented
Are we sure this is the right approach? Because why required will exclude the system host?

What load without a value and if is marked as required user will have to add a value and that value could be system host.

If we don't want the user to select system host we can do something else? Blacklist maybe? 

I don't know all the details behind this reasoning, but this is a component we might be using in a lot of places.

2024-06-19 02:47 UTC, dsilvam commented
@fmontes RE: don't show system host if required: 
tagged you on Slack in the thread were this was discussed.

2024-06-19 03:28 UTC, fmontes requested changes

2024-06-19 03:28 UTC, fmontes commented on core-web/libs/edit-content/src/lib/fields/dot-edit-content-host-folder-field/store/methods/loadSites.ts
> +                            }
Not sure about this... why required will remove SYSTEM_HOS?

2024-06-19 03:32 UTC, fmontes approved these changes

2024-06-19 14:59 UTC, merged