#28084 fix force html highlighting for .vtl files
dotCMS/core pull request #29166
Opened 2024-07-09 04:11 UTC by valentinogiardino

### Proposed Changes
* Introduced logic to set the editor's language to HTML when editing VTL files:

1. Extracted file extension logic into extractFileExtension.
2. Created setVelocityLanguage for .vtl file handling.
3. Moved language update logic for other extensions to updateLanguageForFileExtension.
4. Extracted validateFileType logic to check file types in all cases.

### Screenshots
![html-highlighting-for-vtl-files](https://github.com/dotCMS/core/assets/77643678/04aa6902-487a-4536-8222-820edae4c453)

2024-07-09 14:13 UTC, nicobytes commented on core-web/libs/edit-content/src/lib/fields/dot-edit-content-binary-field/components/dot-binary-field-editor/dot-binary-field-editor.component.ts
>          this.mimeType = mimetypes?.[0];
@valentinogiardino Should the mimeType have a default value if `mimetypes?.[0]` is undefined?

2024-07-09 14:19 UTC, rjvelazco requested changes

2024-07-09 14:19 UTC, rjvelazco commented on core-web/libs/edit-content/src/lib/fields/dot-edit-content-binary-field/components/dot-binary-field-editor/dot-binary-field-editor.component.ts
> +        }
We need to write a test to cover this case

2024-07-09 14:33 UTC, fmontes approved these changes

2024-07-10 14:27 UTC, rjvelazco approved these changes

2024-07-10 16:38 UTC, merged