Fixed IQA
dotCMS/core pull request #29262
Opened 2024-07-18 12:48 UTC by KevinDavilaDotCMS

### Proposed Changes
* Fixed IQA issues

https://github.com/user-attachments/assets/4e2bfb5b-264c-4f3d-96d7-bba529c1a556

2024-07-18 13:43 UTC, nicobytes approved these changes

2024-07-18 14:09 UTC, oidacra approved these changes

2024-07-18 14:27 UTC, fmontes requested changes

2024-07-18 14:27 UTC, fmontes commented on core-web/apps/dotcms-ui/src/app/view/components/_common/dot-autocomplete-tags/dot-autocomplete-tags.component.scss
> +                        white-space: nowrap;
The chips should not be full width, must be `fit-content`, one next to each other and wrap when no space like:

```
----------------------------------------
| tag 1 | | tag 2 | | tag 3 | | tag 4 |
| tag 5 | | tag 6 |
----------------------------------------
```

2024-07-19 13:23 UTC, zJaaal approved these changes

2024-07-21 23:41 UTC, hmoreras approved these changes

2024-07-22 13:42 UTC, fmontes approved these changes

2024-07-22 16:13 UTC, merged