fix #29083 Remove layout attribute from Content Type descriptor
dotCMS/core pull request #29357
Opened 2024-07-25 18:06 UTC by valentinogiardino

### Proposed Changes
* Add `layout` attribute to `@JsonIgnoreProperties`
* Add test cases for content type layout attribute
* Add `ContentTypeTestHelperService` class with methods to facilitate testing

This PR fixes #29083

2024-07-26 15:15 UTC, jgambarios approved these changes

2024-07-26 16:05 UTC, nollymar approved these changes

2024-07-29 14:05 UTC, spbolton requested changes
Sonarqubes reported 1 new issue should be resolved.   It is thinking that ContentTypeLayoutUtilTest.java is a test class and saying there are no test cases in there.    This is not just sonarqube, but maven also uses *Test.java format as a way to identify the test java files which this is not.   This file should not end in Test to prevent confusion here.

2024-07-29 15:41 UTC, spbolton approved these changes

2024-07-31 19:00 UTC, merged