feat(AI): Providing a fallback for invalid models #29284
dotCMS/core pull request #29413
Opened 2024-07-31 03:14 UTC by victoralfaro-dotcms

2024-07-31 22:13 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/ai/api/AIServices.java
> +public class AIServices {
javadoc

2024-07-31 22:13 UTC, dsilvam commented on dotCMS/src/main/java/com/dotcms/ai/config/ProviderConfig.java
> +public class ProviderConfig {
doc

2024-08-01 13:30 UTC, jcastro-dotcms requested changes

2024-08-01 13:30 UTC, jcastro-dotcms commented on dotCMS/src/main/java/com/dotcms/ai/model/request/AIRequest.java
> +public class AIRequest<T extends Serializable> {
Let's add some doc here please

2024-08-09 15:23 UTC, closed without merging