Fix no show rows in permissions
dotCMS/core pull request #29542
Opened 2024-08-12 19:18 UTC by oidacra

### Proposed Changes
* Fix no-show rows in permissions

<img width="1183" alt="Screenshot 2024-08-12 at 2 17 09 PM" src="https://github.com/user-attachments/assets/55d56d38-5c57-42ee-822d-ba3824f00048">

2024-08-12 19:53 UTC, hmoreras requested changes

2024-08-12 19:53 UTC, hmoreras commented on dotCMS/src/main/webapp/html/portlet/ext/common/edit_permissions_tab_js_inc.jsp
> +		console.info('adjustAccordionHeigth',container);
remove

2024-08-12 20:02 UTC, zJaaal approved these changes

2024-08-12 20:39 UTC, oidacra commented on dotCMS/src/main/webapp/html/portlet/ext/common/edit_permissions_tab_js_inc.jsp
> +		console.info('adjustAccordionHeigth',container);
done.

2024-08-12 20:51 UTC, hmoreras approved these changes

2024-08-13 15:00 UTC, nicobytes approved these changes

2024-08-13 15:43 UTC, merged