Create sbom folder in the core repo
dotCMS/core pull request #29585
Opened 2024-08-14 05:26 UTC by rashik1144

Add 'sbom' folder in the core repo.

2024-08-14 05:27 UTC, mbiuki approved these changes

2024-08-14 05:28 UTC, mbiuki commented
We would need a new folder otherwise the sbom workflow would crash.

2024-08-14 17:12 UTC, sfreudenthaler requested changes
Oh interesting.  That brings in another question.  For the lines of the workflow, the commentary and the code don't match
https://github.com/dotCMS/core/blob/8e575648b1cde3c07aaf2dddf3c73208e9decf28/.github/workflows/legacy-release_sbom-generator.yaml#L66-L71

I missed it in the [last PR](https://github.com/dotCMS/core/pull/29467).  It's not trying to commit to the [core-test-results](https://github.com/dotcms/core-test-results) repo, but the core repo itself.

Can we remedy this disconnect as part of the PR here?  Alternatively what do you think about updating the action to actually checkout and commit back to that [core-test-results repo](https://github.com/dotcms/core-test-results)

2024-08-15 05:49 UTC, mbiuki commented
We do not need this anymore.

2024-08-15 05:49 UTC, closed without merging