chore: fix error with strictTemplates
dotCMS/core pull request #29630
Opened 2024-08-16 22:20 UTC by nicobytes

### Proposed Changes
* change 1
* change 2

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2024-08-16 22:31 UTC, hmoreras requested changes

2024-08-16 22:31 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/view/components/dot-toolbar/components/dot-toolbar-user/dot-toolbar-user.component.ts
Do not include this file in this PR. I will fix it as part of https://github.com/dotCMS/core/issues/29534

2024-08-16 23:19 UTC, hmoreras approved these changes

2024-08-19 15:44 UTC, fmontes approved these changes

2024-08-19 23:57 UTC, merged