implementantion(fix): #29534 Login-as popup show's in the incorrect position.
dotCMS/core pull request #29631
Opened 2024-08-16 23:16 UTC by hmoreras

### Proposed Changes
* Hide mask when menu close. 

### Before 

https://github.com/user-attachments/assets/bb75bc88-7e73-48eb-98c0-bbd53e6f9c79

### After

https://github.com/user-attachments/assets/f35abb40-9250-4bf4-8e22-898814bb3e58

2024-08-19 12:56 UTC, zJaaal approved these changes

2024-08-19 13:16 UTC, nicobytes requested changes

2024-08-20 15:49 UTC, hmoreras commented on core-web/apps/dotcms-ui/src/app/view/components/dot-toolbar/components/dot-toolbar-user/dot-toolbar-user.component.ts
>      @ViewChild('menu') menu: Menu;
done

2024-08-20 15:52 UTC, zJaaal approved these changes

2024-08-20 15:56 UTC, nicobytes approved these changes
LGTM

2024-08-20 17:44 UTC, merged