Issue 29213 Copying a contentlet without having Edit Permissions causes copy to have incorrect permissions.
dotCMS/core pull request #29744
Opened 2024-08-23 19:14 UTC by gortiz-dotcms

2024-09-05 01:40 UTC, erickgonzalez requested changes

2024-09-05 01:40 UTC, erickgonzalez commented on dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java
> +    private final String IS_COPY = "isCopy";
Looks like we already have a content property https://github.com/dotCMS/core/blob/4c3a898a308cadc2247a06fbee5397ed629d04f8/dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/model/Contentlet.java#L170 let's check if we can use it. If not let's add the property to the class mentioned, so you can call it from diff places.

2024-09-09 14:57 UTC, erickgonzalez approved these changes

2024-09-09 16:23 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/business/PermissionBitAPIImpl.java
> +		if (permissionable instanceof Contentlet){
I would encapsulate this into a method isCopy()
this methods are already so big

2024-09-09 16:23 UTC, jdotcms commented on dotCMS/src/main/java/com/dotmarketing/business/PermissionBitAPIImpl.java
> +		if(!isCopy) {
the same herem checkCopyPermissions or so

2024-09-09 16:24 UTC, jdotcms approved these changes
I have left some optional comments just in case

2024-09-10 17:53 UTC, merged