implementation (category field): #29563 Change category selection from PrimeNG sidebar to dialog
dotCMS/core pull request #29770
Opened 2024-08-27 22:01 UTC by hmoreras

### Proposed Changes
* Moving Category field from sidebar to Dialog. 

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2024-08-28 20:53 UTC, nicobytes requested changes

2024-08-28 20:53 UTC, nicobytes commented on core-web/libs/edit-content/src/lib/fields/dot-edit-content-category-field/components/dot-category-field-dialog/dot-category-field-dialog.component.ts
> +    @Output() closedDialog = new EventEmitter<void>();
@hmoreras I suggest using the new API for outputs and transforms this into: `closedDialog = output<void>();`

2024-08-28 20:53 UTC, nicobytes commented on core-web/libs/edit-content/src/lib/fields/dot-edit-content-category-field/components/dot-category-field-dialog/dot-category-field-dialog.component.ts
>      @Input() visible = false;
@hmoreras Please use signal inut here.

2024-08-29 13:26 UTC, nicobytes approved these changes

2024-08-29 14:29 UTC, zJaaal approved these changes

2024-08-29 16:56 UTC, merged