Issue #29742 Adding Documentation to Api-token Endpoints
dotCMS/core pull request #29783
Opened 2024-08-29 15:28 UTC by gavriella-dotcms

### Proposed Changes
* Adding documentation to api-token endpoints

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2024-09-12 16:15 UTC, nollymar approved these changes

2024-09-12 16:30 UTC, jdcmsd requested changes
In this case we'll be specifying three properties, all of them object types. The description can further explain what its sub-properties might be.

2024-09-12 16:30 UTC, jdcmsd commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/authentication/ApiTokenResource.java
> +                                        "| `revoked`    | Boolean   | Value for if token is revoked or not |",
This might need a revisit; looks like the properties specified here don't match the ones given in the example immediately below.

2024-09-16 20:55 UTC, jdcmsd approved these changes

2024-09-17 15:36 UTC, jdcmsd commented
Even when it's at the head of a fresh merge queue, we get these API rate limit errors causing a rejection.

I've created an issue for this in EOS.

2024-09-23 17:17 UTC, merged