fix(deployment): Edit Page V2 Automate the deploy of the SDK librar (#28259)
dotCMS/core pull request #29876
Opened 2024-09-04 18:29 UTC by dcolina

### Proposed Changes
* This pull request introduces an improved approach for managing version increments and dependency updates for the dotCMS SDK libraries. Unlike the previous solution that handled version calculations locally before committing, this new method performs version calculation and updates directly within the continuous integration flow, specifically after a merge and during the deployment phase.

The new solution ensures that all SDK libraries in the repository are updated centrally and consistently. Key improvements include:

Version Updates: Automatically increments the version of each SDK package found in the relevant directory.
Dependency Management: Updates peerDependencies between SDK libraries to maintain internal compatibility.
NPM Publishing: Publishes each updated SDK library to the NPM registry, ensuring that the latest versions are readily available.

### Additional Info
Related to #28259 (Edit Page V2 Automate the deploy of the SDK librar).

2024-09-04 19:41 UTC, nollymar approved these changes

2024-09-04 20:50 UTC, spbolton approved these changes

2024-09-04 21:40 UTC, fmontes requested changes

2024-09-04 21:40 UTC, fmontes commented on .github/actions/core-cicd/deployment/deploy-sdk-npm/README.md
What about renaming to `deploy-javascript-sdk` and all related to JavaScript SDK, to make it very clear.

2024-09-05 11:14 UTC, dcolina commented on .github/actions/core-cicd/deployment/deploy-sdk-npm/README.md
Done.

2024-09-05 15:15 UTC, fmontes approved these changes

2024-09-05 22:41 UTC, merged