fix ( Edit Content ): #29690 New Content Edit: Remove label for constant field
dotCMS/core pull request #29885
Opened 2024-09-05 02:09 UTC by hmoreras

### Proposed Changes
* change 1
* change 2

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

2024-09-05 19:13 UTC, oidacra approved these changes

2024-09-05 20:19 UTC, nicobytes requested changes

2024-09-05 20:19 UTC, nicobytes commented on core-web/libs/edit-content/src/lib/models/dot-edit-content-field.enum.ts
> +    WYSIWYG = 'WYSIWYG'
Great!

2024-09-05 20:34 UTC, hmoreras commented on core-web/libs/edit-content/src/lib/components/dot-edit-content-form/dot-edit-content-form.component.spec.ts
> +            ...data.contentlet,
that comes with the original mock, including `archived`, here just adding the extra fields

2024-09-05 20:34 UTC, hmoreras commented on core-web/libs/edit-content/src/lib/components/dot-edit-content-form/dot-edit-content-form.component.html
> +                                            [contentlet]="formData.contentlet"
it will be undefined until the actual content exist, meaning in the creation of content will be null

2024-09-05 22:02 UTC, nicobytes approved these changes

2024-09-06 15:45 UTC, zJaaal approved these changes

2024-09-09 00:22 UTC, merged