Issue 29865 query parser
dotCMS/core pull request #30004
Opened 2024-09-13 20:33 UTC by jdotcms

Draft of the query parser for analytics

2024-09-18 04:57 UTC, jcastro-dotcms approved these changes

2024-09-18 14:27 UTC, freddyDOTCMS requested changes

2024-09-18 15:58 UTC, jdotcms commented on dotCMS/src/test/java/com/dotcms/analytics/query/AnalyticsQueryParserTest.java
> +     * 	"timeDimensions":Events.day day",
totally, will leave as it is, and can improve future forward

2024-09-19 21:07 UTC, freddyDOTCMS approved these changes

2024-09-20 04:45 UTC, merged