#30192 adding the date range parsing
dotCMS/core pull request #30208
Opened 2024-10-01 22:12 UTC by jdotcms

Adding the ability to parse date range to the time dimension

2024-10-01 22:40 UTC, jcastro-dotcms approved these changes

2024-10-01 22:49 UTC, freddyDOTCMS requested changes

2024-10-01 22:49 UTC, freddyDOTCMS commented on dotCMS/src/test/java/com/dotcms/analytics/query/TimeDimensionParserTest.java
> +}
Perhaps try another test using a value like 'yesterday.' 'This week' is a two-word phrase, whereas 'yesterday' is just one word.

Maybe another test without extra spaces ''Events.day  day This Week"

Maybe another one with "Last 7 days" three-word phase

2024-10-07 17:17 UTC, freddyDOTCMS approved these changes

2024-10-07 18:03 UTC, freddyDOTCMS approved these changes

2024-10-08 20:40 UTC, merged