ci: Add Semgrep to workflows (#30610)
dotCMS/core pull request #30611
Opened 2024-11-08 15:43 UTC by spbolton

### Proposed Changes
* enable semgrep in workflows in parallel with sonarqube
* add ability to use github vars DISABLE_SONAR=true and DISABLE_SEMGREP=true on the repository to disable if issues without pushing code change

2024-11-08 16:32 UTC, dcolina requested changes

2024-11-08 16:32 UTC, dcolina commented on .github/workflows/cicd_comp_semgrep-phase.yml
> +          name: ddependency-tree.zip
I think there is a typo here.

2024-11-08 17:33 UTC, dcolina approved these changes

2024-11-11 14:10 UTC, spbolton commented
vars.SEMGREP_NO_FAIL is enabled to allow us to merge the base code into main without fixing the issues found at this time.  We can remove this flag when we are ready.

2024-11-11 14:20 UTC, valentinogiardino approved these changes

2024-11-11 16:36 UTC, merged