docs(api): Refactoring swagger response code annotations
dotCMS/core pull request #30986
Opened 2024-12-19 19:27 UTC by jdcmsd

### Proposed Changes
* Moved a few `@ApiResponse` annotations into the class & removed them from methods

2024-12-23 13:12 UTC, valentinogiardino requested changes

2024-12-23 14:56 UTC, jdcmsd commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/workflow/WorkflowResource.java
> +                    @ApiResponse(responseCode = "405", description = "Method Not Allowed") // if param string blank
Added, will correct on the next commit.

2024-12-23 14:56 UTC, jdcmsd commented on dotCMS/src/main/java/com/dotcms/rest/api/v1/workflow/WorkflowResource.java
> +                    @ApiResponse(responseCode = "405", description = "Method Not Allowed") // if param string blank
In that case, the argument for including 405 is the overall accessibility of the code, while the argument against including it is that it's not a response people should expect that an unchanging API call in their code should ever have to handle. I'll discuss it with @bryanboza.

2024-12-23 18:07 UTC, valentinogiardino approved these changes
Nice work in this refactor. LGTM!

2024-12-26 16:06 UTC, nollymar approved these changes

2024-12-26 19:15 UTC, merged