#9853 Including IntegrationTestInitService.java
dotCMS/core pull request #9855
Opened 2016-09-29 21:15 UTC by nollymar

- Adding new singleton class to set up web environment for integration tests. Class name: IntegrationTestInitService.java
- Replacing call set up in ContentletBaseTest.java

2016-09-29 21:20 UTC, jdotcms requested changes

2016-09-29 21:20 UTC, jdotcms commented on test/com/dotmarketing/util/IntegrationTestInitService.java
> +    private static boolean initCompleted;
Use AtomicBoolean to make it thread-safe

2016-09-29 21:30 UTC, nollymar commented on test/com/dotmarketing/util/IntegrationTestInitService.java
> +    private static boolean initCompleted;
Suggestion included in the PR

2016-09-29 22:07 UTC, freddyucv commented on test/com/dotmarketing/util/IntegrationTestInitService.java
> +        }
Really it is not a thread safe way to implement a singleton.
here explain my point: 
http://crunchify.com/thread-safe-and-a-fast-singleton-implementation-in-java/

2016-09-30 14:23 UTC, nollymar commented on test/com/dotmarketing/util/IntegrationTestInitService.java
> +        }
I have applied changes to make the singleton class thread safe.
Thanks!

2016-09-30 22:15 UTC, jdotcms approved these changes

2016-09-30 22:15 UTC, dsilvam approved these changes

2016-09-30 22:15 UTC, merged