#9798 pushing SAVE_BASE_CONTENT_TYPE, UPDATE_BASE_CONTENT_TYPE and DE…
dotCMS/core pull request #9871
Opened 2016-10-03 12:34 UTC by freddyucv

…LETE_BASE_CONTENT_TYPE

2016-10-03 14:51 UTC, jdotcms requested changes

2016-10-03 14:51 UTC, jdotcms commented on src/com/dotmarketing/portlets/structure/factories/StructureFactory.java
> +			throw new RuntimeException( e );
We already have a i18n runtime base class, could be used here instead

2016-10-03 19:40 UTC, jgambarios approved these changes

2016-10-03 19:53 UTC, oswaldogallango commented on src/com/dotmarketing/portlets/structure/business/StructureAPI.java
> +import javax.servlet.http.HttpServletRequest;
remove this import.

2016-10-03 20:10 UTC, jdotcms requested changes

2016-10-03 20:10 UTC, jdotcms commented on src/com/dotcms/notifications/BaseContentTypeSystemEventProcessor.java
> +        ContentTypeView contentTypeView = ContentTypeView.getInstance(structure, contentTypePayloadDataWrapper.getActionUrl());
The ContentTypeView should be a class attribute instead of getting the instance static.

2016-10-04 13:46 UTC, oswaldogallango approved these changes

2016-10-04 17:05 UTC, merged