Fixed dotCMS/core#9917 by replacing publishing-bundle's owner and adding foreign-key constraint
dotCMS/core pull request #9951
Opened 2016-10-11 23:49 UTC by agomez-dotcms

2016-10-11 23:51 UTC, jgambarios approved these changes

2016-10-12 00:21 UTC, jdotcms requested changes

2016-10-12 00:21 UTC, jdotcms commented on src/com/dotcms/publisher/bundle/business/BundleFactoryImpl.java
> +			return;
shouldn't report an exception or something?

2016-10-12 00:21 UTC, jdotcms commented on src/com/dotmarketing/business/UserAPIImpl.java
> +		BundleAPI bundleAPI = APILocator.getBundleAPI();
we should avoid to get api reference on the code, better to use a class attribute. It is easier for testing proposes.

2016-10-12 14:52 UTC, jdotcms approved these changes

2016-10-12 14:54 UTC, freddyucv commented on src/com/dotcms/publisher/bundle/business/BundleFactory.java
> +
it should be final too

2016-10-12 14:56 UTC, freddyucv approved these changes

2016-10-13 17:23 UTC, merged