Fixed dotCMS/core#9730 by introducing fix-task that updates invalid asset-type in identifiers
dotCMS/core pull request #9966
Opened 2016-10-12 22:45 UTC by agomez-dotcms

2016-10-13 17:49 UTC, dsilvam requested changes

2016-10-13 17:49 UTC, dsilvam commented on src/com/dotmarketing/fixtask/tasks/FixTask00015FixAssetTypesInIdentifiers.java
> +						} catch (DotDataException e) {
What's the reason for this catch? and if we want to leave it there, shouldn't it be affecting the total that is set in FixAssetsProcessStatus.setErrorsFixed(total)?

2016-10-13 17:49 UTC, dsilvam commented on src/com/dotmarketing/fixtask/tasks/FixTask00015FixAssetTypesInIdentifiers.java
> +				Audit.setAction("task 20: Fixed DeleteOrphanedIdentifiers");
should be 'task 15' with its description here

2016-10-13 18:05 UTC, agomez-dotcms commented on src/com/dotmarketing/fixtask/tasks/FixTask00015FixAssetTypesInIdentifiers.java
> +						} catch (DotDataException e) {
I think the try/catch may be removed. query should not fail unless there is a fatal error (such as network / database connection issue). I will remove it from FixTask00020DeleteOrphanedIdentifiers as well.

2016-10-13 18:08 UTC, agomez-dotcms commented on src/com/dotmarketing/fixtask/tasks/FixTask00015FixAssetTypesInIdentifiers.java
> +				Audit.setAction("task 20: Fixed DeleteOrphanedIdentifiers");
Absolutely... thanks for the comments!

2016-10-13 18:27 UTC, dsilvam approved these changes

2016-10-17 17:34 UTC, jgambarios approved these changes

2016-10-17 17:35 UTC, merged